### ISSUE TITLE
Docker for mac intermittently fails and won't start until computer is restarted

### ISSUE THREAD

**Issue by bmleshopventory** [docker/for-mac#1090]
Diagnostic ID: DF92E328-FF43-4EAE-93C7-20B3F72ECD0C

Docker for Mac: version: 1.12.5 (3e6f00c1d)
OS X: version 10.11 (build: 15A284)
logs: /tmp/DF92E328-FF43-4EAE-93C7-20B3F72ECD0C/20161228-182633.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by kennytrytek-wf** [comment]
I am seeing the same issue. The Docker for Mac whale icon menu shows that Docker is "starting" but it never successfully starts.
```
$ docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      darwin/amd64
Error response from daemon: Bad response from Docker engine
```

**Comment by djs55** [comment]
@bmleshopventory I see in your diagnostics upload the misleading error message
```
Dec 20 09:29:31 ... Docker[com.docker.driver.amd64-linux][46959] <Notice>: vmx_init: processor not supported by Hypervisor.framework
Dec 20 09:29:31 ... Docker[com.docker.driver.amd64-linux][46959] <Notice>: Unable to create VM (-85377018)
```
At least, I assume it's misleading because if you can run Docker for Mac at all, your processor must support it. Perhaps the error code from the macOS `hypervisor.framework` is wrong. My current theory is that the root cause is some kind of resource exhaustion, perhaps caused by leaking `hyperkit` processes. There have been some recent bug fixes on the beta channel which will soon be released in stable -- if you have the time, could you try with the latest beta (34.1)? It's available from

https://download.docker.com/mac/beta/Docker.dmg

**Comment by djs55** [comment]
@kennytrytek-wf is your issue also fixed by a reboot? Could you also try beta 34.1 and see if it helps? If it doesn't could you upload a diagnostics on a fresh issue (the root cause may be different even if the symptoms look similar)

**Comment by kennytrytek-wf** [comment]
@djs55, reboot did not fix the issue. I was able to work around it by following the advice at https://forums.docker.com/t/docker-is-not-responding-console-ring-doesnt-exist/9886/7 and deleting the contents of the Library directory: `$ rm -rf ~/Library/Containers/com.docker.docker`.

I should note that I'm on OS X Yosemite 10.10.5, which I believe is not officially supported by Docker any more. I'll try the beta first, and potentially upgrade to El Capitan if I'm still seeing the bad behavior.

**Comment by bmleshopventory** [comment]
@djs55 I'll give the beta a shot and see how it goes. This generally happens if the machine has been idle for a while. Not sure if that helps.

**Comment by dsheets** [comment]
@bmleshopventory are you still experiencing this issue? You may also want to try upgrading your OS X installation to 10.11.6 from 10.11.0 which may contain `hypervisor.framework` bugs that were fixed in later releases.

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
