### ISSUE TITLE
com.docker.osx.hyperkit.linux failed to start

### ISSUE THREAD

**Issue by monotone** [docker/for-mac#1185]
### Expected behavior
start docker 

### Actual behavior

> com.docker.osx.hyperkit.linux failed to start
> Exit code 1

![Uploading image.png…]()

### Information
```

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G31)
logs: /tmp/A846893D-1441-40CA-BFDF-FEFB5CA089DD/20170122-153957.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/danny/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/danny/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/danny/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/danny/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/danny/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/danny/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

```
Diagnostic ID: A846893D-1441-40CA-BFDF-FEFB5CA089DD

### Steps to reproduce the behavior
  1. just start the docker

**Comment by Catorpilor** [comment]
same issue here！
when upgrade docker to 1.3.1

**Comment by briangonzalez** [comment]
@Catorpilor @monotone 

I fixed this by opened the app before it would shut down and then clicking "Reset to Factory Defaults"

![screen shot on 2017-01-22 at 08-21-36](https://cloud.githubusercontent.com/assets/659829/22183832/f3eae470-e07b-11e6-8918-0580693bda24.png)

**Comment by monotone** [comment]
@briangonzalez I have try it before this issus here.  still not work.

**Comment by ddffx** [comment]
The same issue happened in my Mac, OS X El Capitan 10.11.6. The only way I was able to **get it working**:
1. Force reinstall the older version 1.12
2. Uninstall Docker and remove the application by moving it to trash
3. Install Docker 1.13

**Comment by erickfgb89** [comment]
It took a bit of training to win the race against the password prompt, but resetting to defaults worked for me with 1.13 on Sierra

**Comment by kabobbob** [comment]
"Reset to factory defaults" worked for me with 1.13 on Sierra.

**Comment by frodeanonsen** [comment]
Tried "Reset to factory defaults", but it did not resolve the error
> com.docker.osx.hyperkit.linux failed to start
> Exit code 1

**Comment by yallop** [comment]
@monotone: I see this in your logs:
```
vmx_init: processor not supported by Hypervisor.framework
```

Is it possible that Intel Virtualization is disabled on your machine?

**Comment by Catorpilor** [comment]
As #1159 explained, `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` and restart docker everything works fine.

**Comment by frodeanonsen** [comment]
@yallop Enabling Intel Virtualization did the trick for me. Thanks!

**Comment by monotone** [comment]
@yallop I have used 3-rd software named MACCPUID to see VMX(VT-x) is trun on before commited this issues. And there is some tips too:
> [OK]     virtualization VT-X
> [OK] app

**Comment by monotone** [comment]
@Catorpilor I have tried that just now. It still not work.

**Comment by shatil** [comment]
What was the fix for this issue? This issue cropped up for me on my MacBook Air (13-inch Early 2015), without me changing anything. I have had Docker 1.13.0 (15072 Channel: Stable 0c6d765c4) installed and running for over a week now.

Restarting the machine appears to have allowed Docker to work again. I have never modified the VT-x settings on any macOS machine I've been running Docker on.

On my MacBook Pro (Retina 15-inch Mid 2014), I'm on the Beta channel running Version 1.13.1-rc1-beta40 (15241) 0d026e19d7, and I've never encountered this issue.

**Comment by yallop** [comment]
@monotone: thanks for the update!  I'm glad to hear that the problem is resolved for you.

@shatil: the symptoms you're seeing may not have the same cause.  A more common reason for Docker failing to start after recent updates is described in https://github.com/docker/for-mac/issues/1159#issuecomment-273899215.  If the workarounds there don't resolve the problem for you, could you please open a new issue with a diagnostic ID so that we can investigate further?

**Comment by rbpinheiro** [comment]
@Catorpilor solution solved it to me
