### ISSUE TITLE
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: server misbehaving

### ISSUE THREAD

**Issue by nabedge** [docker/for-mac#1317]
```
$ uname -a
Darwin nabedge.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
$ docker-compose --version
docker-compose version 1.11.1, build 7c5d5e4
$ docker --version
Docker version 1.13.1, build 092cba3
$ docker pull centos:6.8
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: server misbehaving
```

Is this same bug ? https://github.com/docker/for-mac/issues/1025

**Comment by ijc25** [comment]
@nabedge please use the :whale: menu :arrow_right: `Diagnose and feedback" to upload a diagnostic log ball and add the output here.

@LevonBecker, please do the same but create a fresh issue, although your symptoms seem similar the underlying cause could be different and it is far easier to de-dup issues than it is to split a single issue into two.

**Comment by nabedge** [comment]
Thanks.
I have solved this problem by re-install (uninstall -> install) the same version docker.

**Comment by LevonBecker** [comment]
sure thing

**Comment by nicksnyder** [comment]
I just had the same problem and a re-install fixed it.

**Comment by rainder** [comment]
have hte same problem but re-installing does not help.

**Comment by ferbass** [comment]
same problem after reinstall
Fixed when switching to beta version

**Comment by LevonBecker** [comment]
clean reinstall (1.13.1) did not fix for me. Switching to beta version did fix it for me.

**Comment by rainder** [comment]
my problem was fixed when I set 8.8.8.8 as a dns server

**Comment by LevonBecker** [comment]
8.8.8.8 didn't fix mine... just installing beta. It's such a random issue with random solutions that work. Very odd /shrug

**Comment by MagnusS** [comment]
@nicksnyder @rainder @ferbass @levonbecker There are several DNS fixes in the latest 17.03.x beta/stable releases, which may fix the issue for you. If you still experience problems with the latest version, please open new issues with a diagnostic ID. This is a closed issue and to figure out what is going on we would have to look at the logs. Thanks!

**Comment by ferbass** [comment]
Thank you @MagnusS the problems was solved on this version to me

`
Version 17.03.0-ce-mac2 (15654)
Channel: stable
1d7d97bbbd
`

**Comment by MikhailKaduchka** [comment]
```
docker-machine ssh default
sudo vi /etc/resolv.conf
```
change nameserver to 8.8.8.8

**Comment by richarda23** [comment]
Hi, I've just installed docker CE today, following instructions at https://docs.docker.com/engine/installation/linux/ubuntu/  and get this error as well when trying to run  or pull anything.
Ubuntu 14.04LTS:
> lsb_release -a
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

Docker 17.03:
builder@kudu:~$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:57:58 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:57:58 2017
 OS/Arch:      linux/amd64
 Experimental: false

and /etc/resolve.cnf:
nameserver 8.8.8.8
nameserver 8.8.4.4

Any suggestions appreciated, thanks!

**Comment by ranaskr** [comment]
I had the same error when I was running docker pull hello-world
```
root@someubuntumc:~# docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.1.1:53: no such host
```
I then realized that I did not configure proxy in the docker config file. Add these details to your docker config (depending on your os), I am using ubuntu so the file is - /etc/default/docker/

```
export http_proxy="http://user:pwd@proxyurl.com:port"
export https_proxy="https://user:pwd@proxy-url.com:port"
```
Restart docker (service docker restart) and this solved for me

**Comment by pnowy** [comment]
DNS server set to 8.8.8.8 fix the problem for me (Win10)

**Comment by carusology** [comment]
Same issue for Docker for Mac:
```
~$ docker pull ubuntu
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.2:47975->192.168.65.1:53: i/o timeout
```

Setting the DNS Server for the Docker Daemon via "Preferences > Daemon > Advanced" based upon advice given [here](https://github.com/moby/moby/issues/32270#issuecomment-290829987) by @thaJeztah via putting in the following value worked for me (no reinstall required):
```
{ "dns" : [ "8.8.8.8", "8.8.4.4" ]}
```

**Comment by umbruch** [comment]
all this did not help me. If you are in a company behinde a proxy use this guide, it did solve my problem
https://docs.docker.com/engine/admin/systemd/#manually-creating-the-systemd-unit-files

**Comment by zatamine** [comment]
I went lunch and it's worked when i'm back :D

**Comment by akshaygoel96** [comment]
Changing DNS server to 8.8.8.8 helped me. (Windows 10)

**Comment by omerlh** [comment]
Changing DNS server to 8.8.8.8 on Docker settings helped also for me (Windows 10).

**Comment by ShamekindsMe** [comment]
Re-installed docker and now it work.

**Comment by azamatsulaiman** [comment]
solved restarting docker from settings (windows 10)

**Comment by veeshall** [comment]
As commented by @MikhailKaduchka  the below worked for on Windows 10

> docker-machine ssh default
> sudo vi /etc/resolv.conf

change nameserver to 8.8.8.8

**Comment by samsonkolge** [comment]
If you are behind a proxy, please use the following link:
https://docs.docker.com/engine/admin/systemd/#httphttps-proxy

**Comment by kethansrinivas9** [comment]
I am also using the Windows 10 machine but i haven't shifted my env to my External Virtual Machine in docker running the following command solved my issue
docker-machine env $MY_EXTERNAL_VIRTUAL_MACHINE_NAME$

**Comment by MTWiley** [comment]
Win 10 Machine - Restarting docker fixed it for me

**Comment by jtough-github** [comment]
Windows 10 - Restarting docker fixed the problem

**Comment by GopalSingh07** [comment]
Same problem it solved after re-installed same version but before we should uninstall all like virtual box  and should be deleted .docker from C:user/username/.docker after uninstalling restart system then install once again it will work

**Comment by parand87** [comment]
change nameserver to 8.8.8.8 worked for me too

**Comment by BiscoWeb** [comment]
Resetting the docker for mac solved the issue, Its under preferences,

**Comment by vishwa-21** [comment]
Doing a System/VM reboot worked for me.

**Comment by karthik-padav** [comment]
Reinstall fixed this problem for me

**Comment by kostyanius** [comment]
reeinstall did not solve an issue. 17.07 version of docker. using 5005 port for registry in my gitlab.yml

**Comment by bliaxiong** [comment]
Super weird, i my /etc/resolve.conf was 8.8.8.8. I changed it to 8.8.4.4 and it worked.

**Comment by sidduSthawarmath** [comment]
I have added 
nameserver 8.8.4.4
 in  /etc/resolve.conf  file and it worked for me

**Comment by jerome-arzel** [comment]
This problem occurs when the network is down, specifically when the dns server did not respond.

**Comment by antonszilasi** [comment]
restarted the docker-machine solved the problem for me

**Comment by laytoneverson** [comment]
I'm running into troubles with dns resolution. I was able to resolve it once by switching the dns from 8.8.8.8 to the automatic setting; however, hours later I'm running into resolution problems again. 

*Problems inside a container: *
```                                                                                                           
host$ docker-compose exec workspace bash
root@c190ce7f5d52:/var/www# composer create-project sylius/sylius-standard acme

Do not run Composer as root/super user! See https://getcomposer.org/root for details. 
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution 
failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

  [Composer\Downloader\TransportException]
  The "http://packagist.org/p/sylius/sylius-standard%246ed7457d36c3c529786da191dbb431aea34fed81e1ce49225683223ce787de66.json" file could not be downloaded: php_network 
  _getaddresses: getaddrinfo failed: Temporary failure in name resolution
 failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
```

*Problems outside a container: *
```
C:\..\Projects\laradock [master ≡ +0 ~4 -0 !]
$ docker run busybox ping -c 1 192.203.230.10
Unable to find image 'busybox:latest' locally                                                                                                                             
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:59044->[::1]:53: read: connection refused.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'

C:\..\Projects\laradock [master ≡ +0 ~4 -0 !]                                                                                                         
$  docker pull busybox
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:36936->[::1]:53: read: connection refused
C:\..\Projects\laradock [master ≡ +0 ~4 -0 !]                                                                                                                    
$
```

A diagnostic was uploaded with id: 2E28A919-AEC5-4465-BCB2-947BFD956A67/2017-10-22_04-20-19

**Comment by NaitikShah** [comment]
`export DOCKER_HOST=`

I simply ran this command
and everything worked back to normal

**Comment by dkcwd** [comment]
Like @antonszilasi mentioned, restarting the docker machine could help if there is a network issue.  It worked for me.

If your docker machine name is ```default```:

```
eval $(docker-machine env default)
docker-machine restart default
```

You should see something like:

```
(default) Check network to re-create if needed...
(default) Waiting for an IP...
Waiting for SSH to be available...
Detecting the provisioner...
Restarted machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
```

So then you can:

```
eval $(docker-machine env default)
```

and try again.

**Comment by scythepl** [comment]
Setting docker's Settings->Network->DNS Server to fixed 8.8.8.8 helped me solve this issue in Win10

**Comment by guthyerrz** [comment]
My problem was that I had Charles configured at one point, and when I was trying to do execute a `docker pull` the Charles application was closed, and for some reason the Docker did not reset the proxy settings. So When I opened Charles again everything worked fine

**Comment by psibernetic** [comment]
My problem was I connected, and then disconnected to a VPN while Docker was running, so it had stale DNS settings.

**Comment by Stark-X** [comment]
In my case, I just using the command `systemctl restart dnsmasq` to restart the "DNS caching server", then resumed. 
Or, you could just stop it with `systemctl stop dnsmasq`  .

**Comment by akashcmit** [comment]
Changing DNS server to 8.8.8.8 on Docker settings works

**Comment by irwinwilliams** [comment]
Changing settings as per @carusology's instructions above worked for me. 
{ "dns" : [ "8.8.8.8", "8.8.4.4" ]}
I'm running this: 
 
![image](https://user-images.githubusercontent.com/1428703/33242427-46b94b5c-d2ab-11e7-9bfe-6c834102cb14.png)

With docker 
![image](https://user-images.githubusercontent.com/1428703/33242437-660b1fc6-d2ab-11e7-8492-7dac8e5f1b53.png)

**Comment by meteorlxy** [comment]
- Ubuntu 16.04.3
- Docker version 17.09.0-ce, build afdb6d4

Reinstall fixed

**Comment by ssala7** [comment]
- mac X
- Docker versions : Version 17.09.0-ce-mac35
- Changed DNS 8.8.8.8 , 8.8.4.4
- uninstall and reinstall

```Did not worked```

Nothings seems to be working for me :-(

**Comment by doruiulian** [comment]
For me as i'm behind a company proxy it helped following this solution:
https://docs.docker.com/engine/admin/systemd/#httphttps-proxy

**Comment by mingjunyang** [comment]
in china
add  config:
 "registry-mirrors" : [
    "https://docker.mirrors.ustc.edu.cn"
  ]

![image](https://user-images.githubusercontent.com/2757223/33819649-74bc8e38-de86-11e7-9a34-48570ea890d0.png)

thx mirrors.ustc.edu.cn !!!

**Comment by kevadamson** [comment]
Uninstall and reinstall fixed for me. Windows 10.

Don't be a donkey like me by not backing-up any locally databases first!

**Comment by agounaris** [comment]
Just hit this today... latest docker 

Sending build context to Docker daemon   7.68kB
Step 1/7 : FROM jenkins/jenkins:lts-alpine
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: no such host

Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by MohsenBzm** [comment]
Restarting to factory settings worked for me.

**Comment by astanciu** [comment]
Also running into this. Resetting to factory works but as soon as I run docker-compose up, it breaks to this error again.

**Comment by ganeshkondal** [comment]
I am in Mac Sierra. 8.8.8.8 DNS entry didn't work. I am not behind a proxy.

Only after doing a factory reset, I got out of the error.

**Comment by FX-HAO** [comment]
Get the same issue on macOS. I am using proxy. I configured the http and https server to `http://192.168.65.1:1087`. It did work perfectly. Setting DNS to `8.8.8.8` and `8.8.4.4` does not fix it. Dokcer version 17.12.0-ce.

**Comment by tnovau** [comment]
Setting DNS to 8.8.8.8 and 8.8.4.4 fix the problem for me in Windows 10.

**Comment by snehabarshamishra** [comment]
Worked for me as:
1) kubectl get service -n kube-system > Take the ClusterIP from the output.
2) Take the IP and put it as nameserver in /etc/resolve.conf
3) exit
4)  eval $(minikube docker-env)

**Comment by harry-chin** [comment]
On my Mac high Sierra with docker 17.12.0-ce

docker->Preference->Reset (bomb icon on right-up side) -> Reset to factory defaults is only worked for me.

**Comment by EugeneLugin** [comment]
win 8.1
docker toolbox 18.01
I had same issue till I set 8.8.8.8 as dns

**Comment by germanp** [comment]
I had the same issue on linux. I've restarted the docker service and it got solved. Before having this issue I was using a crappy cell phone connection to pull some images, so maybe it is related. So I changed to a wifi connection and restarted the daemon.

**Comment by FX-HAO** [comment]
Just tried latest release version(18.03.0-ce-mac59). The "magic" IP(192.168.65.1) seems to be unnecessary. Now it's just `localhost`, now it works.

**Comment by MikhailTymchukDX** [comment]
I worked around this by I referring to insecure registry by IP instead of symbolic name.

**Comment by IzaGz** [comment]
@MikhailKaduchka after restarting the docker-machine previous IP returned
`search mshome.net
nameserver 10.0.2.3`
does not help

**Comment by IzaGz** [comment]
@harry-chin where can i find this Preferencies? i user docker-machine

**Comment by IzaGz** [comment]
@EugeneLugin  have you fixed it?

**Comment by harry-chin** [comment]
@IzaGz you can find the docker icon on the right up of the Mac screen around WiFi status icon. Click the docker icon then click Preferences. Or move docker app using Command+Tap, and then press Command+,    It for Mac.

**Comment by SadiqueManzar** [comment]
Having same issue, installed docker but failing the below docker build command 

docker build --ulimit nofile=65535:65535 --ulimit nproc=25059:25059 -t esri/city_in_motion:0.1 .

Sending build context to Docker daemon 21.46 MB
Step 1/20 : FROM phusion/baseimage:0.10.1
Trying to pull repository registry.access.redhat.com/phusion/baseimage ...
Trying to pull repository docker.io/phusion/baseimage ...
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.37.161.54:53: no such host


uname -r
3.10.0-862.el7.x86_64

docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-63.git94f4240.el7.x86_64
 Go version:      go1.9.2
 Git commit:      94f4240/1.13.1
 Built:           Mon Apr 30 15:45:42 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-63.git94f4240.el7.x86_64
 Go version:      go1.9.2
 Git commit:      94f4240/1.13.1
 Built:           Mon Apr 30 15:45:42 2018
 OS/Arch:         linux/amd64
 Experimental:    false

docker  info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: e9c345b3f906d5dc5e8100b05ce37073a811c74a (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: 5b117de7f824f3d3825737cf09581645abbe35d4 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-862.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 11.57 GiB
Name: DX2821.etisalat.corp.ae
ID: YNDM:6SCW:HHDL:GNEJ:2L2J:5DL4:345L:SI4J:Z3JK:7NUZ:LN6W:2PBL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: registry.access.redhat.com (secure), docker.io (secure)

Kindly help , how could i fix the above error.

**Comment by IzaGz** [comment]
@harry-chin but what if i use docker-toolbox- i havent this icon. what should i do in this way?

**Comment by SadiqueManzar** [comment]
@IzaGz any solution for my above mentioned issue.

**Comment by HunderlineK** [comment]
I had this issue in windows 10 using gitbash; it was because gitbash doesn't map ports properly on windows. Use cmd, problem solved

**Comment by koji-2** [comment]
I experienced this problem with Windows for Docker.

**Environment**

Client:
 Version: 18.06.0-ce
 API version: 1.38
 Go version: go1.10.3
 Git commit: 0ffa 825
 Built: Wed Jul 18 19: 05: 28 8 2018
 OS / Arch: windows / amd64
 Experimental: false

**Error message**

```
PS C: \ WINDOWS \ system32> docker run hello-world
Unable to find image 'hello-world: latest' locally
Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup proxy on 192.168. 65.1: 53: no such host.
See 'C: \ Program Files \ Docker \ Docker \ Resources \ bin \ docker.exe run --help'.
```

**Discussion**

The proxy server had specified the host name. We thought that proxy server name resolution had failed.

**Countermeasures**

Web Server (HTTP :) `proxyservername: 8080`
Secure Web Server (HTTP :) `proxyservername: 8080`

To

Web Server (HTTP :) `IP adoption: 8080`
Secure Web Server (HTTP :) `IP adoption: 8080`

And solved it.

Everyone's post was a great hint. Thank you.

**Comment by iamnumlock** [comment]
see https://docs.docker.com/config/daemon/systemd/#httphttps-proxy

**Comment by shailendra333** [comment]
I faced same error too. Changing change nameserver to 8.8.8.8 solved. Thanks.

**Comment by cythb** [comment]
> ```
> docker-machine ssh default
> sudo vi /etc/resolv.conf
> ```
> change nameserver to 8.8.8.8

fix mine

**Comment by juliocarneiro** [comment]
set the mirror https://docker.mirrors.ustc.edu.cn worked for me! version 18.06.1-ce, build e68fc7a

**Comment by eakonovalov** [comment]
I get the same issue when I have a Cisco AnyConnect connected to a VPN. Disconnect helps.

**Comment by bijaykanshinew** [comment]
I was facing same issue on mac, i just restarted laptop and it fixed the issue :P :P :P

**Comment by renesansz** [comment]
> ```
> docker-machine ssh default
> sudo vi /etc/resolv.conf
> ```
> change nameserver to 8.8.8.8

This solved my issue. Thanks! 👍

**Comment by vanipolnedi** [comment]
Get https://registry-1.docker.io/v2/hyperledger/fabric-javaenv/manifests/x86_64-1.0.0-alpha: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:59027->127.0.0.53:53: i/o timeout 

any suggestions please ??

**Comment by bnrmaster** [comment]
> Docker for Mac的问题相同：
> 
> ```
> ~$ docker pull ubuntu
> Using default tag: latest
> Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.2:47975->192.168.65.1:53: i/o timeout
> ```
> 通过“首选项>守护程序>高级”基于给出的建议设置为码头工人守护DNS服务器[在这里](https://github.com/moby/moby/issues/32270#issuecomment-290829987)通过@thaJeztah通过将在下面的值我工作（无需重新安装）：
> 
> ```
> { "dns" : [ "8.8.8.8", "8.8.4.4" ]}
> ```
This solved my issue. Thanks! 👍

**Comment by bjdevopsmail** [comment]
> > ```
> > docker-machine ssh default
> > sudo vi /etc/resolv.conf
> > ```
> > change nameserver to 8.8.8.8
> 
> This solved my issue. Thanks! 👍

Thanks a lot it worked for me

**Comment by rosemead** [comment]
win10, docker-toolbox 18.03.0-ce.
Started docker-machine. Got above error.
Added '8.8.8.8' in HostOptions/dns to ~\.docker\machine\machines\default\config.json
restarted the docker-machine ('stop'/'start')

docker pull working...

**Comment by QingNeng** [comment]
try to restart docker

**Comment by gabodl15** [comment]
In my case, only the DNS change works.

What strikes me is that yesterday it worked with the DNS that I already had

**Comment by amit-bhandari** [comment]
Upgrading to latest version did the trick for me

**Comment by temberature** [comment]
> ```
> docker-machine ssh default
> sudo vi /etc/resolv.conf
> ```
> change nameserver to 8.8.8.8

i just add nameserver  8.8.8.8 to /etc/resolv.conf and it's done.

**Comment by unlikezy** [comment]
On mac osx, encounter the same problem.
I am using ssh proxy.
Only change dns to 8.8.8.8 doesn't work for me.

And I found that my mac IP is 192.168.1.187, but in docker->Advance->Docker subnet, that's 192.168.65.0.
![screen shot 2018-12-28 at 11 58 01 pm](https://user-images.githubusercontent.com/3445204/50520665-88858980-0afc-11e9-9e7c-fe4013ad1d17.png)

So I change the subnet to be the same subnet as my mac. It works.

**Comment by thiennhank9** [comment]
> DNS server set to 8.8.8.8 fix the problem for me (Win10)

I can't install coral-talk in windows 10, can you guide me how to run it. Thank you!

**Comment by mysim1** [comment]
> Same issue for Docker for Mac:
> 
> ```
> ~$ docker pull ubuntu
> Using default tag: latest
> Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.2:47975->192.168.65.1:53: i/o timeout
> ```
> Setting the DNS Server for the Docker Daemon via "Preferences > Daemon > Advanced" based upon advice given [here](https://github.com/moby/moby/issues/32270#issuecomment-290829987) by @thaJeztah via putting in the following value worked for me (no reinstall required):
> 
> ```
> { "dns" : [ "8.8.8.8", "8.8.4.4" ]}
> ```

sharing your privacy with Google for free is a bad idea.

**Comment by martinmani** [comment]
restarting docker solved issue for me. but does anyone know the root cause of this?

ty

**Comment by tandon-aman** [comment]
> ```
> docker-machine ssh default
> sudo vi /etc/resolv.conf
> ```
> change nameserver to 8.8.8.8

This is the best solution I find so far, thanks.

**Comment by hardsv** [comment]
I had the same issue with error 
\.docker\machine\machines\default\config.json: The system cannot find the file specified.

I have to go to my Oracle Virtual VM GUI and saw that there is a VM named 'default' which was running. I have to stop and delete it. 
Now the docker quick start working fine.

Check following link for info:
https://stackoverflow.com/questions/40052629/docker-not-working-in-windows10

**Comment by digglife** [comment]
I logged out my dockerhub account, and magically, it worked. WTF?

**Comment by data2601** [comment]
I resolve it by editing /etc/resolv.conf file.
nameserver 8.8.8.8
nameserver 8.8.4.4
add two lines in above file.

**Comment by allamiro** [comment]
> my problem was fixed when I set 8.8.8.8 as a dns server

this fixed mine as I was using pfsense firewall

**Comment by draganstanisavljevic** [comment]
I had same issue. The reason was VPN. After I disconnected from VPN, problem was fixed

**Comment by manishbansal8843** [comment]
I am facing the same issue on a ubuntu linux VM on GCP. But it is not getting resolved. I have tried adding nameserver in /etc/resolv.conf, but it is still not working.

```
manishbansal8843@instance-1:~$ docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:38063->[::1]:53: read: connection refused.
```

**Comment by chandrauppaluru** [comment]
reinstall worked for me

**Comment by carljdp** [comment]
On Windows: Uninstall / reinstall solved it for me (+ setting proxy settings if on corporate network)

**Comment by amstrudy** [comment]
For ROS users: This happened to me when I forgot to update the key. Make sure you have done that.

**Comment by harshsharma22** [comment]
reinstall worked for me

**Comment by spookyGh0st** [comment]
Turning off my vpn worked for me

**Comment by Tungtono** [comment]
Restart Docker worked for me.

**Comment by furytara** [comment]
"docker login" fix it

**Comment by talondnb** [comment]
second attempt at the same command worked for me, odd!

**Comment by zhuyingda** [comment]
Same issue for me.
Docker version: 19.03.4
MacOS version: 10.14.6

And reinstall(Preference>Reset>Uninstall> click same Docker.dmg to install) solved my problem~
Thanks.

**Comment by frostyaxe** [comment]
> As commented by @MikhailKaduchka the below worked for on Windows 10
> 
> > docker-machine ssh default
> > sudo vi /etc/resolv.conf
> 
> change nameserver to 8.8.8.8

This has worked for me too. Thanks a lot mate. I owe you a beer ;)

**Comment by karippery** [comment]
it work when I follow this doc: https://docs.docker.com/config/daemon/systemd/

**Comment by badrulhussain** [comment]
Hi on my Windows Server 2019 running on AWS EC2 I managed to install docker using powershell and run the "docker run hello-world", which works fine.
but when I try to pull and run busybox i get this error 
![image](https://user-images.githubusercontent.com/47890161/69199804-12817b00-0b31-11ea-82eb-83935305fdee.png)

I have also tried changing DNS to 8.8.8.8 
![image](https://user-images.githubusercontent.com/47890161/69199978-a8b5a100-0b31-11ea-8a43-35f0c0e9c387.png)

and even tried adding the 8.8.4.4 on alternate DNS. But I still get the same error. 
Does anyone know how to use docker on Windows server 2019?

**Comment by CompilationAnxiety** [comment]
**If you are behind an HTTP or HTTPS proxy server**, for example in corporate settings, you need to add this configuration in the Docker systemd service file.
1) Create a systemd drop-in directory for the docker service:
```
$ sudo mkdir -p /etc/systemd/system/docker.service.d
```
2) Create a file called /etc/systemd/system/docker.service.d/http-proxy.conf that adds the HTTP_PROXY environment variable:
```
[Service]
Environment="HTTP_PROXY=http://proxy.example.com:80/"
```
Or, if you are behind an HTTPS proxy server, create a file called /etc/systemd/system/docker.service.d/https-proxy.conf that adds the HTTPS_PROXY environment variable:
```
[Service]
Environment="HTTPS_PROXY=https://proxy.example.com:443/"
```

**Comment by pmaidens** [comment]
# Ubuntu Docker CE

I ran into this problem after installing the Docker CE on Ubuntu.

Following the instruction [here](https://docs.docker.com/install/linux/linux-postinstall/#specify-dns-servers-for-docker) solved my issue.

## tl;dr:

You need a `/etc/docker/daemon.json` file that contains

```JSON
{
	"dns": ["8.8.8.8", "8.8.4.4"]
}
```

Then just restart docker `sudo service docker restart`.

**Comment by gunjan1004** [comment]
### Docker on Vagrant Ubuntu Box, Windows 10 Host
Same issue got resolved after adding the following entries in /etc/resolv.conf

- nameserver 8.8.8.8
- nameserver 8.8.4.4

**Comment by gnarr** [comment]
Restart fixed this for me on Ubuntu Server 18.04 behind a pfSense

**Comment by fico7489** [comment]
On Windows 10: It started to work when I changed my WIFI connection

**Comment by Dryobs** [comment]
I had same issue on Ubuntu 16.04.
I simply stopped all my containers and the issue got resolved.

**Comment by incredimike** [comment]
macOS Catalina 10.15.3
Docker upgraded using the built-in upgrade tool. Then this issue started. Downloading Docker fresh and installing it again fixed it.

**Comment by WHK102** [comment]
Same problem from KVM image using CentOS7

```bash
[root@server ~]# docker -v
Docker version 19.03.6, build 369ce74a3c
[root@server ~]# ping -c 1 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=54 time=13.8 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 13.823/13.823/13.823/0.000 ms
[root@server ~]# cat /etc/docker/daemon.json
{
    "dns": ["8.8.8.8", "8.8.4.4"]
}
[root@server ~]# docker pull atlassian/jira-software
Using default tag: latest
Trying to pull repository docker.io/atlassian/jira-software ... 
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.x.x:53: read udp 192.168.x.x:54328->192.168.x.x:53: i/o timeout
[root@server ~]# DOCKER_OPTS="--dns=8.8.8.8" docker pull atlassian/jira-software
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.x.x:53: read udp 192.168.x.x:46200->192.168.x.x:53: i/o timeout
[root@server ~]# dig -t A registry-1.docker.io @192.168.x.x

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> -t A registry-1.docker.io @192.168.x.x
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7747
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;registry-1.docker.io.		IN	A

;; ANSWER SECTION:
registry-1.docker.io.	42	IN	A	34.199.40.84
registry-1.docker.io.	42	IN	A	52.202.253.107
registry-1.docker.io.	42	IN	A	34.201.196.144
registry-1.docker.io.	42	IN	A	34.205.88.205
registry-1.docker.io.	42	IN	A	34.228.211.243
registry-1.docker.io.	42	IN	A	34.232.31.24
registry-1.docker.io.	42	IN	A	52.201.142.14
registry-1.docker.io.	42	IN	A	34.199.77.19

;; Query time: 0 msec
;; SERVER: 192.168.x.x#53(192.168.x.x)
;; WHEN: sáb feb 15 23:49:13 -03 2020
;; MSG SIZE  rcvd: 177
```

There is something curious to see the status of the firewalld service and it is that the docker rules commands have failed since installation. Is the connection to the DNS service due to a problem in the firewall rules applied automatically in the docker installation?

```bash
[root@server ~]# cat /var/log/firewalld
2020-02-15 23:04:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER' failed: iptables v1.4.21: Couldn't load target `DOCKER':No such file or directory
Try `iptables -h' or 'iptables --help' for more information.
2020-02-15 23:04:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER' failed: iptables v1.4.21: Couldn't load target `DOCKER':No such file or directory
Try `iptables -h' or 'iptables --help' for more information.
2020-02-15 23:04:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D PREROUTING' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:04:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D OUTPUT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:04:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -F DOCKER' failed: iptables: No chain/target/match by that name.
2020-02-15 23:04:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -X DOCKER' failed: iptables: No chain/target/match by that name.
2020-02-15 23:04:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -F DOCKER' failed: iptables: No chain/target/match by that name.
2020-02-15 23:04:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER' failed: iptables: No chain/target/match by that name.
2020-02-15 23:04:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -F DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.
2020-02-15 23:04:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.
2020-02-15 23:04:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:19:01 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER' failed: iptables: No chain/target/match by that name.
2020-02-15 23:19:01 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D PREROUTING' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:19:01 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D OUTPUT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:19:01 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER' failed: iptables: Too many links.
2020-02-15 23:19:01 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER-ISOLATION' failed: iptables: Too many links.
2020-02-15 23:19:01 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:19:01 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:33:57 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER' failed: iptables: No chain/target/match by that name.
2020-02-15 23:33:57 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D PREROUTING' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:33:57 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D OUTPUT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:33:57 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER' failed: iptables: Too many links.
2020-02-15 23:33:57 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -F DOCKER-ISOLATION-STAGE-1' failed: iptables: No chain/target/match by that name.
2020-02-15 23:33:57 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER-ISOLATION-STAGE-1' failed: iptables: No chain/target/match by that name.
2020-02-15 23:33:57 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -F DOCKER-ISOLATION-STAGE-2' failed: iptables: No chain/target/match by that name.
2020-02-15 23:33:57 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER-ISOLATION-STAGE-2' failed: iptables: No chain/target/match by that name.
2020-02-15 23:33:57 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:33:57 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:35:17 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER' failed: iptables: No chain/target/match by that name.
2020-02-15 23:35:17 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D PREROUTING' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:35:17 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D OUTPUT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:35:17 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER' failed: iptables: Too many links.
2020-02-15 23:35:17 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER-ISOLATION-STAGE-1' failed: iptables: Too many links.
2020-02-15 23:35:17 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -F DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.
2020-02-15 23:35:17 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.
2020-02-15 23:35:17 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-15 23:35:18 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-16 00:04:41 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-16 00:04:41 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-16 00:08:03 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2020-02-16 00:08:03 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
```

**Comment by sreeja369** [comment]
Iam getting this issue, unable to solve.I have tried many ways like changing DNS server , restarting the windows, reinstalling the docker, but nothing worked out.Please help me solving this issue.please find the below error.


Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 100.24.246.89:443: connectex: No connection could be made because the target machine actively refused it.

**Comment by hajnalmt** [comment]
For me, I observed this issue on a Windows machine with Docker desktop version 2.2.0.3. None of the solutions worked for me, but when I turned off the firewall, the problem disappeared.  Didn't dive into the issue, but it could be helpful to somebody.

**Comment by karippery** [comment]
```
export {http,https,ftp}_proxy=your proxy :port 
export {HTTPS,HTTP,FTP}_PROXY=your proxy :port
```
 
change your network adapter in virtual machine to host adapter

**Comment by DiazAlvarran** [comment]
I had the same problem with Docker Toolbox. First it was working normal and suddenly it started giving me that error. In the task manager I finished everything related to Virtual Box and Docker, I started the docker again and it worked.

**Comment by vidurpunj** [comment]
faced same issue in the centos 7, on push command
`sudo docker push vidurpunj/mysample-app `
restarted the docker,
` sudo service docker restart `
the it uploaded, however it took multiple attempts, could be due to slow network at that point of time.

**Comment by DivekJohns** [comment]
> ```
> $ uname -a
> Darwin nabedge.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
> $ docker-compose --version
> docker-compose version 1.11.1, build 7c5d5e4
> $ docker --version
> Docker version 1.13.1, build 092cba3
> $ docker pull centos:6.8
> Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: server misbehaving
> ```
> 
> Is this same bug ? #1025

Disable proxy solved my issue :)
