### ISSUE TITLE
Cannot add back reserved volume after removing it

### ISSUE THREAD

**Issue by atombender** [docker/for-mac#138]
### Expected behavior

Should be able to add back `/Users` after removing it.

### Actual behavior

Docker for Mac says it's reserved.

### Steps to reproduce the behavior

This is what I did. Steps 3-6 are probably unnecessary.

  1. Under File Sharing tab, remove default volume `/Users`.
  2. Save and restart.
  3. Add `/Users/foo`.
  4. Save and restart.
  5. Remove `/Users/foo`.
  6. Save and restart.
  7. Add `/Users`. App now complains that `/Users` is reserved, and refuses to add it.

**Comment by dsheets** [comment]
I cannot reproduce this issue. Were there error message pop-ups during this sequence? The only known spurious error is combining descendent exports together in a single `Apply & Restart` step as mentioned in #139 (which reports the opposite).

**Comment by atombender** [comment]
I'm no longer able to reproduce this. It was not the same error as #139. I'm confident that error dialog explicitly said `/Users` is a reserved folder.

**Comment by dsheets** [comment]
I'm going to close this as neither of us can reproduce it. If you see it again, please do come back and re-open the issue with as much detail as you can remember/have saved. Thank you for your report; I appreciate that you took the time to tell us about a defect.

**Comment by atombender** [comment]
Understandable. Thanks, I will.

**Comment by maximilliangeorge** [comment]
I'm having the same issue.

### Expected behavior
Should be able to add back /Users after removing it.

### Actual behavior
Docker for Mac says:

> The path /Users is reserved by Docker however it may be possible to export specific subdirectories.
> Please see the documentation for more information.

### Steps to reproduce the behavior
This is what I did.

Under File Sharing tab, remove default volume /Users.
Save and restart.
Add /Users
Save and restart. App now complains that /Users is reserved, and refuses to add it.

**Comment by pjialin** [comment]
Same problem here and still can't find any answer to solve this.

**Docker version:  2.0.0.0-mac81 (29211)**
right now,  It's the latest version.

**Comment by pjialin** [comment]
I think this problem has been solved by me.
I removed all the containers associated with the problem directory, then restarted docker and tried to add it again. No error

This is not a good way to solve this problem, but it does work.

**Comment by estraph** [comment]
Just hit the same issue. I had removed the `/Users` entry in that menu and when trying to add back a sub-directory within it, got this error:

![image](https://user-images.githubusercontent.com/22151295/56412016-b8f35e00-627a-11e9-8057-8e42a55bf5af.png)

I ran `docker rm $(docker ps -a -q)` and removed a bunch of containers, but still had the same issue. I then restarted Docker from the app menu and after that was finally able to add the directories into that menu.

### Version info

![image](https://user-images.githubusercontent.com/22151295/56412037-cdcff180-627a-11e9-880e-8920b71a2673.png)

**Comment by estraph** [comment]
@dsheets I feel like this is still an issue and should be re-opened.

**Comment by dgm** [comment]
I too had this problem, and I had to delete all my containers and restart.

**Comment by psdevhh** [comment]
Just encountered the same issue. Very annoying, this is clearly a bug and this issue should be re-opened.

**Comment by drewtoto** [comment]
Ran into this problem today.  I had to "Reset to factory defaults" to be able to add directory back.

Docker version: 19.03.2 (6a30dfc)

**Comment by griddyphillip** [comment]
Also running into this issue. @dsheets it would be greatly appreciated if this issue was reopened

**Comment by waterfall531** [comment]
@estraph work on me...

**Comment by Lambeaux** [comment]
Also hit this issue today with a custom file path made from root. @estraph's workaround fixed it.
