### ISSUE TITLE
Bad terminal output from docker exec -it

### ISSUE THREAD

**Issue by tobi-richard-mitchell** [docker/for-mac#1694]
### Expected behavior

Normal left alignment of prompt on screen.

### Actual behavior

Return pressed 14 times ...

<img width="1151" alt="screen_shot" src="https://cloud.githubusercontent.com/assets/12239096/26808967/b6e67946-4a15-11e7-8463-27c954ab97e5.png">

### Information

  - Updated Docker seconds before this happened.
  - Happens in iTerm2 and Terminal.
  - ^D puts the terminal back to normal, after pressing return.
  - Retried after closing window and quitting app—still broken.
  - Diagnostic ID 41108689-CBC1-4E62-9528-9A7EB3EB91A8
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
    Docker for Mac: version: 17.06.0-rc1-ce-mac13 (4cdec4294a50b2233146b09469b49937dabdebdd)
    macOS: version 10.11.6 (build: 15G1510)
    logs: /tmp/41108689-CBC1-4E62-9528-9A7EB3EB91A8/20170605-172646.tar.gz
    [OK]     db.git
    [OK]     vmnetd
    [OK]     dns
    [OK]     driver.amd64-linux
    [OK]     virtualization VT-X
    [OK]     app
    [OK]     moby
    [OK]     system
    [OK]     moby-syslog
    [OK]     db
    [OK]     env
    [OK]     virtualization kern.hv_support
    [OK]     slirp
    [OK]     osxfs
    [OK]     moby-console
    [OK]     logs
    [OK]     docker-cli
    [OK]     menubar
    [OK]     disk

### Steps to reproduce the behavior

  1. In a terminal: docker exec -it some_app_webhost_1 /bin/bash -l

**Comment by dernotte** [comment]
Same for me. I have this problem since the last update 17.06.0-rc1-ce-mac13. Yesterday, with the same docker image, I was able to login with 'docker exec -ti' without any problem. It is not an issue with the image.

**Comment by kinghuang** [comment]
This issue is covered in #1671 and #1672.

**Comment by tobi-richard-mitchell** [comment]
fixed in this mornings update Version 17.06.0-rc2-ce-mac14 (18280)
thanks.

**Comment by sampeka** [comment]
Still experiencing this issue with `Docker 17.06.0-rc2-ce-mac14`

**Comment by gtardif** [comment]
@sampeka Yes, there is still a remaining issue specific to compose, that should be addressed shortly. #1672 keeps track of this
