### ISSUE TITLE
docker for mac after upgrade can't start .

### ISSUE THREAD

**Issue by airforce-captain** [docker/for-mac#2116]
my Machine :    MacOS 10.12.6
docker ver: latest edge
my Diagnostic ID :    DD8F9E2-418D-4726-9F00-DE6C68876A7C

```
Docker for Mac: version: 17.09.0-ce-mac31 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/1DD8F9E2-418D-4726-9F00-DE6C68876A7C/20171003-092854.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/youngman/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/youngman/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/youngman/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/youngman/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/youngman/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
```

**Comment by airforce-captain** [comment]
and I return to install  docker ce for mac (stable) version， unfortunately, still not work.

OS:  MacOS 10.12.6
docker ver:   latest stable
Diagnostic ID:   1DD8F9E2-418D-4726-9F00-DE6C68876A7C

```
Docker for Mac: version: 17.09.0-ce-mac32 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/1DD8F9E2-418D-4726-9F00-DE6C68876A7C/20171003-100134.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/youngman/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/youngman/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/youngman/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/youngman/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/youngman/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
```

**Comment by nodesocket** [comment]
Related: https://github.com/docker/for-mac/issues/2117 as well.

**Comment by mmynsted** [comment]
Yes, same issue for me.

**Comment by gtardif** [comment]
This should be fixed with the latest version (17.09.0-ce-mac34 on edge channel, mac35 on stable channel)

**Comment by MincheolC** [comment]
How can i download 17.09.0-ce-mac34? 
Edge from https://docs.docker.com/docker-for-mac/install/#download-docker-for-mac still get same issue.
