### ISSUE TITLE
php+xdebug connection closes unexpectedly 

### ISSUE THREAD

**Issue by tbfisher** [docker/for-mac#2421]
### Expected behavior

debug session stays open

### Actual behavior

debug session opens as expected, after 30-150 seconds session disconnects and process completes

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu 436160D8-2EA4-44B9-8363-A9D82B22F2DE

### Steps to reproduce the behavior

  1. docker for mac 17.12.0 stable/edge, downgrading to 17.09 fixes
  2. https://hub.docker.com/_/php/ with xdebug
  3. configure xdebug using `remote_host=docker.for.mac.localhost`
  4. initiate debugging session, stop at breakpoint
  5. wait 30-150 seconds for session to close and php process to complete

**Comment by smk** [comment]
Fixed in mac49.

**Comment by tbfisher** [comment]
I'm still seeing the issue after 5 minutes of inactivity but, but interaction with the debugger seems to reset that. Much more usable now, thanks.

**Comment by rhift** [comment]
@smk - I still encounter the same behavior in `Version 17.12.0-ce-mac49 (21995)`.

**Comment by rhift** [comment]
fwiw this solves it by setting an arbitrary timeout:

https://github.com/docker/for-mac/issues/2197#issuecomment-359866362
https://github.com/docker/for-mac/issues/2197#issuecomment-369944559

**Comment by jrgilman** [comment]
> fwiw this solves it by setting an arbitrary timeout:
> 
> [#2197 (comment)](https://github.com/docker/for-mac/issues/2197#issuecomment-359866362)
> [#2197 (comment)](https://github.com/docker/for-mac/issues/2197#issuecomment-369944559)

Thanks a ton, been searching for hours and this solved this problem for me.
