### ISSUE TITLE
Docker does not open on Mac

### ISSUE THREAD

**Issue by cyriltw** [docker/for-mac#2683]
### Expected behavior
Open Docker
### Actual behavior
Launches on Start up and gives a Fatal Error: com.docker.supervisor failed to start. Exit code 1 
### Information
Diagnostic ID: FC9F3970-DE4E-4C0F-A889-D807996A3781
```
Docker for Mac: version: 17.12.0-ce-mac55 (18467c0ae7afb7a736e304f991ccc1a61d67a4ab)
macOS: version 10.11.6 (build: 15G19009)
logs: /tmp/FC9F3970-DE4E-4C0F-A889-D807996A3781/20180309-182901.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/cyril/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/cyril/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     app
[OK]     virtualization VT-X
[ERROR]  moby
         /Users/cyril/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     moby-console
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/cyril/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk
```
### Steps to reproduce the behavior

  1. Open Docker on Mac

**Comment by cyriltw** [comment]
Fixed this with a reboot of the Mac

**Comment by tjamet** [comment]
I had quite the same behaviour with this popup:
![screen shot 2018-03-12 at 08 52 39](https://user-images.githubusercontent.com/6061440/37271809-bec968d0-25d4-11e8-8233-38c13ce770eb.png)

Diagnose ID: 8A8F9D98-E405-4AB4-ABF8-B52AB26DBD61
```
Docker for Mac: version: 18.03.0-ce-rc1-mac54 (e22e653363ad9e0f458ab38d464ab106d30a72b2)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/8A8F9D98-E405-4AB4-ABF8-B52AB26DBD61/20180312-085436.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/thibault.jamet/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/thibault.jamet/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/thibault.jamet/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk
```

This happened after my mac was switched of as it ran out of battery while docker was running

**Comment by tjamet** [comment]
For me restarting the mac host did not solve the problem, I had to go through the reset to factory settings process.
When the problem was occurring, I tried to get the logs with `syslog -k Sender Docker` but the output was empty.

**Comment by akimd** [comment]
Hi @tjamet.  Depending on your version of macOS, the `-k Sender` thing is likely to no longer work.  Please supply Diagnostics from the Docker menu.

**Comment by chrisid** [comment]
I've been having this issue since November, no new released has fixed it.
I have to run Diagnostic, exit and do it again 5 to 10 times until Docker finally starts. It's painful and time-consuming but it's the only way it works for me.

**Comment by cyriltw** [comment]
@chrisid I'm trying your method now. Sign its a pain to keep resetting and setting up the whole environment again.

**Comment by akimd** [comment]
@tjamet Do you still have the problem?  Or is it fixed for good?
Your logs included
```
2018-03-12 08:53:21.717366+0100  localhost com.docker.driver.amd64-linux[2740]: One goroutine failed: Failed to start Docker daemon
2018-03-12 08:53:21.720078+0100  localhost com.docker.supervisor[2737]: cannot read stdout from com.docker.driver.amd64-linux: EOF
2018-03-12 08:53:21.720090+0100  localhost Docker[2712]: [Docker:] DockerState: failed to start
2018-03-12 08:53:21.720120+0100  localhost Docker[2712]: [Docker:] DockerState: diagnose:
main.newDaemonCommand.func1(0xc420096480, 0xc420154540, 0x0, 0x7, 0x0, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:29 +0x5d
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc420096480, 0xc420010090, 0x7, 0x7, 0xc420096480, 0xc420010090)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x44f
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420096480, 0x21929c0, 0x2417501, 0xc4203cebc0)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x310
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420096480, 0xc4203cebc0, 0x190e700)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2d
main.main()
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:105 +0xe3
2018-03-12 08:53:21.720189+0100  localhost Docker[2712]: [Docker:] Terminator: Failed to start Docker daemon
```
which requires more investigation.


@cyriltw I understand the feeling...

**Comment by akimd** [comment]
@cyriltw I understand the feeling...

**Comment by ankittare** [comment]
Seeing the same issue, I tried restarting and reinstalling but didn't solve the problem. Unfortunately I am not able to run diagnostic as well. Using mac OS High Sierra V 10.13.3

`Failure: diagnostic: response is not valid JSON
You can also run diagnostics manually :
$ /Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u
`

**Comment by akimd** [comment]
Please run the tool (`/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u) and report the UID here. TIA!

**Comment by kassner** [comment]
I have the same problem when running Docker for Mac in 2 different users in the same Mac. If I start Docker in one user while the other one already has it running, I get the "reset to factory defaults" message. If I just close Docker without choosing, close Docker in the other user and try again, it works fine.

**Comment by akimd** [comment]
Docker for Mac does not work for several users on the same machine.  Known "problem", but so far there is not enough demand for us to fix this.  However, the latest stable should improve the situation a bit.

**Comment by akimd** [comment]
I really need diagnostics if you want us to dig into this.  Please, update to the latest Edge or Stable, diagnostics of older versions will not be considered.

**Comment by tjamet** [comment]
Hi @akimd I did not have the issue again after the factory reset, I will comment if I see the same problem again

**Comment by akimd** [comment]
So I'll close this issue.  Feel free to open a new one if you face the problem again.

**Comment by hashh420** [comment]
I have issues with the docker as well, as it is not opening at all.
is there any idea or help

**Comment by sandropoluan** [comment]
Just installed and when trying to open it...
<img width="888" alt="Screen Shot 2019-10-06 at 17 02 54" src="https://user-images.githubusercontent.com/11922251/66267458-2c098480-e85b-11e9-8de5-bbf5aab6ab19.png">

**Comment by RuedigerMoeller** [comment]
same here, run once, but cannot reopen
![image](https://user-images.githubusercontent.com/6097932/84891666-83bfe700-b09c-11ea-9d29-6bc70475c458.png)
