### ISSUE TITLE
qcow is always corrupt

### ISSUE THREAD

**Issue by spara** [docker/for-mac#301]
### Steps to reproduce

1. Restart docker
2. Run diagnose

### Expected behavior

qcow2 should not be corrupt after a restart

### Actual behavior

diagnose tells me qcow2 is corrupt again and again and again

### Information

```
Diagnostic ID: D2ED5516-63F2-4DE5-A702-BC3741B50B5C
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     dns
[OK]     moby-syslog
[OK]     app
[ERROR]  disk
         Docker.qcow2 is corrupt: reset to factory defaults is required
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dsheets** [comment]
I believe running `Reset to Factory Defaults` should fix this issue.

**Comment by MagnusS** [comment]
This error may also be reported incorrectly in beta22 - this should be fixed in beta23 which was released today.

**Comment by spara** [comment]
Installed beta 23 and the issue remains 

D2ED5516-63F2-4DE5-A702-BC3741B50B5C
Version 1.12.1-rc1-beta23 (build: 11375)
2f0427ac7d4d47c705934ae141c3a248ed7fff40

```
Docker for Mac: version: 2f0427a
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/D2ED5516-63F2-4DE5-A702-BC3741B50B5C/20160817-150953.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by samoht** [comment]
Do you still have the issue? Please re-open the issue if that's the case. We pushed few improvement to the diagnostic tool and to our qcow2 support in the latest Betas.

**Comment by ShurikAg** [comment]
I have this issue. And I lost all of my containers. Is there any way to restore them?
