### ISSUE TITLE
docker beta on mac sierra not working

### ISSUE THREAD

**Issue by bedginton** [docker/for-mac#348]
### Expected behavior
use docker on mac

### Actual behavior
docker keeps reporting ' Cannot connect to docker daemon. Is the docker daemon running on this host?'

### Information
I created a symbolic link ln -sf ~/Library/Containers/com.docker.docker/Data/s60 /var/run/docker.sock.
I can now connect to the docker daemon but I received this diagnostic for the first 'docker ps'

Diagnostic ID: 445067BE-FB45-454C-A568-496EC96E4E81
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A294a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
There was a major issue with golang and macOS Sierra Beta that was tracked by #64 and has now been resolved in Beta 23. We know of other issues with Docker for Mac on Sierra Beta so after installing the beta or installing 1.12.1 stable in a few weeks, please report any more issues you find. Thanks!

**Comment by GiorgioG** [comment]
Installed Beta 24 on Sierra Beta 7 still having the same issue.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
