### ISSUE TITLE
Very slow network performance (host to container)

### ISSUE THREAD

**Issue by AlexC** [docker/for-mac#3497]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 50BBDCC5-2FBD-4D18-A327-8B27D9C5F70E/20190130153518

### Expected behavior
HTTP calls to docker container should respond quickly

### Actual behavior
HTTP calls are very slow to respond. Compared to my Ubuntu 16.04 host whereby I get the `ab` command to complete in ~1 second, the Mac OSX host is taking ~17 seconds to complete.

### Information
 - macOS Version: 10.13.4 (High Sierra)
 - Docker for Mac: 2.0.0.2 (30215) (Engine 18.09.1)

### Diagnostic logs
```
Diagnose succeeded 
```

### Steps to reproduce the behavior
```
$ cat foo.php
<?php echo 'bar'; ?>
$ cat Dockerfile
FROM php:7.2-apache
COPY foo.php /var/www/html/
$ docker build --file Dockerfile -t slow-container .
$ docker run --rm -d -p 80:80 slow-container
$ ab -n5000 -c5 http://127.0.0.1/foo.php
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 500 requests
Completed 1000 requests
Completed 1500 requests
Completed 2000 requests
Completed 2500 requests
Completed 3000 requests
Completed 3500 requests
Completed 4000 requests
Completed 4500 requests
Completed 5000 requests
Finished 5000 requests


Server Software:        Apache/2.4.25
Server Hostname:        127.0.0.1
Server Port:            80

Document Path:          /foo.php
Document Length:        3 bytes

Concurrency Level:      5
Time taken for tests:   17.705 seconds
Complete requests:      5000
Failed requests:        0
Total transferred:      975000 bytes
HTML transferred:       15000 bytes
Requests per second:    282.41 [#/sec] (mean)
Time per request:       17.705 [ms] (mean)
Time per request:       3.541 [ms] (mean, across all concurrent requests)
Transfer rate:          53.78 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        1    5   3.5      4      46
Processing:     2   10   4.5     10      69
Waiting:        1    8   4.1      7      58
Total:          4   15   5.1     15      71

Percentage of the requests served within a certain time (ms)
  50%     15
  66%     16
  75%     17
  80%     17
  90%     19
  95%     21
  98%     26
  99%     43
 100%     71 (longest request)
```

**Comment by kazak1377** [comment]
Same here Docker desktop Version 2.0.0.3 (31259)
Engine: 18.09.2
Compose: 1.23.2
Machine: 0.16.1

**Comment by AlexC** [comment]
Does anybody know of any further information that I can get to help debug this?

**Comment by AlexC** [comment]
We've been able to try on a few more Macbooks all with similar result on most. The only thing that connects them is that they are all a corporate Macbook that has been tweaked slightly, though some of them work OK and the test completes in around 3.5 seconds.

One thing we have noticed is that if you run the tests shorty after each other then performance gets slower and slower. e.g. run the test and it takes 3.5 seconds, wait 5 seconds before trying and it will take 6-7 seconds, wait 5 seconds again then it'll take 12 seconds. If you then give it some time to rest, it'll be back at 3.5 seconds

**Comment by UniBen** [comment]
Docker version 19.03.0-rc2, build f97efcc
docker-compose version 1.24.0, build 0aa59064

I ran this command inside an ubuntu container:
```
curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
```

From within the container i got about 120mbps

When I run on the host i get about 500mbps. Why is the container so much slower? I am using an external network but didn't think it would have that much of a hit.

**Comment by fourgates** [comment]
I have experienced the same issue.

Diagnosis ID: 54A0E2A5-DFEA-4380-8AAC-AABF6C10E66B/20200124232052

I use Docker on my work PC with no issues. I recently started developing on an iMac at home and it takes significantly longer to serve up the same main.js file. No issues when working on the PC. Same code, same images/containers, and I think my iMac actually has a much more powerful processor and more RAM.

**Comment by UniBen** [comment]
> I have experienced the same issue.
> 
> Diagnosis ID: 54A0E2A5-DFEA-4380-8AAC-AABF6C10E66B/20200124232052
> 
> I use Docker on my work PC with no issues. I recently started developing on an iMac at home and it takes significantly longer to serve up the same main.js file. No issues when working on the PC. Same code, same images/containers, and I think my iMac actually has a much more powerful processor and more RAM.

Very much a known separate issue.

**Comment by wader** [comment]
I can reproduce this with:

Dockerfile
```Dockerfile
FROM golang:1.13
COPY main.go .
ENTRYPOINT ["go", "run", "main.go"]
```

main.go
```go
package main

import (
	"io"
	"net/http"
)

func main() {
	http.ListenAndServe(":8080", http.HandlerFunc(func (w http.ResponseWriter, r *http.Request) {
		io.Copy(w, r.Body)
	}))
}
```

```sh
$ docker build -t dockerformacslow .
$ docker run --rm -ti -p 8080:8080 dockerformacslow 
```

From host
```sh
$ dd if=/dev/zero bs=1000000 count=100 | curl --data-binary @- 0:8080 | dd bs=1000000 of=/dev/null
100+0 records in
100+0 records out
100000000 bytes transferred in 0.072270 secs (1383701612 bytes/sec)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  190M    0 95.3M  100 95.3M  15.0M  15.0M  0:00:06  0:00:06 --:--:-- 15.0M
0+5975 records in
0+5975 records out
100000000 bytes transferred in 6.401760 secs (15620704 bytes/sec)
```

From inside container:
```sh
root@1b0f3c04b6f8:/go# dd if=/dev/zero bs=1000000 count=100 | curl --data-binary @- 0:8080 | dd bs=1000000 of=/dev/null
100+0 records in
100+0 records out
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100000000 bytes (100 MB, 95 MiB) copied, 0.330937 s, 302 MB/s
100  190M    0 95.3M  100 95.3M   262M   262M --:--:-- --:--:-- --:--:--  525M
0+1726 records in
0+1726 records out
100000000 bytes (100 MB, 95 MiB) copied, 0.71619 s, 140 MB/s
```

**Comment by Cospel** [comment]
The same issue here, I need to install the older 2.1.0.1 version docker for-mac.

**Comment by davisengeler** [comment]
I'm having this issue. Services running inside Docker containers on macOS have very slow network speeds. This happens when running on two different MBPs.

**Comment by cherryred5959** [comment]
I removed the volume from my docker-compose, and tried [Mutagen](https://mutagen.io/).  
Then my slow network improved.  
I've read that Docker volume is slow on a Mac, but I don't know what it has to do with the network.

However, separate docker-compose file and Mutagen script should be written in development environment.
I look forward to coding more happily on the Mac...

**Comment by soccer99** [comment]
All the requests to my container have about 14 seconds of latency added just in the network request.

**Comment by slowr** [comment]
> I can reproduce this with docker for mac 2.2.0.0 (42247)
> 
> main.go
> 
> ```go
> package main
> 
> import (
> 	"io"
> 	"net/http"
> )
> 
> func main() {
> 	http.ListenAndServe(":8080", http.HandlerFunc(func (w http.ResponseWriter, r *http.Request) {
> 		io.Copy(w, r.Body)
> 	}))
> }
> ```
> 
> ```shell
> $ docker run --rm -ti -v $PWD:$PWD -w $PWD -p 8080:8080 golang:1.13 go run main.go
> ```
> 
> From host
> 
> ```shell
> $ dd if=/dev/zero bs=1000000 count=100 | curl --data-binary @- 0:8080 | dd bs=1000000 of=/dev/null
> 100+0 records in
> 100+0 records out
> 100000000 bytes transferred in 0.072270 secs (1383701612 bytes/sec)
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  190M    0 95.3M  100 95.3M  15.0M  15.0M  0:00:06  0:00:06 --:--:-- 15.0M
> 0+5975 records in
> 0+5975 records out
> 100000000 bytes transferred in 6.401760 secs (15620704 bytes/sec)
> ```
> 
> From inside container:
> 
> ```shell
> root@1b0f3c04b6f8:/go# dd if=/dev/zero bs=1000000 count=100 | curl --data-binary @- 0:8080 | dd bs=1000000 of=/dev/null
> 100+0 records in
> 100+0 records out
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100000000 bytes (100 MB, 95 MiB) copied, 0.330937 s, 302 MB/s
> 100  190M    0 95.3M  100 95.3M   262M   262M --:--:-- --:--:-- --:--:--  525M
> 0+1726 records in
> 0+1726 records out
> 100000000 bytes (100 MB, 95 MiB) copied, 0.71619 s, 140 MB/s
> ```

Still reproducible on 2.2.0.5 release. It seems that every connection going to the container through the port forward makes it 10-20 times slower.

**Comment by davisengeler** [comment]
I ran into another issue with Docker for Mac and I'm curious if it may be related to what we're seeing here. If not, sorry to muddy up the conversation. 

The open issue https://github.com/docker/for-mac/issues/180 made me realize that Docker for Mac in particular has some pretty weird behavior related to networking (I *think* due to hyperkit). Docker's [documentation about this](https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds) is pretty lacking, but there are [some other writeups](https://dimitraz.github.io/blog/post/docker-networking/) that may be worth checking into. To me, this all kinda seems like a bug related to the virtualization happening on the macOS version. 

But this is probably not news to any of you hahah.

**Comment by paales** [comment]
We've been analyzing network latency for our docker development box we've been trying to create:

Benchmarks with Docker latest:
https://github.com/ho-nl/docker-development-box/issues/10#issuecomment-638677595

- Mac to Docker: 0.976s
- Docker local TCP: real	0.281s
- Docker local Socket:: 0.147s
- Dedicated Server comparison TCP: 0.085s
- Dedicated Server comparison Socket: 0.046s

- From Mac to Docker takes 3x as much time as locally on the Docker box.
- TCP takes about twice as long as connecting over Socket.
- Docker is about 3x as slow as dedicated hardware.
- Dedicated socket is 18x faster than Mac to Docker TCP

Benchmarks with Docker 2.1.0.1:
https://github.com/ho-nl/docker-development-box/issues/10#issuecomment-639384629

- Mac to Docker: 0.4s

If we subtract the local TCP (0.281) from the 0.4 we get about 0,1ms of latency, which seems acceptable. (We still need to figure out why mysql is responding so much slower compared to a dedicated server, but that's another discussion.)

It seems there is a huge network latency overhead when running with the latest docker version which wasn't there when running the older docker version.

**Comment by dylan-chong** [comment]
Have done some debugging, and in our set up using Elixir/Phoenix API, the network delay of roughly 15 seconds isn't caused by Docker network itself. It is caused by Phoenix  checking for files changed ( Presumably source files and dependencies) when it receives a network request `plug(Phoenix.CodeReloader)`.  disabling this avoids the problem -  indicating that it is the problem with Docker file system.

**Comment by pdefreitas** [comment]
I can confirm that downgrading to Docker 2.1.0.1 increases substancially the performance in my use case (Wordpress). I've noticied the decrease of performance after upgrading my Docker setup to the latest release even through I'm using docker-sync due to the poor performance of volume mapping in Docker for Mac.

**Comment by ethan92429** [comment]
> I can confirm that downgrading to Docker 2.1.0.1 increases substancially the performance in my use case (Wordpress). I've noticied the decrease of performance after upgrading my Docker setup to the latest release even through I'm using docker-sync due to the poor performance of volume mapping in Docker for Mac.

This did not change performance for me at all. I am still seeing extremely slow performance on 2.1.0.1

**Comment by reduardo7** [comment]
???????

**Comment by 4np** [comment]
I'm seeing the docker container being able to use just about 1/5th of the total available network throughput using `SABnzbd+` inside a docker container.

**Comment by kevinhq** [comment]
Run through this problem too. Killing/restaring docker desktop works. But, it's too much hurdle.

**Comment by jbarop** [comment]
Downloading Debian packages with modem speeds... Pure nostalgia

**Comment by pwais** [comment]
I am seeing a similar issue but for local disk access.  Writes to the in-container filesystem can achieve well over 100MBytes / sec while writes to the same physical disk but using the volume-mounted `host_mnt` directory can only get about 50MBytes / sec.  This is on a new 2020 iMac with Apple NVMe SSD.  I see a similar cap using a Thunderbolt external drive that is also volume-mounted into the container.

While this Github Issue focuses on networking, I hypothesize that the hyperkit hypervisor is interfering with *any* I/O.

**Comment by shaunhp** [comment]
Same issue here.  Host write performance to my NAS is around 770Mb/s.  Write performance to same target from docker on that host is 230Mb/s.  Not fun when you're pushing 70GB files. (Mac Mini/Catalina)

**Comment by joshspicer** [comment]
+1 to this, although i'm seeing it from container -> internet.

Consistently spinning up a container in a docker-compose scenario with no custom networking config

```
root@6cc6a923ef59:/# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=4 ttl=37 time=1920 ms <-----
64 bytes from 1.1.1.1: icmp_seq=5 ttl=37 time=880 ms
64 bytes from 1.1.1.1: icmp_seq=6 ttl=37 time=11.3 ms
64 bytes from 1.1.1.1: icmp_seq=7 ttl=37 time=13.5 ms
```

**Comment by gonzofish** [comment]
> While this Github Issue focuses on networking, I hypothesize that the hyperkit hypervisor is interfering with any I/O.

Me too @pwais. I have a MongoDB container that, on >= v3.2.0 complains with `serverStatus was very slow`. If I downgrade to 3.1.0, there's no error, though.

**Comment by artheus** [comment]
This is a problem for me, as well. Though, I am running the Docker VM through `docker-machine` and `virtualbox`. So I do not think that this is a problem tied only to `docker/for-mac`.

**Comment by dylan-chong** [comment]
If you are sharing the folder between host and VM then FS performance will probably not  be fast. See if things improve if you don’t use shared folders

**Comment by tomav** [comment]
[Same issue here running speedtest.](https://github.com/frdmn/docker-speedtest-grafana/issues/3)

**Comment by tomav** [comment]
https://github.com/docker/for-mac/issues/3497

**Comment by blwsh** [comment]
The problem seems to have been resolved (for me at least)

From the host:

```
Retrieving speedtest.net configuration...
Testing download speed................................................................................
Download: 274.02 Mbit/s
Testing upload speed................................................................................................
Upload: 36.29 Mbit/s
```

and from the container (My internet fluctuates):

```
Retrieving speedtest.net configuration...
Testing download speed................................................................................
Download: 318.35 Mbit/s
Testing upload speed......................................................................................................
Upload: 39.14 Mbit/s
```

**Comment by tomav** [comment]
Using @blwsh commands, from the host:

```
Testing download speed................................................................................
Download: 888.99 Mbit/s
Testing upload speed................................................................................................
Upload: 366.19 Mbit/s
```

From Docker for Mac 3.6.0:
```
Testing download speed................................................................................
Download: 548.20 Mbit/s
Testing upload speed......................................................................................................
Upload: 156.35 Mbit/s
```

From Docker for Mac 4.1.0:
```
Testing download speed................................................................................
Download: 521.60 Mbit/s
Testing upload speed......................................................................................................
Upload: 170.52 Mbit/s
```

Still have a gap here compared to host.
Both Docker versions have similar results.

**Comment by zfil** [comment]
From the host
Download: 912.78 Mbit/s
Upload: 391.63 Mbit/s

From docker for mac 4.5.0
Download: 475.84 Mbit/s
Upload: 355.90 Mbit/s

**Comment by tomav** [comment]
From the host (OSX)
```
Testing download speed................................................................................
Download: 739.55 Mbit/s
Testing upload speed................................................................................................
Upload: 292.14 Mbit/s
```

Docker Desktop 4.6.0 (75818)

```
Testing download speed................................................................................
Download: 523.70 Mbit/s
Testing upload speed......................................................................................................
Upload: 302.98 Mbit/s
```

Still a significant difference on download (tried multiple times).

**Comment by hyzyla** [comment]
Apple Macbook M1 2022:


From the host:
```
Hosted by Techgroup Jakub Osuch (Warszawa) [2.12 km]: 7.73 ms
Testing download speed................................................................................
Download: 186.38 Mbit/s
Testing upload speed......................................................................................................
Upload: 16.23 Mbit/s
```

Docker Desktop 4.6.1 (76265)
```
Hosted by Techgroup Jakub Osuch (Warszawa) [2.12 km]: 2512.785 ms
Testing download speed................................................................................
Download: 2.35 Mbit/s
Testing upload speed......................................................................................................
Upload: 2.80 Mbit/s
```

**Comment by Giuseppetm** [comment]
This is still an issue ..

**Comment by nothing2obvi** [comment]
On Mac Mini with M1 chip, Docker Desktop 4.17.0:

From the host:
`Testing download speed................................................................................
Download: 442.37 Mbit/s
Testing upload speed.....................................................................................................
.Upload: 32.35 Mbit/s`

From Docker container:
`Testing download speed................................................................................
Download: 55.03 Mbit/s
Testing upload speed......................................................................................................
Upload: 15.97 Mbit/s`

**Comment by nothing2obvi** [comment]
Can confirm that completely quitting Docker Desktop and re-opening it does bring some improvement, but still not perfect. I tried turning off Virtualization Framework, too, and it was much worse.

On Mac Mini with M1 chip, Ventura 13.2.1, Docker Desktop 4.17.0

**With Virtualization Framework**

From the host:
```
Testing download speed................................................................................
Download: 609.29 Mbit/s
Testing upload speed......................................................................................................
Upload: 41.24 Mbit/s
```

From Docker container:
```
Testing download speed................................................................................
Download: 149.31 Mbit/s
Testing upload speed......................................................................................................
Upload: 41.50 Mbit/s
```

**Without Virtualization Framework**

From Docker container:
```
Testing download speed................................................................................
Download: 32.08 Mbit/s
Testing upload speed......................................................................................................
Upload: 32.95 Mbit/s
```

**Comment by nothing2obvi** [comment]
Upgraded to 4.18.0 and my speeds have increased dramatically. I'm happy with this.

From the host:
```
Testing download speed................................................................................
Download: 653.12 Mbit/s
Testing upload speed......................................................................................................
Upload: 29.14 Mbit/s
```

From Docker container:
```
Testing download speed................................................................................
Download: 561.10 Mbit/s
Testing upload speed......................................................................................................
Upload: 40.34 Mbit/s
```

**Comment by nothing2obvi** [comment]
Upgraded to 4.19.0 a few weeks ago and this issue has pretty much resolved for me.
