### ISSUE TITLE
Cannot unset Preference "Securely store Docker logins in MacOs keychain".  Upgrades from previous version fail docker login if preference unset.

### ISSUE THREAD

**Issue by imkarrer** [docker/for-mac#3774]
- [x] I have tried with the latest version of my channel `2.1.0.0` (Stable or Edge)
  - [ ] I have uploaded Diagnostics How do I upload diagnostics?
  - Diagnostics ID:

### Expected behavior

The "Securely store docker logins in macOS keychain" preference can be disabled.

### Actual behavior

The "Securely store docker logins in macOS keychain" preference cannot be disabled.
### Information

  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes, if the option is disabled before update, docker logins fail with `error storing credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out:`
  - macOS Version: 10.14.5 (18F132)

### Diagnostic logs

```
Docker for Mac: version...

```
Not sure how to obtain these

### Steps to reproduce the behavior

  1. Install docker for mac 2.1.0.0
  2. Attempt to unset the Preference "Securely store docker logins in macOS keychain"

or
  1. Upgrade to 2.1.0.0 with the Preference unchecked
  2. Attempt docker login
  3. See `Error saving credentials: error storing credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out:`

**Comment by Cselt** [comment]
As a temporary workaround  edit and remove _desktop_ from _credStore_ config in `~/.docker/config.json`.

```
"credStore": ""
```
This way docker will store your credentials in config.json as before.

**Comment by NyanHorse** [comment]
> As a temporary workaround edit and remove _desktop_ from _credStore_ config in `~/.docker/config.json`.
> 
> ```
> "credStore": ""
> ```
> 
> This way docker will store your credentials in config.json as before.

Doesn't work for me :(
After restarting Docker, it creates a new "credsStore":"desktop"
```{"HttpHeaders":{"User-Agent":"Docker-Client/18.09.2 (darwin)"},"auths":{"docker.intenthq.com":{"auth":"YWNjZXNzOnNwNkRVOHNGcnFjVHg3UVY2QXhLRTllaVJDQk1rWg=="}},"credSstore":"","credsStore":"desktop","stackOrchestrator":"swarm"}```

**Comment by markverg** [comment]
> > As a temporary workaround edit and remove _desktop_ from _credStore_ config in `~/.docker/config.json`.
> > ```
> > "credStore": ""
> > ```
> > 
> > 
> > This way docker will store your credentials in config.json as before.
> 
> Doesn't work for me :(
> After restarting Docker, it creates a new "credsStore":"desktop"

same here :(

**Comment by Cselt** [comment]
If take a close look of your config then you will notice you have `"credSstore":""` and `"credsStore":"desktop"` as well.

Try to remove `"credsStore":"desktop"`. I think you don't need to restart docker. 
After restarting docker you may need to edit config again to remove _desktop_.

**Comment by imkarrer** [comment]
The config is a generated file, right?  Even if it persists on restart, if your organization does credential rotation you will have to google the error and then find this thread again.  Rolling back to `2.0.0.0` seems like the only reasonable option until a fix is rolled out in a future release.

**Comment by Cselt** [comment]
That's right, you need to edit the config file manually every time you log in to docker hub. 
That's why my solution is a temporary one.

**Comment by guillaumerose** [comment]
Thanks for report! This is fixed in the stable we released right now.
You can click "Check for updates" or take this link: https://download.docker.com/mac/stable/37199/Docker.dmg

**Comment by guillaumerose** [comment]
Edge channel will be updated today or Monday.

**Comment by dhoffman34** [comment]
@guillaumerose, I tried out https://download.docker.com/mac/stable/37199/Docker.dmg, but I still got the same issue.

Updating `~/.docker/config.json` to remove the `credStore` entry worked, though.

**Comment by rhass** [comment]
The 2.1.0.4 release seems to be very touchy about attempting to change this. `docker login` causes the `credStore` setting to come back when it is removed from the `config.json` file and the option is unchecked.

**Comment by maxbates** [comment]
N of 1, but simply removing the `"credsStore"` line didn't work, presumably because it produces invalid JSON. Also removing the preceding comma allowed the change to persist.

**Comment by icaromagalhaes** [comment]
I just faced this issue. The solution was to check the option "Include VM in Time Machine backups" and the "Secure store Docker logins in macOS keychain" option became available. My docker version is 2.2.0.0 (42247)

**Comment by mcpate** [comment]
> I just faced this issue. The solution was to check the option "Include VM in Time Machine backups" and the "Secure store Docker logins in macOS keychain" option became available. My docker version is 2.2.0.0 (42247)

I'm on 2.2.0.3 and this was my fix too.

**Comment by BananaWanted** [comment]
> I just faced this issue. The solution was to check the option "Include VM in Time Machine backups" and the "Secure store Docker logins in macOS keychain" option became available. My docker version is 2.2.0.0 (42247)

It really works! Although the solution looks weird. I can even turn back turn off the Time Machine settings after turned off the keychain store.

**Comment by adamski52** [comment]
Can confirm:  clicking "include VM in Time Machine" backup enables the "Securely store Docker logins" checkbox, which lets you unset it, which then let me use the AWS CLI to login to ECR.

**Comment by lastyearproject87** [comment]
got the same error 
just logged in through the User interface instead of command line

**Comment by bsilvaedu** [comment]
> I just faced this issue. The solution was to check the option "Include VM in Time Machine backups" and the "Secure store Docker logins in macOS keychain" option became available. My docker version is 2.2.0.0 (42247)

fixed on 2.2.0.5

**Comment by mojo2012** [comment]
Damn this bug is still there in the newest version! Can you please fix this asap?

**Comment by BananaWanted** [comment]
Just tried this isn't fixed in my side, please reopen this issue

![image](https://user-images.githubusercontent.com/7879714/81698665-e5d36e00-9498-11ea-803a-af161d185305.png)

**Comment by imkarrer** [comment]
This issue is almost a year old folks. They reacted quite positively and quickly last time (even if the issue was not resolved in full, they acted!).

I think you all would have more success if you were to fill out a new bug report and reference this one.  Your request to re-open this issue is vague and probably wont get much traction or attention.

**Comment by laukhin** [comment]
@BananaWanted just have found workaround for it
if option "Include VM in Time Machine backups" is enabled, option about keychain becomes available. Once you unset keychain option you can return first option to the initial state.

**Comment by myedibleenso** [comment]
I also feel this should be reopened.  The "solution" @BananaWanted  [described]( https://github.com/docker/for-mac/issues/3774#issuecomment-589989238) also worked for me on v2.3.0.3, but it's a hack...
