### ISSUE TITLE
Get https://kubernetes.docker.internal:6443 forbidden breaks kubernettes/kubectl

### ISSUE THREAD

**Issue by jonathanunderwood** [docker/for-mac#3829]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8AC5C556-EA39-41EE-B986-C84DDADBECDD/20190811072127

This is related to #3828 but is a distinct issue.

### Expected behavior
NginX ingress controller is installable as per instructions at https://kubernetes.github.io/ingress-nginx/deploy/

### Actual behavior
```bash
$ sudo -E kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
Password:
error when retrieving current configuration of:
Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
Name: "ingress-nginx", Namespace: ""
Object: &{map["apiVersion":"v1" "kind":"Namespace" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"] "name":"ingress-nginx"]]}
from server for: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api/v1/namespaces/ingress-nginx: Forbidden
error when retrieving current configuration of:
Resource: "/v1, Resource=configmaps", GroupVersionKind: "/v1, Kind=ConfigMap"
Name: "nginx-configuration", Namespace: "ingress-nginx"
Object: &{map["apiVersion":"v1" "kind":"ConfigMap" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"] "name":"nginx-configuration" "namespace":"ingress-nginx"]]}
from server for: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api/v1/namespaces/ingress-nginx/configmaps/nginx-configuration: Forbidden
error when retrieving current configuration of:
Resource: "/v1, Resource=configmaps", GroupVersionKind: "/v1, Kind=ConfigMap"
Name: "tcp-services", Namespace: "ingress-nginx"
Object: &{map["apiVersion":"v1" "kind":"ConfigMap" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"] "name":"tcp-services" "namespace":"ingress-nginx"]]}
from server for: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api/v1/namespaces/ingress-nginx/configmaps/tcp-services: Forbidden
error when retrieving current configuration of:
Resource: "/v1, Resource=configmaps", GroupVersionKind: "/v1, Kind=ConfigMap"
Name: "udp-services", Namespace: "ingress-nginx"
Object: &{map["apiVersion":"v1" "kind":"ConfigMap" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"] "name":"udp-services" "namespace":"ingress-nginx"]]}
from server for: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api/v1/namespaces/ingress-nginx/configmaps/udp-services: Forbidden
error when retrieving current configuration of:
Resource: "/v1, Resource=serviceaccounts", GroupVersionKind: "/v1, Kind=ServiceAccount"
Name: "nginx-ingress-serviceaccount", Namespace: "ingress-nginx"
Object: &{map["apiVersion":"v1" "kind":"ServiceAccount" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"] "name":"nginx-ingress-serviceaccount" "namespace":"ingress-nginx"]]}
from server for: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api/v1/namespaces/ingress-nginx/serviceaccounts/nginx-ingress-serviceaccount: Forbidden
error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1beta1, Resource=clusterroles", GroupVersionKind: "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRole"
Name: "nginx-ingress-clusterrole", Namespace: ""
Object: &{map["apiVersion":"rbac.authorization.k8s.io/v1beta1" "kind":"ClusterRole" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"] "name":"nginx-ingress-clusterrole"] "rules":[map["apiGroups":[""] "resources":["configmaps" "endpoints" "nodes" "pods" "secrets"] "verbs":["list" "watch"]] map["apiGroups":[""] "resources":["nodes"] "verbs":["get"]] map["apiGroups":[""] "resources":["services"] "verbs":["get" "list" "watch"]] map["apiGroups":[""] "resources":["events"] "verbs":["create" "patch"]] map["apiGroups":["extensions" "networking.k8s.io"] "resources":["ingresses"] "verbs":["get" "list" "watch"]] map["apiGroups":["extensions" "networking.k8s.io"] "resources":["ingresses/status"] "verbs":["update"]]]]}
from server for: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/apis/rbac.authorization.k8s.io/v1beta1/clusterroles/nginx-ingress-clusterrole: Forbidden
error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1beta1, Resource=roles", GroupVersionKind: "rbac.authorization.k8s.io/v1beta1, Kind=Role"
Name: "nginx-ingress-role", Namespace: "ingress-nginx"
Object: &{map["apiVersion":"rbac.authorization.k8s.io/v1beta1" "kind":"Role" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"] "name":"nginx-ingress-role" "namespace":"ingress-nginx"] "rules":[map["apiGroups":[""] "resources":["configmaps" "pods" "secrets" "namespaces"] "verbs":["get"]] map["apiGroups":[""] "resourceNames":["ingress-controller-leader-nginx"] "resources":["configmaps"] "verbs":["get" "update"]] map["apiGroups":[""] "resources":["configmaps"] "verbs":["create"]] map["apiGroups":[""] "resources":["endpoints"] "verbs":["get"]]]]}
from server for: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/apis/rbac.authorization.k8s.io/v1beta1/namespaces/ingress-nginx/roles/nginx-ingress-role: Forbidden
error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1beta1, Resource=rolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1beta1, Kind=RoleBinding"
Name: "nginx-ingress-role-nisa-binding", Namespace: "ingress-nginx"
Object: &{map["apiVersion":"rbac.authorization.k8s.io/v1beta1" "kind":"RoleBinding" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"] "name":"nginx-ingress-role-nisa-binding" "namespace":"ingress-nginx"] "roleRef":map["apiGroup":"rbac.authorization.k8s.io" "kind":"Role" "name":"nginx-ingress-role"] "subjects":[map["kind":"ServiceAccount" "name":"nginx-ingress-serviceaccount" "namespace":"ingress-nginx"]]]}
from server for: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/apis/rbac.authorization.k8s.io/v1beta1/namespaces/ingress-nginx/rolebindings/nginx-ingress-role-nisa-binding: Forbidden
error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1beta1, Resource=clusterrolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRoleBinding"
Name: "nginx-ingress-clusterrole-nisa-binding", Namespace: ""
Object: &{map["apiVersion":"rbac.authorization.k8s.io/v1beta1" "kind":"ClusterRoleBinding" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"] "name":"nginx-ingress-clusterrole-nisa-binding"] "roleRef":map["apiGroup":"rbac.authorization.k8s.io" "kind":"ClusterRole" "name":"nginx-ingress-clusterrole"] "subjects":[map["kind":"ServiceAccount" "name":"nginx-ingress-serviceaccount" "namespace":"ingress-nginx"]]]}
from server for: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/nginx-ingress-clusterrole-nisa-binding: Forbidden
error when retrieving current configuration of:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "nginx-ingress-controller", Namespace: "ingress-nginx"
Object: &{map["apiVersion":"apps/v1" "kind":"Deployment" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"] "name":"nginx-ingress-controller" "namespace":"ingress-nginx"] "spec":map["replicas":'\x01' "selector":map["matchLabels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"]] "template":map["metadata":map["annotations":map["prometheus.io/port":"10254" "prometheus.io/scrape":"true"] "labels":map["app.kubernetes.io/name":"ingress-nginx" "app.kubernetes.io/part-of":"ingress-nginx"]] "spec":map["containers":[map["args":["/nginx-ingress-controller" "--configmap=$(POD_NAMESPACE)/nginx-configuration" "--tcp-services-configmap=$(POD_NAMESPACE)/tcp-services" "--udp-services-configmap=$(POD_NAMESPACE)/udp-services" "--publish-service=$(POD_NAMESPACE)/ingress-nginx" "--annotations-prefix=nginx.ingress.kubernetes.io"] "env":[map["name":"POD_NAME" "valueFrom":map["fieldRef":map["fieldPath":"metadata.name"]]] map["name":"POD_NAMESPACE" "valueFrom":map["fieldRef":map["fieldPath":"metadata.namespace"]]]] "image":"quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.25.0" "livenessProbe":map["failureThreshold":'\x03' "httpGet":map["path":"/healthz" "port":'\u280e' "scheme":"HTTP"] "initialDelaySeconds":'\n' "periodSeconds":'\n' "successThreshold":'\x01' "timeoutSeconds":'\n'] "name":"nginx-ingress-controller" "ports":[map["containerPort":'P' "name":"http"] map["containerPort":'\u01bb' "name":"https"]] "readinessProbe":map["failureThreshold":'\x03' "httpGet":map["path":"/healthz" "port":'\u280e' "scheme":"HTTP"] "periodSeconds":'\n' "successThreshold":'\x01' "timeoutSeconds":'\n'] "securityContext":map["allowPrivilegeEscalation":%!q(bool=true) "capabilities":map["add":["NET_BIND_SERVICE"] "drop":["ALL"]] "runAsUser":'!']]] "serviceAccountName":"nginx-ingress-serviceaccount"]]]]}
from server for: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/apis/apps/v1/namespaces/ingress-nginx/deployments/nginx-ingress-controller: Forbidden
```

### Information
This worked fine for the previous version 2.0.0.3, but is broken for 2.1.0.1.

Note that I am having to run `kubectl` under sudo (as per #3828), which I didn't previously need to. Even then, the failure above is seen.

  - macOS Version: 10.14.6

### Diagnostic logs
See above.
```
Docker for Mac: 2.1.0.1

```

### Steps to reproduce the behavior
See above.

**Comment by jonathanunderwood** [comment]
Performed a "Reset to Factor defaults" on docker for mac, and now getting this:

```bash
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api?timeout=32s: Forbidden
unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api?timeout=32s: Forbidden
unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api?timeout=32s: Forbidden
unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api?timeout=32s: Forbidden
unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api?timeout=32s: Forbidden
unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api?timeout=32s: Forbidden
unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api?timeout=32s: Forbidden
unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api?timeout=32s: Forbidden
unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api?timeout=32s: Forbidden
unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml": Get https://kubernetes.docker.internal:6443/api?timeout=32s: Forbidden
```

**Comment by ralphkar** [comment]
Same here. I installed version 2.1.1.0 (37260) this morning and have the same error since.

**Comment by jonathanunderwood** [comment]
I think it's something to do with DNS breakage. I see the following in `/etc/hosts`:

```
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

But tools like `host` `nslookup` won't use that:

```
$ host kubernetes.docker.internal
Host kubernetes.docker.internal not found: 3(NXDOMAIN)
```

while `dscacheutil` will:

```
$ dscacheutil -q host -a name kubernetes.docker.internal
name: kubernetes.docker.internal
ip_address: 127.0.0.1
```

I suspect that `kubectl` has not been build with the ability to use settings in `/etc/hosts`. To check this, I replaced mentions of `kubernetes.docker.internal` in `~/.kube/config` with `127.0.0.1` and all is fine again.

So, something is wrong with how `kubectl` is being built such that DNS lookups aren't respecting `/etc/hosts` on OSX.

**Comment by wpwoodjr** [comment]
> So, something is wrong with how `kubectl` is being built such that DNS lookups aren't respecting `/etc/hosts` on OSX.

Ditto for Ubuntu under WSL.  I replaced `kubernetes.docker.internal` in `~/.kube/config` with `localhost` and all is good.

**Comment by jonathanunderwood** [comment]
Digging a bit further, it turns out that, for me adding `.docker.internal` to the `no_proxy` and `NO_PROXY` environment variables actually fixes the issue.

**Comment by jonathanunderwood** [comment]
I am going to close this, as I believe the issue is resolved.

**Comment by cdenneen** [comment]
@jonathanunderwood Still seeing issue with latest 2.2.0.0 what is the NO_PROXY fix?

**Comment by jonathanunderwood** [comment]
Not seeing any issues here.

**Comment by ChiefInnovator** [comment]
Seeing this problem with 2.3.0.2 edge build
