### ISSUE TITLE
Mounting subdirectories of symlinks into containers is not possible

### ISSUE THREAD

**Issue by Mactory** [docker/for-mac#412]
In my setup, I mount a subfolder of etc into my docker container (e.g. /etc/foo). (On OS X '/etc' is actually a symlink to "/private/etc".) I want to be able to use the same scripts on Linux and on OS X machines, so I use the /etc/foo path for mounting these folders.
The /etc folder is not shared as default with docker, so I tried adding "/etc" to the shared folders but I got a message saying, that "/etc is reserved by docker". When I try to add "/etc/foo" directly to the shared folders, it gets resolved to "/private/etc/foo".
Currently I see no possibility to mount "/etc/foo" on OS X into a docker container though it works on Linux systems.
Is there a reason for this restriction, or is it just an oversight, as adding "/etc/foo" to the shared folders should work but is broken by the system's folder selection which resolves the symlink?

Thank you for your help.

**Comment by dsheets** [comment]
Thanks for reporting this. This is an issue with the OS X directory chooser that does not allow the user to select paths with unresolved components (only the last component remains unresolved if the option to retain verbatim paths is used). We need to use a different method to select the paths to export to Docker. This issue has been tracked internally since August 16 and I have started a thread with our GUI team about getting it resolved.

Thanks for using Docker for Mac and sorry for this annoying problem.

**Comment by Mactory** [comment]
Thank you for your reply.
For now I have helped myself by adding an additional local.yml for docker-compose that overwrites /etc/foo:/etc/foo to use the resolved form /private/etc/foo:/etc/foo

**Comment by nmcalabroso** [comment]
+1 to this issue

**Comment by ebuildy** [comment]
If this can help, you can use NFS mounts instead of D4M shares, this should let you more flexibility (and speed ^^).

**Comment by nmcalabroso** [comment]
Just some update, I managed to mount directories via symlinks using `docker-compose`. This worked for me since I'm just concerned on building a local development environment rather a production one.

**Comment by dsheets** [comment]
This was fixed in Beta 33 and has been recently improved in Beta 35 or 36 so that exported directory paths are editable and now manually enterable by editing a blank entry at the end of the list.

Thanks for your patience with this issue and for using Docker for Mac. This improvement should reach the stable channel in a week or two.

**Comment by snanurag** [comment]
I am still facing this issue. Here are the set of commands for the proof.

```$ docker run -it --name devtest --mount type=bind,source=/var/lib/wercker,target=/var/lib/wercker nginx
docker: Error response from daemon: invalid mount config for type "bind": bind mount source path does not exist: /var/lib/wercker.
See 'docker run --help'. 
$ ls -l /var/lib/
total 0
drwx------  2 _postfix  wheel  64 Feb 11  2018 postfix
drwxrwxrwx  2 root      wheel  64 Aug 21 13:37 wercker
$ ls -l /var
lrwxr-xr-x@ 1 root  wheel  11 Mar 28 15:24 /var -> private/var
```
And my docker version is 
```$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true```

Why am I still facing this problem?

**Comment by pengisgood** [comment]
After I upgrade to the latest version on Mac os 10.15.3. I get `Mounts denied` error again.
<img width="760" alt="docker" src="https://user-images.githubusercontent.com/2988765/74736493-d83d8c00-528d-11ea-8e6d-fd83d87cfe83.png">

I try to mount `/var/data/test:/var/data/test` in the docker compose file. And I choose the folder in the `file sharing` menu, it turns out to be `/private/var/data/test`. 

If I try to run `docker-compose up`, always get `Mounts denied` error.

```
ERROR: for c9430ce45017_xxx-SNAPSHOT  Cannot start service xxx: Mounts denied:
The path /var/data/test
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```
