### ISSUE TITLE
Missing Whale icon in the OS X menu bar

### ISSUE THREAD

**Issue by bosko** [docker/for-mac#4947]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I expect to see whale icon in the menu bar

### Actual behavior
Whale icon in the menu bar is missing and does not appear neither after system restart nor after reinstalling Docker for Mac.

### Information
Problem appeared after installing the latest update Docker for Mac version.

  - macOS Version:
macOS Catalina 10.15.6

### Diagnostic logs
I cannot access menu because icon is missing.

```
› docker version
Client: Docker Engine - Community
 Azure integration  0.1.15
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

› docker info
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: TMYB:336V:ZOQV:RPFL:4EON:VISG:7ZQZ:ZXKX:7V6S:NP35:WG72:IOPV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 39
  Goroutines: 51
  System Time: 2020-09-26T15:06:03.993613957Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Steps to reproduce the behavior
Install latest update of Docker for Mac

**Comment by StefanScherer** [comment]
In macOS the left most icons in the menu bar tend to „disappear“ when there is no space left. On my Mac I also can‘t see all icons, depending on the app I‘m running as it occupies space for its menu items. 
I suggest to reorder the icons and have the more important ones on the right side. 
Could you share a screenshot of your menu bar?

**Comment by bosko** [comment]
Here is the screenshot of menu bar after closing Skype and Flux. So left of Google drive icon were two more icons for Skype and Flux but even after removing those two whale icon didn't appear.

<img width="1674" alt="Screenshot 2020-09-26 at 17 41 46" src="https://user-images.githubusercontent.com/49883/94344432-ad839500-001f-11eb-9681-6a04a0e23bf9.png">

**Comment by StefanScherer** [comment]
We have no other report of missing icon, and you menu bar looks good and has plenty of space.
Yesterday we have released a new Stable 2.4.0.0. I suggest to install this version to see if it's showing the icon again.

**Comment by bosko** [comment]
I have installed it and icon is still missing. However there is an improvement. With previous version (I forgot to write that in the initial description) I was not able to start GUI at all but with new version GUI is started after Command-Space "Docker".

<img width="1056" alt="Screenshot 2020-10-02 at 07 10 06" src="https://user-images.githubusercontent.com/49883/94890115-b260a280-047e-11eb-8b1b-5f1a8139acc8.png">

**Comment by byaruhaf** [comment]
my icon is also missing, I just uninstall and reinstalled it but that didn't fix the problem

**Comment by StefanScherer** [comment]
@bosko If you have the chance could you run the diagnostics and upload it? You can find it in the "bug" icon, then "Run Diagnostics", then press "Upload" it and paste the diagnostics id. Thank you.

**Comment by bosko** [comment]
@StefanScherer, of course. Here is the diagnostics ID: 61DF01BB-2759-4D75-A760-9540D5120C99/20201005065513

**Comment by bosko** [comment]
Suddenly icon appeared altogether with Dropbox and Zoom icons so I'm closing this issue because it obviously is not related to Docker for desktop but to some system related issue.
