### ISSUE TITLE
2.4.0.0 Rails doesn't pick up file changes on webpage refresh. Works in 2.3.0.5.

### ISSUE THREAD

**Issue by nitsujri** [docker/for-mac#4962]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Editing files and refreshing webpage on the Rails server should pick up changes.

### Actual behavior

Refreshing webpage with rails server with edited files does not reflect changes.

### Information

  - macOS Version: 10.15.7
  - Reproducible: Yes
  - Problem new: Yes
  - Did the problem appear with an update?
    - Yes
    - Works in 2.3.0.5, reloading webpage w/ changes stops working in 2.4.0.0

### Diagnostic logs

```
Docker for Mac: 2.4.0.0

```

### Steps to reproduce the behavior

To reproduce - Empty Rails app w/ instructions in README:

https://github.com/jenfi-eng/docker-rails-reload-issue

**Comment by Sirfrummel** [comment]
I'm dealing with this too -- except with PHP.
I just upgraded from 10.13 to 10.15.7 too, thinking it was related to 10.13 being deprecated.  I guess I'll try downgrading -

**Comment by stephen-turner** [comment]
Thanks for the report, @nitsujri. Does it fix it if you switch back from gRPC Fuse to osxfs file sharing in the settings?

**Comment by ManCodeB** [comment]
+1 I have the exact same issue with docker desktop 2.4.0 for osx and with Rails 5.2 applications

**Comment by nitsujri** [comment]
@stephen-turner ah yes that fixes it - switching off the `gRPC FUSE` makes the problem go away.

**Comment by stephen-turner** [comment]
Great, thanks, we'll investigate.

**Comment by ManCodeB** [comment]
yes, turning gRPC Fuse off also fixes it for me!

**Comment by kwerle** [comment]
I use a rails gem "guard" https://github.com/guard/guard that watches for filesystem events and runs the appropriate tests when files are saved.

2.4.0.0 broke this functionality.  It certainly looked like filesystem events were not propagating.

Turning of gRPC Fuse addressed this issue for me.
  System Version:	macOS 10.15.6 (19G2021)

**Comment by pvande** [comment]
Both the Guard and the Rails issues mentioned here track back to the Listen gem, which handles file system updates for both.  My own experience confirms that this is an issue under gRPC even with more recent versions of that library, and that it functions properly under the osxfs adapter.

**Comment by dmrty** [comment]
Got the same problem here with a Rails app when going upgrading to 2.4.0.
gPRC-Fuse not working but Osxfs works.

Activating the environment variable `LISTEN_GEM_DEBUGGING: "2"` shows that the Listen Gem do not receive any `inotify` events.

I deduce GPRC-Fuse do not emit the inotify events when ?

**Comment by stephen-turner** [comment]
It's weird that all the reports here are with Ruby. Normally if inotify is broken we get loads of PHP complaints. It looks like there might be something specific to Ruby in this case.

**Comment by pvande** [comment]
Digging in further:

Under `osxfs`, saving a file locally causes both ATTRIB and MODIFY events to fire.
Under `gRPC`, saving a file locally *only* triggers an inotify MODIFY event.
The `listen` gem [only sets up listeners for ATTRIB and FILE_CLOSE](https://github.com/guard/listen/blob/master/lib/listen/adapter/linux.rb#L85-L91) events.
The lack of MODIFY listeners has been [previously noted](https://github.com/guard/listen/issues/450) as suspicious and problematic.

**Comment by pvande** [comment]
Also worth noting:

`touch`ing a file locally under `osxfs` produces an ATTRIB event.
`touch`ing a file locally under `gRPC` produces no events.

**Comment by joshua-bn** [comment]
> It's weird that all the reports here are with Ruby. Normally if inotify is broken we get loads of PHP complaints. It looks like there might be something specific to Ruby in this case.

My team is having this issue on a PHP application.

**Comment by djs55** [comment]
@joshua-bn could you check whether this is the same issue by looking for inotify events in the container? For example
```
PS> docker run -it -v C:\Users\dave\workspace:/workspace alpine sh
/ # apk add inotify-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/1) Installing inotify-tools (3.20.2.2-r0)
Executing busybox-1.31.1-r16.trigger
OK: 6 MiB in 15 packages
/ # inotifywait -r -m /workspace/
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/workspace/ MODIFY foo.txt
/workspace/ CREATE bar.txt
/workspace/ MODIFY bar.txt
/workspace/ DELETE bar.txt
```
If the inotify events generated explains the difference between `grpcfuse` and `osxfs` then that's really useful information. If it looks like a different situation, if you could share a repro case that would be really helpful.

**Comment by joshua-bn** [comment]
Without checked:
```
Watches established.
/workspace/ CREATE foo.txt
/workspace/ MODIFY foo.txt
/workspace/ CREATE foo.txt
/workspace/ ATTRIB foo.txt
/workspace/ MODIFY foo.txt
/workspace/ CREATE bar.txt
/workspace/ DELETE foo.txt
/workspace/ CREATE bar.txt
/workspace/ DELETE bar.txt
/workspace/ CREATE bar.txt
/workspace/ CREATE foo.txt
/workspace/ MODIFY foo.txt
```

With checked:
```
/workspace/ CREATE foo.txt
/workspace/ CREATE bar.txt
/workspace/ DELETE foo.txt
/workspace/ DELETE bar.txt
/workspace/ CREATE foo.txt
/workspace/ MODIFY foo.txt
```

**Comment by NDuggan** [comment]
+1 👍 Turning off `Use gRPC FUSE for file sharing` also fixed my team's Rails application not updating.

**Comment by alechirsch** [comment]
Having the same issue with my node application, some files from volumes are not found in the container, even though they are on the host machine. Trying it with disabling gRPC FUSE.

**Comment by djs55** [comment]
A quick status update: there's a dev build (based on 2.4.0.0 stable, a pre-release version of a possible 2.4.0.1 update) https://desktop-stage.docker.com/mac/stable/48820/Docker.dmg with some filesystem fixes. This build now generates `ATTRIB` events as well as `MODIFY` when files are touched and gRPC FUSE is enabled:
```
/ # inotifywait -r -m /workspace/event
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/workspace/event/ CREATE foo
/workspace/event/ ATTRIB foo
/workspace/event/ MODIFY foo
/workspace/event/ ATTRIB foo
/workspace/event/ MODIFY foo
```
If you could try this build and let me know how it goes I would be very grateful.

If there are still problems, could you provide a repro example? If it's not possible to produce a simple repro, try reproducing the bug locally, upload some diagnostics, quote the id here and describe as much as possible about your project and I'll see if I can figure it out.

Thanks!

**Comment by pvande** [comment]
@djs55 I'll run the build in my environment for today, and see what comes up!  Thanks!

**Comment by pvande** [comment]
@djs55 First impressions are that this is working exactly as expected!

**Comment by pvande** [comment]
Having worked with the developer build for a full day, everything worked beautifully.  Thanks for getting that together for us, @djs55!

**Comment by simonferquel** [comment]
The issue has been fixed in Edge release 2.4.2.0, thank you for reporting it.

**Comment by kylepeeler** [comment]
I was still encountering this issue in the latest edge build 2.4.2.0 where none of my file changes were being picked up by Webpack HMR... had to downgrade to Docker stable to be able to develop 😢

**Comment by trip-somers** [comment]
I have been running v2.4.0.0 (48506) with gRPC Fuse unchecked for a couple of weeks after originally reading this issue, and today this problem popped back up. gRPC Fuse preference is still unchecked, but file system is not updating after the first few minutes of the container running.

**Comment by kwerle** [comment]
Bad news first:
2.5.0.0 with gPRC off fails to transmit file system events

Good news:
2.5.0.0 with gPRC on works as expected

**Comment by paranishian** [comment]
@kwerle 
I was having the same problem, and that's how I solved it! Thank you!
