### ISSUE TITLE
Alpine edge DNS issues in D4M but not on Linux host.

### ISSUE THREAD

**Issue by PhilETaylor** [docker/for-mac#5020]
### Expected behavior

Cross posting from https://gitlab.alpinelinux.org/alpine/aports/-/issues/12051

When trying to build Alpine Edge with this two line docker file, I expect it to download index.html (this is a reproducer, in real life my whole build fails on edge because wget/curl cannot resolve dns)

If I use Alpine 3.11 or Alpine 3.12 then it works in Docker 4 Mac as expected 

```
FROM alpine:3.12
RUN wget https://alpinelinux.org
# now run...     docker build --no-cache .
```

<img width="604" alt="Screenshot 2020-10-25 at 14 16 54" src="https://user-images.githubusercontent.com/400092/97109935-1f5a0780-16ce-11eb-9db5-fdfaa139d151.png">

### Actual behavior

any use of wget or curl in the docker file fails with a bad address or other dns issue when using `alpine:edge`

<img width="608" alt="Screenshot 2020-10-25 at 14 18 00" src="https://user-images.githubusercontent.com/400092/97109936-2123cb00-16ce-11eb-8bde-24f8772c08eb.png">

### Steps to reproduce the behavior

```
FROM alpine:edge
RUN wget https://alpinelinux.org
# now run...     docker build --no-cache .
```

```
docker build --no-cache .
```

<img width="608" alt="Screenshot 2020-10-25 at 14 18 00" src="https://user-images.githubusercontent.com/400092/97109936-2123cb00-16ce-11eb-8bde-24f8772c08eb.png">

**Comment by PhilETaylor** [comment]
Similar to https://gitlab.alpinelinux.org/alpine/aports/-/issues/11879 conclusion there was its a Docker For Mac issue :)

**Comment by OTLabs** [comment]
I would like to confirm this behavior on my computer:

macOS Catalina 10.15.7

Docker for Mac 2.4.0.0

You can use https://github.com for same purpose too.

**Comment by OTLabs** [comment]
Still observed on Docker for Mac 2.5.0.0

**Comment by stephen-turner** [comment]
Thanks for the report. I can confirm that I've reproduced it on Mac but not Windows. I've opened an internal ticket.

It's odd, because our intent is just to transparently pass the DNS requests through to the host's DNS server, but maybe it's not as transparent as it's meant to be. We'll figure it out.

**Comment by merzilla** [comment]
I can confirm having the same issue on Docker For Mac 2.5.0.1.
E.g. "Could not resolve host: api.github.com" or just "GitHub.com" not working when `alpine:edge` should run Composer commands.

**Comment by stephen-turner** [comment]
Thanks, we don't need any more confirmations, we've reproduced it and will fix it.

**Comment by lorenrh** [comment]
The fix for this issue has been released in Edge 2.5.4, I’ll go ahead and close the ticket now.

**Comment by stephen-turner** [comment]
If you're on the Stable channel, we're planning a release including this later this week.

**Comment by temp** [comment]
@lorenrh @stephen-turner Upgraded to 2.5.4, did a factory reset, but I'm still having problems in docker build, with buildkit.

```
#7 1.242 WARNING: Ignoring https://packages.xxx.net/apk/php80: DNS lookup error
...
#7 3.429 curl: (6) Could not resolve host: composer.github.io
```

**Comment by PhilETaylor** [comment]
I can confirm with Edge 2.5.4 the specific problem I reported seems to have been fixed. 

```
 docker build --no-cache .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine:3.12
3.12: Pulling from library/alpine
Digest: sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a
Status: Downloaded newer image for alpine:3.12
 ---> d6e46aa2470d
Step 2/2 : RUN wget https://alpinelinux.org
 ---> Running in d2baf29062c4
Connecting to alpinelinux.org (147.75.101.119:443)
saving to 'index.html'
index.html           100% |********************************|  8001  0:00:00 ETA
'index.html' saved
Removing intermediate container d2baf29062c4
 ---> 7ed531538d54
Successfully built 7ed531538d54
```

**Comment by temp** [comment]
@PhilETaylor can you try with buildkit enabled?

**Comment by PhilETaylor** [comment]
```
~/Sites/test DOCKER_BUILDKIT=1  docker build --no-cache .
[+] Building 0.4s (6/6) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                          0.0s
 => => transferring dockerfile: 92B                                                                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/alpine:3.12                                                                                                                                                                0.0s
 => CACHED [1/2] FROM docker.io/library/alpine:3.12                                                                                                                                                                           0.0s
 => [2/2] RUN wget https://alpinelinux.org                                                                                                                                                                                    0.3s
 => exporting to image                                                                                                                                                                                                        0.0s
 => => exporting layers                                                                                                                                                                                                       0.0s
 => => writing image sha256:877f5fe65644eaf884b2de6c5fb566bf8999f3087e988496d74323aedf440fd9                                                                                                                                  0.0s
```

**Comment by stephen-turner** [comment]
@temp Maybe you have a different bug. Can you reduce it to a test case like Phil's that just has a two-line Dockerfile, or execs into the container and runs a single command, or something like that?

(Also, just to confirm, you're on build 50534, right? I ask because there were some earlier pre-release builds of 2.5.4 mentioned on some other tickets that wouldn't have had this fix in.)

**Comment by temp** [comment]
Build is 50534. Will try to produce a small testcase.

**Comment by temp** [comment]
Here we go.

Not working, alpine:edge

```dockerfile
FROM alpine:edge

RUN apk --no-cache upgrade \
    && apk add curl \
    && curl -LsS -o /tmp/composer-setup.php https://getcomposer.org/installer \
    && curl -LsS -o /tmp/composer-setup.sig https://composer.github.io/installer.sig
```

```
$ DOCKER_BUILDKIT=0 docker build .
Sending build context to Docker daemon  95.23kB
Step 1/2 : FROM alpine:edge
 ---> 003bcf045729
Step 2/2 : RUN apk --no-cache upgrade     && apk add curl     && curl -LsS -o /tmp/composer-setup.php https://getcomposer.org/installer     && curl -LsS -o /tmp/composer-setup.sig https://composer.github.io/installer.sig
 ---> Running in 7ec9c7d46761
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
Upgrading critical system libraries and apk-tools:
(1/1) Upgrading apk-tools (2.12.0_rc1-r2 -> 2.12.0-r2)
Executing busybox-1.32.0-r3.trigger
Continuing the upgrade transaction with new apk-tools:
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/7) Upgrading musl (1.2.1-r1 -> 1.2.2_pre5-r0)
(2/7) Upgrading busybox (1.32.0-r3 -> 1.32.0-r7)
Executing busybox-1.32.0-r7.post-upgrade
(3/7) Upgrading libcrypto1.1 (1.1.1g-r0 -> 1.1.1h-r0)
(4/7) Upgrading libssl1.1 (1.1.1g-r0 -> 1.1.1h-r0)
(5/7) Upgrading ca-certificates-bundle (20191127-r4 -> 20191127-r5)
(6/7) Upgrading ssl_client (1.32.0-r3 -> 1.32.0-r7)
(7/7) Upgrading musl-utils (1.2.1-r1 -> 1.2.2_pre5-r0)
Executing busybox-1.32.0-r7.trigger
OK: 6 MiB in 14 packages
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/5) Installing ca-certificates (20191127-r5)
(2/5) Installing brotli-libs (1.0.9-r2)
(3/5) Installing nghttp2-libs (1.42.0-r0)
(4/5) Installing libcurl (7.73.0-r0)
(5/5) Installing curl (7.73.0-r0)
Executing busybox-1.32.0-r7.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 8 MiB in 19 packages
curl: (6) Could not resolve host: composer.github.io
The command '/bin/sh -c apk --no-cache upgrade     && apk add curl     && curl -LsS -o /tmp/composer-setup.php https://getcomposer.org/installer     && curl -LsS -o /tmp/composer-setup.sig https://composer.github.io/installer.sig' returned a non-zero code: 6
```

DNS is resolvable:
```
$ ping composer.github.io
PING composer.github.io (185.199.109.153): 56 data bytes
64 bytes from 185.199.109.153: icmp_seq=0 ttl=55 time=8.073 ms
````

Working, alpine:3.12

```dockerfile
FROM alpine:3.12

RUN apk --no-cache upgrade \
    && apk add curl \
    && curl -LsS -o /tmp/composer-setup.php https://getcomposer.org/installer \
    && curl -LsS -o /tmp/composer-setup.sig https://composer.github.io/installer.sig
```

```
$ docker build .
Sending build context to Docker daemon  95.23kB
Step 1/2 : FROM alpine:3.12
 ---> d6e46aa2470d
Step 2/2 : RUN apk --no-cache upgrade     && apk add curl     && curl -LsS -o /tmp/composer-setup.php https://getcomposer.org/installer     && curl -LsS -o /tmp/composer-setup.sig https://composer.github.io/installer.sig
 ---> Running in 4fcd0bf448c5
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/2) Upgrading musl (1.1.24-r9 -> 1.1.24-r10)
(2/2) Upgrading musl-utils (1.1.24-r9 -> 1.1.24-r10)
Executing busybox-1.31.1-r19.trigger
OK: 6 MiB in 14 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ca-certificates (20191127-r4)
(2/4) Installing nghttp2-libs (1.41.0-r0)
(3/4) Installing libcurl (7.69.1-r1)
(4/4) Installing curl (7.69.1-r1)
Executing busybox-1.31.1-r19.trigger
Executing ca-certificates-20191127-r4.trigger
OK: 7 MiB in 18 packages
Removing intermediate container 4fcd0bf448c5
 ---> c1294646146b
Successfully built c1294646146b
```

**Comment by PhilETaylor** [comment]
I get those same results with `alpine:edge`

**Comment by temp** [comment]
Oh weird. I *only* have the problems in edge, not in 3.12.

**Comment by temp** [comment]
Here is a thread that mentions these problems as well: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11879.

**Comment by temp** [comment]
Since alpine:edge will be released as 3.13 in a few days, this might become a bigger problem...

**Comment by stephen-turner** [comment]
Yes, the diagnosis we found in https://gitlab.alpinelinux.org/alpine/aports/-/issues/11879 is exactly what we've fixed. And it's fixed Phil's case. We'll try and find out what's different about your example.

**Comment by temp** [comment]
The problem seems to be related to musl 1.2.1+, with musl 1.1.x the error doesn't occur.

**Comment by radhus** [comment]
@stephen-turner the test case I posted in #5088 still works but I have to change it to `dl-cdn.alpinelinux.org` to get a reliable result.

Full reproducable:
```
$ cat Dockerfile
FROM alpine:edge
RUN apk add --no-cache bind-tools
$ # build with --network=host to prevent failure
$ docker build --network=host -t asd .
[...]
$ docker run --rm -ti asd:latest sh -c 'dig A dl-cdn.alpinelinux.org AAAA dl-cdn.alpinelinux.org'
;; Warning, extra type option

; <<>> DiG 9.16.8 <<>> A dl-cdn.alpinelinux.org AAAA dl-cdn.alpinelinux.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 39719
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dl-cdn.alpinelinux.org.                IN      AAAA

;; Query time: 3 msec
;; SERVER: 192.168.65.1#53(192.168.65.1)
;; WHEN: Tue Dec 08 10:53:27 UTC 2020
;; MSG SIZE  rcvd: 40

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17329
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dl-cdn.alpinelinux.org.                IN      A

;; ANSWER SECTION:
dl-cdn.alpinelinux.org. 4502    IN      CNAME   dualstack.d.sni.global.fastly.net.
dualstack.d.sni.global.fastly.net. 30 IN A      151.101.194.133
dualstack.d.sni.global.fastly.net. 30 IN A      151.101.66.133
dualstack.d.sni.global.fastly.net. 30 IN A      151.101.130.133
dualstack.d.sni.global.fastly.net. 30 IN A      151.101.2.133

;; Query time: 11 msec
;; SERVER: 192.168.65.1#53(192.168.65.1)
;; WHEN: Tue Dec 08 10:53:27 UTC 2020
;; MSG SIZE  rcvd: 151
```

Most times, the DNS server is still returning `NXDOMAIN` instead of `NOERROR` for the `AAAA` record, which makes musl interpret this as the domain doesn't exist.

**Comment by PhilETaylor** [comment]
ipv6 now "a feature" on Docker For Mac? I thought the docs specifically stated that ipv6 for Docker For Mac was a no no ?

**Comment by stephen-turner** [comment]
So Phil's original Dockerfile is fixed:

```
FROM alpine:edge
RUN wget https://alpinelinux.org
```

but this very similar one breaks on Alpine Edge (working on Alpine 3.12):

```
FROM alpine:edge
RUN wget https://composer.github.io
```

Obviously there's a case we missed, we'll have another go. Thanks for the reports.

**Comment by richfelker** [comment]
I feel like this would be resolved more easily just taking Alpine out of the picture and testing `host -t aaaa` on a v4-only domain using whatever dist you're comfortable with, and seeing whether it produces NODATA (correct) or NxDomain (wrong).

**Comment by djs55** [comment]
Sorry for the confusion on this one. We have another (!) test build which hopefully has this problem fixed: https://desktop-stage.docker.com/mac/edge/50679/Docker.dmg

```
/ # host -t AAAA composer.github.io
composer.github.io has no AAAA record
/ # host -t A composer.github.io
composer.github.io has address 185.199.108.153
composer.github.io has address 185.199.109.153
composer.github.io has address 185.199.110.153
composer.github.io has address 185.199.111.153
/ # host -t AAAA does.not.exist
Host does.not.exist not found: 3(NXDOMAIN)
```

Unfortunately the API we're currently using (Apple [DNSServiceRef](https://developer.apple.com/documentation/dnssd/dnsserviceref)) isn't making this easy for us: it doesn't like to distinguish between NODATA and NXDOMAIN itself. We originally chose it to ensure we were able to transparently handle mDNS lookups and Mac VPN configurations. In the latest build we follow up a generic "record not found" with an "ANY" query to see if we can discover anything about the name at all:
```
% host -t ANY composer.github.io
composer.github.io host information "RFC8482" ""
% host -t ANY dave.recoil.org   
dave.recoil.org is an alias for static.recoil.org.
% host -t ANY does.not.exist 
Host does.not.exist not found: 3(NXDOMAIN)
```
If this is insufficient we'll have to investigate another API.

Thanks for all your help so far understanding this one!

**Comment by richfelker** [comment]
For what it's worth I think you should just forward the actual DNS requests rather than using DNSServiceRef. This is the only way to provide valid DNSSEC-signed results to the guest, which reasonable guests may want. Anything done via DNSServiceRef is inherently a DNS forgery. At least this should be an option to the user, with the tradeoffs properly documented.

I'm not sure how well ANY queries will work for you. They're considered deprecated, and some nasty auth nameservers don't support them - NotImpl from auth server which translates into ServFail from the recursive, which is permanently inconclusive for a secure zone with DNSSEC.

You should probably open a bug report against Apple's DNSServiceRef API complaining that it can't properly differentiate these results. Differentiating them is necessary for correct use of DNSSEC even just on the host itself (ignoring guests/virtualization issues). You can't implement DANE validation with the limitations they've imposed.

**Comment by djs55** [comment]
@richfelker thanks for the detailed feedback. I think we have an opportunity to improve this in the near future -- when we update to the new VM APIs needed for Apple Silicon we'll be able to use an Apple-provided DNS server on an internal IP, rather than our current DNSServiceRef-based implementation. With any luck this Apple-provided server will do a better job.

**Comment by richfelker** [comment]
Sounds good. If you have a better long-term solution in mind (local DNS server is it -- this is the right way to do DNSSEC anyway) I think the trick with ANY will probably serve you okay for now. I've mainly seen cautions against it in environments where you need to be able to resolve arbitrary obscure misconfigured domains (particularly for an outgoing mailserver) and I doubt Docker users will run into problems with it.

**Comment by temp** [comment]
Tried the test build, looking good. Everything is working as expected.

**Comment by temp** [comment]
Correction: The above mentioned DNS problem are fixed, but now `host.docker.internal` can't be resolved:

```
[2020-12-10T08:59:06.074722+01:00] console.ERROR: Error thrown while running command "'a:u'". Message: "Couldn't resolve host name for "http://host.docker.internal/api/employee/employees.json
```

Inside the container:
```
$ ping host.docker.internal
ping: bad address 'host.docker.internal'
```

**Comment by djs55** [comment]
@temp thanks -- the code for `host.docker.internal` was separate and still buggy. I'm working on a fix now.

**Comment by OTLabs** [comment]
Just installed D4M 3.0.0. The issue still persists.

**Comment by stephen-turner** [comment]
Correct, we weren’t expecting it to have been fixed in this version.

**Comment by OTLabs** [comment]
I am a bit confused as this issue was mentioned as solved in release notes for D4M 3.0.0, (second bullet in [Bug fixes and minor changes](https://docs.docker.com/docker-for-mac/release-notes/#bug-fixes-and-minor-changes-1)).

**Comment by PhilETaylor** [comment]
@OTLabs D4M 3.0.0 fixes the initial reported issue I made, but not then the subsequent issues reported in this thread. Read the whole thread.

**Comment by temp** [comment]
@PhilETaylor OTLabs has a point, the alpine-link in the changelog is related to the alpine:edge problem, not to the initial alpine:3.12 problem. musl 1.2.1 was introduced in alpine:edge.

**Comment by PhilETaylor** [comment]
Look at this thread - you will see that it was closed on 4 days ago and reopened 3 days ago when others reported other DNS related issues. The initial issue reported here by me is resolved and works with alpine:edge and alpine:3.12 in D4M 3.0.0

The subsequent reports are about a different test case/scenario. 

Im guessing the release notes were written before these additional issues came to light.

**Comment by temp** [comment]
@PhilETaylor yes, but the wrong alpine issue is linked. 12051 was the initial issue, 11879 the one that I threw in the ring, with the musl problem. And the changelog states 11879.

**Comment by stephen-turner** [comment]
Ah, I understand the confusion now. Sorry about that. I'll remove it from the release notes for 3.0.0 (although it probably won't get merged until Monday now) as it was not fully fixed in that version.

**Comment by spkane** [comment]
Are there any updates in regards to this issue? It has been very silent for the last 3 weeks despite being actively listed as a known issue for the last few releases.

**Comment by stephen-turner** [comment]
We have an internal fix. It will be released in 3.1 in a couple of weeks.

**Comment by stephen-turner** [comment]
3.1 is now released, and fixes this bug.
