### ISSUE TITLE
Docker for Desktop Preview M1 on Mac - hang during startup

### ISSUE THREAD

**Issue by taraszka** [docker/for-mac#5130]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Desktop for Mac should up and run

### Actual behavior
Hangs on startup

### Information

  - macOS Version: macOS 11.1 (20C69)

### Diagnostic logs
```
INFO[0542] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0544] connecting to tcp+connect://192.168.64.1:1999...
INFO[0576] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0578] connecting to tcp+connect://192.168.64.1:1999...
INFO[0610] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0612] connecting to tcp+connect://192.168.64.1:1999...
INFO[0643] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0645] connecting to tcp+connect://192.168.64.1:1999...
INFO[0677] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0679] connecting to tcp+connect://192.168.64.1:1999...
```

```
Docker for Mac: Preview 5
```

### Steps to reproduce the behavior

Reset Docker to defaults / factory defaults or uninstall it
When docker for Desktop starts it want to talk to vpnkit-bridge at `192.168.64.1: 1999`

The VPNKit Bridge itself start and binds to `0.0.0.0:1999`:
```
/Data/log/host/vpnkit-bridge.log:2:time="2020-12-14T21:38:57+01:00" level=info msg="waiting for connection on tcp+listen://0.0.0.0:1999..."
```

But the bridge100 have different IP address: 
```
 ifconfig bridge100
bridge100: flags=8a63<UP,BROADCAST,SMART,RUNNING,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500
	options=3<RXCSUM,TXCSUM>
	ether 1a:3e:ef:0d:be:64
	inet6 fe80::14a4:ac58:32cb:3b03%bridge100 prefixlen 64 secured scopeid 0x15
	inet 192.168.65.1 netmask 0xffffff00 broadcast 192.168.64.255
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: en6 flags=803<LEARNING,DISCOVER,PRIVATE>
	        ifmaxaddr 0 port 20 priority 0 path cost 0
	Address cache:
		3a:20:b5:c6:f2:ca Vlan1 en6 1200 flags=0<>
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```

When I added correct IP address to the bridge interface, VM started, Docker for Desktop reported that Docker is running fine.
```
INFO[0679] connecting to tcp+connect://192.168.64.1:1999...
INFO[0679] connected!
INFO[0679] Proxy gui: waiting for remote service to be available
INFO[0679] Proxy vpnkit-data: waiting for remote service to be available
INFO[0679] Proxy docker-proxy: waiting for remote service to be available
INFO[0679] Proxy ssh-auth: waiting for remote service to be available
INFO[0679] Proxy vpnkit: waiting for remote service to be available
INFO[0679] Proxy backend: waiting for remote service to be available
INFO[0679] Proxy filesystem: waiting for remote service to be available
INFO[0679] received ack for service gui, publishing locally
INFO[0679] received ack for service docker-proxy, publishing locally
INFO[0679] received ack for service vpnkit-data, publishing locally
(...)
INFO[1970-01-01T00:11:26.588751285Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[1970-01-01T00:11:26.588953494Z] serving...                                    address=/run/containerd/debug.sock
INFO[1970-01-01T00:11:26.589022244Z] serving...                                    address=/run/containerd/containerd.sock.ttrpc
INFO[1970-01-01T00:11:26.589068285Z] serving...                                    address=/run/containerd/containerd.sock
INFO[1970-01-01T00:11:26.589120077Z] containerd successfully booted in 0.189638s
```

**Comment by taraszka** [comment]
So, Docker started. But, VM is at 192.168.64.* network, where the rest of the stack is expecting to have some services available at 192.168.65.* network:
```
$ docker build -f Dockerfile.arm64 .
[+] Building 11.4s (3/3) FINISHED
 => [internal] load build definition from Dockerfile.arm64                                                                                                                   1.2s
 => => transferring dockerfile: 2.27kB                                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                                            1.0s
 => => transferring context: 2B                                                                                                                                              0.0s
 => ERROR [internal] load metadata for docker.io/library/alpine:latest                                                                                                      10.0s
------
 > [internal] load metadata for docker.io/library/alpine:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head https://registry-1.docker.io/v2/library/alpine/manifests/latest: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.9:57078->192.168.65.1:53: i/o timeout
```

**Comment by taraszka** [comment]
Ok, I think I have it. Docker VM seems has wrong clock/time set or it simply ignore that host hardware clock/date or because of the missing network, the network time isn't set correctly *inside* the VM, please have a look at the fragment of the log:
```
Cleaning up stale service: "vpnkit-forwarder"
time="1970-01-01T00:01:13.583167785Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/acpid pid=735
time="1970-01-01T00:01:13.790444326Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/binfmt pid=790
time="1970-01-01T00:01:13.981708243Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/dhcpcd pid=841
time="1970-01-01T00:01:14.148744577Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/diagnose pid=894
time="1970-01-01T00:01:14.328368952Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/docker pid=961
time="1970-01-01T00:01:14.519149285Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/kmsg pid=1020
time="1970-01-01T00:01:14.720843868Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/sntpc pid=1108
time="1970-01-01T00:01:14.920503869Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/socks pid=1161
time="1970-01-01T00:01:15.126930535Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/trim-after-delete pid=1218
time="1970-01-01T00:01:15.368426244Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/vpnkit-forwarder pid=1286
[   75.702343] bpfilter: Loaded bpfilter_umh pid 1341
```

Thanks.

**Comment by BhavyaSree** [comment]
Thanks @taraszka , I'm facing the same issue on the Preview7 build. As you explained, docker was able to start after resetting the _ip_ for `bridge100` to _192.168.64.1_.

```shell
sudo ifconfig bridge100 inet 192.168.64.1 netmask 255.255.255.0
```

**Comment by AlexMartinFR** [comment]
I had the same issue with Preview7 and after running your command, Docker is finally starting.

Thanks, @BhavyaSree & @taraszka 👍

**Comment by guglen** [comment]
up
Does someone have a solution?

**Comment by guglen** [comment]
the problem of IP 192.168.65.1 of the bridge card "seems" to have been solved by modifying the file

/Library/preferences/SystemConfiguration/com.apple.vmnet.plist

by editing the final part of the file:

         <key> Shared_Net_Address </key>
         <string> 192.168.64.1 </string>
         <key> Shared_Net_Mask </key>
         <string> 255.255.255.0 </string>

**Comment by pencilcheck** [comment]
None of the solution above works for me. Still get the same error.

**Comment by guglen** [comment]
@pencilcheck 
do you have the same scenario?

do you have the virtual card on IP 192.168.65.1?

read on the "console.log":

INFO[0542] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0544] connecting to tcp+connect://192.168.64.1:1999...
INFO[0576] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0578] connecting to tcp+connect://192.168.64.1:1999...
INFO[0610] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0612] connecting to tcp+connect://192.168.64.1:1999...
INFO[0643] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0645] connecting to tcp+connect://192.168.64.1:1999...
INFO[0677] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0679] connecting to tcp+connect://192.168.64.1:1999...

what do you read in the /Library/preferences/SystemConfiguration/com.apple.vmnet.plist file?

**Comment by cmorgia** [comment]
@guglen thanks a lot for your suggestion, it works perfectly here. I'm just wondering why I do have something like 172.16.214.1/24 in my original config file.
Anyway, with your trick, my docker is running and I can start some serious testing

**Comment by pencilcheck** [comment]
> @pencilcheck
> do you have the same scenario?
> 
> do you have the virtual card on IP 192.168.65.1?
> 
> read on the "console.log":
> 
> INFO[0542] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
> INFO[0544] connecting to tcp+connect://192.168.64.1:1999...
> INFO[0576] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
> INFO[0578] connecting to tcp+connect://192.168.64.1:1999...
> INFO[0610] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
> INFO[0612] connecting to tcp+connect://192.168.64.1:1999...
> INFO[0643] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
> INFO[0645] connecting to tcp+connect://192.168.64.1:1999...
> INFO[0677] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
> INFO[0679] connecting to tcp+connect://192.168.64.1:1999...
> 
> what do you read in the /Library/preferences/SystemConfiguration/com.apple.vmnet.plist file?

@guglen It is on 192.168.64.1. I already did what was stated here to make sure it is on the IP but it still timeout.

**Comment by boardthatpowder** [comment]
I have the same issue as @pencilcheck. Error being reported is:

```
INFO[0190] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable
INFO[0192] connecting to tcp+connect://192.168.64.1:1999...
```

But the bridge is already showing the correct up:

```
% ifconfig bridge100

bridge100: flags=8a63<UP,BROADCAST,SMART,RUNNING,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500
	options=3<RXCSUM,TXCSUM>
	ether 4e:20:b8:ae:5f:64
	inet 192.168.64.1 netmask 0xffffff00 broadcast 192.168.64.255
	inet6 fe80::8cf:cd47:aff5:3ce1%bridge100 prefixlen 64 secured scopeid 0x13
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: en7 flags=803<LEARNING,DISCOVER,PRIVATE>
	        ifmaxaddr 0 port 18 priority 0 path cost 0
	Address cache:
		d2:ff:2c:2:3f:dc Vlan1 en7 1199 flags=0<>
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```

**Comment by boardthatpowder** [comment]
I realized immediately after posting it what my issue may had been..... had the MacOS Firewall turned on. Turned it off and docker works again.

**Comment by tobtherusch** [comment]
> ```shell
> sudo ifconfig bridge100 inet 192.168.64.1 netmask 255.255.255.0
> ```

@BhavyaSree How do you make these changes persistent. After changing the network on this bridge100 and restarting the docker desktop process, it's again on the net 192.168.66.1.

**Comment by riouruma** [comment]
> sudo ifconfig bridge100 inet 192.168.64.1 netmask 255.255.255.0

I got the error when I pulled the image after doing the above command.

```
$ docker pull php:7.4-fpm
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.2:50038->192.168.64.1:53: read: connection refused
```

**Comment by guglen** [comment]
> > sudo ifconfig bridge100 inet 192.168.64.1 netmask 255.255.255.0
> 
> I got the error when I pulled the image after doing the above command.
> 
> ```
> $ docker pull php:7.4-fpm
> Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.2:50038->192.168.64.1:53: read: connection refused
> ```

you don't have to execute that command, you have to find the file 

/Library/preferences/SystemConfiguration/com.apple.vmnet.plist

and edit it

**Comment by riouruma** [comment]
@guglen 
This is near the end of com.apple.vmnet.plist.

```
<key>Shared_Net_Address</key>
<string>192.168.64.1</string>
<key>Shared_Net_Mask</key>
<string>255.255.255.0</string>
```

What should I do?

**Comment by oleic** [comment]
Deactivating Little Snitch seems also solve the startup problem.

**Comment by guglen** [comment]
> @guglen
> This is near the end of com.apple.vmnet.plist.
> 
> ```
> <key>Shared_Net_Address</key>
> <string>192.168.64.1</string>
> <key>Shared_Net_Mask</key>
> <string>255.255.255.0</string>
> ```
> 
> What should I do?

when docker starts what is the bridge100 IP?

**Comment by klement** [comment]
I see this issue intermittently and what helps for me is to turn off the firewall, restart docker, then turn on the firewall.

**Comment by llauderesv** [comment]
I have the issue on my machine when using ip 192.168.65.1

**Comment by rajatkb-typito** [comment]
I faced the same issue from yesterday evening. It happened once I tried to start minikube. I am not sure what broke but minkube did not started and instead broke docker. Earlier my docker installation did not needed this particular modification. Just thought of mentioning. Can anyone give some clue what must have happened ?? I was able to solve the issue by changing the plist file but need to understand why did it solved the issue.

**Comment by Rotzke** [comment]
> I faced the same issue from yesterday evening. It happened once I tried to start minikube. I am not sure what broke but minkube did not started and instead broke docker. Earlier my docker installation did not needed this particular modification. Just thought of mentioning. Can anyone give some clue what must have happened ?? I was able to solve the issue by changing the plist file but need to understand why did it solved the issue.

Will double the question, helped as well, but what was the problem with Minikube, why the installation changed the bridge100 IP?

**Comment by llauderesv** [comment]
> > @guglen
> > This is near the end of com.apple.vmnet.plist.
> > ```
> > <key>Shared_Net_Address</key>
> > <string>192.168.64.1</string>
> > <key>Shared_Net_Mask</key>
> > <string>255.255.255.0</string>
> > ```
> > 
> > 
> > What should I do?
> 
> when docker starts what is the bridge100 IP?

This works for me, changing the Shared_Net_Address to 192.168.4.1 and restart the docker solved my issue.

**Comment by webvictim** [comment]
Good to know that it's possible to change the shared network address as 192.168.64.0/24 is the internal IP range I use at home.

**Comment by weibaohui** [comment]
> I faced the same issue from yesterday evening. It happened once I tried to start minikube. I am not sure what broke but minkube did not started and instead broke docker. Earlier my docker installation did not needed this particular modification. Just thought of mentioning. Can anyone give some clue what must have happened ?? I was able to solve the issue by changing the plist file but need to understand why did it solved the issue.

me,too

**Comment by tangl163** [comment]
I met the same issue and solved it by `uninstall` and `reinstall` the same docker version _Docker-AppleSilicon-Preview7_

**Comment by moolen** [comment]
This helped in my setup:

```
# this will connect to the VM's tty
# you will see some stdout - ignore it!
nc -U /Users/{your-user}/Library/Containers/com.docker.docker/Data/vms/0/console.sock

# once you see the output type the following and hit enter
ip a a 192.168.64.10/24 dev eth0

# the stdout should change now significantly and docker should come up
# hit ctrl-c to get out of the VM
```

**Comment by weibaohui** [comment]
try this one:
https://desktop.docker.com/mac/stable/arm64/60902/Docker.dmg

this works for me

**Comment by ezeagwulae** [comment]
still having the same issue even with the latest preview "Docker Desktop preview 3.1.0 (60984)" with docker starting at 192.168.65.0 but returning the following error

```
 => => transferring dockerfile: 150B                                                                0.0s
 => [internal] load .dockerignore                                                                   0.5s
 => => transferring context: 2B                                                                     0.0s
 => ERROR [internal] load metadata for docker.io/library/tomcat:8.5.55-jdk8                         1.0s
------
 > [internal] load metadata for docker.io/library/tomcat:8.5.55-jdk8:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:bb59f86923e098ad54f485853e8f8859e2243cfceae762cccc2e5460ab006237: not found
ERROR: Service 'web' failed to build
```

I've checked the bridge is showing up with the correct IP
```
❯ ifconfig bridge100
bridge100: flags=8a63<UP,BROADCAST,SMART,RUNNING,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500
	options=3<RXCSUM,TXCSUM>
	ether a2:78:17:28:2b:64
	inet 192.168.64.1 netmask 0xffffff00 broadcast 192.168.64.255
	inet6 fe80::842:bc3:6d49:c77d%bridge100 prefixlen 64 secured scopeid 0x17
	inet6 fd32:b01a:d73f:b6f7:453:8910:2e2:afce prefixlen 64 autoconf secured
	inet6 fd32:b01a:d73f:b6f7:e4a8:de4:1480:d871 prefixlen 64 autoconf temporary
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: en6 flags=803<LEARNING,DISCOVER,PRIVATE>
	        ifmaxaddr 0 port 22 priority 0 path cost 0
	Address cache:
		b6:3d:65:71:b9:7 Vlan1 en6 1200 flags=0<>
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
❯
```

also checked `com.apple.vmnet.plist` and that looks right.
```
	<key>Shared_Net_Address</key>
	<string>192.168.64.1</string>
	<key>Shared_Net_Mask</key>
	<string>255.255.255.0</string>
```

anything else to try?

**Comment by guylyons** [comment]
> I realized immediately after posting it what my issue may had been..... had the MacOS Firewall turned on. Turned it off and docker works again.

This fixed my issue.

**Comment by mbatesco** [comment]
After uninstalling the previous release of Docker, I install Docker Desktop RC 1 for Apple Silicon release on 3/18, all was well until I rebooted.  On reboot  docker hangs.  I kill all the Docker processes, stop both the Firewall and VPN, start docker it starts fine. Restart the Firewall and VPN and no issues with building and running containers.

I ran the diagnostics and got this ID A520BB73-6BE1-4D31-ADDF-EBB2D818B633/20210321231415.  

The diagnostic log contains: 
time="2021-03-21T16:14:44-07:00" level=info msg="HTTP GET: localhost /fuse/time" type=http
time="2021-03-21T16:14:44-07:00" level=warning msg="Get \"http://localhost/fuse/time\": dial unix lifecycle-server.sock: connect: connection refused" type=http
time="2021-03-21T16:14:44-07:00" level=info msg="Gathering HTTP GET localhost /fuse/count" type=list
time="2021-03-21T16:14:44-07:00" level=info msg="HTTP GET: localhost /fuse/count" type=http
time="2021-03-21T16:14:44-07:00" level=warning msg="Get \"http://localhost/fuse/count\": dial unix lifecycle-server.sock: connect: connection refused" type=http
time="2021-03-21T16:14:44-07:00" level=info msg="Gathering HTTP GET localhost /fuse/filename" type=list
time="2021-03-21T16:14:44-07:00" level=info msg="HTTP GET: localhost /fuse/filename" type=http
time="2021-03-21T16:14:44-07:00" level=warning msg="Get \"http://localhost/fuse/filename\": dial unix lifecycle-server.sock: connect: connection refused" type=http
time="2021-03-21T16:14:44-07:00" level=info msg="Gathering HTTP GET localhost /fuse/calls" type=list
time="2021-03-21T16:14:44-07:00" level=info msg="HTTP GET: localhost /fuse/calls" type=http
time="2021-03-21T16:14:44-07:00" level=warning msg="Get \"http://localhost/fuse/calls\": dial unix lifecycle-server.sock: connect: connection refused" type=http
time="2021-03-21T16:14:44-07:00" level=info msg="Gathering fuseVolumeGatherer" type=list
time="2021-03-21T16:14:44-07:00" level=info msg="Gathering fuseStacksGatherer" type=list
time="2021-03-21T16:14:44-07:00" level=info msg="Gathering mutagenGatherer" type=list
time="2021-03-21T16:14:49-07:00" level=info msg="Gathering diagnosticd.sock" type=list
time="2021-03-21T16:14:49-07:00" level=info msg="Getting Linux Diagnostics via a unix socket: diagnosticd.sock" type=unixsock
time="2021-03-21T16:14:49-07:00" level=warning msg="/diagnostics failed: Get \"http://unix/diagnostics\": dial unix diagnosticd.sock: connect: connection refused" type=unixsock
time="2021-03-21T16:14:49-07:00" level=info msg="All 82 gatherers finished" type=list


What else can I provide to help?

The process is recreatable every time.
