### ISSUE TITLE
Cannot Ctrl-Z out of "docker logs -f" -- have to kill process  

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#5501]
- [X ] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:
2984509E-BD01-4F9C-AC7A-F5018336BD82/20210324214856

### Expected behavior
`docker logs -f <container>` can be Ctrl-Z'd to be put into background
### Actual behavior
Pressing Ctrl-Z after `docker logs -f <container>` just displays `^Z` on screen, also Ctrl-C does nothing just displays `^C`. Even Ctrl-P Ctrl-Q does nothing, displays `^P`
### Information
I've seen this behavior for at least couple of years.
  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.2.2

### Steps to reproduce the behavior
  1. `docker logs -f pushgateway` (any running container)
  2. Press Ctrl-Z to put into background, you can't and can't even Ctrl-C, have to `ps auxww|grep docker.cli` and `kill -9` the process!

```
$ docker logs -f pushgateway
level=info ts=2020-11-27T04:06:30.563Z caller=main.go:83 msg="starting pushgateway" version="(version=1.3.0, branch=HEAD, revision=c28992c985ce6c4fcf4247ba9736b72a3d43882f)"
...
level=info ts=2021-03-15T17:12:08.618Z caller=main.go:84 build_context="(go=go1.15.2, user=root@cf69166ae53e, date=20201001-12:03:34)"
level=info ts=2021-03-15T17:12:08.633Z caller=main.go:137 listen_address=:9091
^Z

^Z^Z^Z^Z^Z
^C^C^C^C^C

^P
```
Does this happen to only me?? Happens with zsh and bash, Terminal and iTerm2.

**Comment by stephen-turner** [comment]
@jamshid Thank you for the report. These references will explain why it happens and how to build your container to avoid it:
https://forums.docker.com/t/docker-run-cannot-be-killed-with-ctrl-c/13108/2
https://stackoverflow.com/questions/31350335/docker-not-responding-to-ctrlc-in-terminal
https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html#process-behavior-inside-docker-containers

**Comment by jamshid** [comment]
Wait @stephen-turner this is about `docker logs`! 
I know about `docker run` and an init process trapping of Ctrl-C.
If I run the `docker logs` on linux I am able to Ctrl-Z.

**Comment by stephen-turner** [comment]
Oh yes, sorry, I thought it was the same. I'll reopen the ticket.

**Comment by jamshid** [comment]
Btw the hang happens with other `docker` commands too. I have this still running from last night where I Ctrl-Z'd out of a `docker system prune`.  I have to kill -9 the process to get my terminal back.
```
jamshid          76416   0.0  0.0  4463460  14516 s016  T+   12:56AM   0:00.07 /usr/local/bin/com.docker.cli system prune -f --volumes
```

**Comment by jamshid** [comment]
This seems related to https://github.com/docker/compose-cli/issues/1477#issuecomment-810035230.

**Comment by jamshid** [comment]
This is **not** fixed in latest Docker for Mac 3.5.2. 

I feel like I'm the only one seeing this because it is really easy to reproduce and it's really annoying. 

Ctrl-Z is ignored by `docker logs` and then even Ctrl-C does not work, I have to `kill -9` the `com.docker.cli` process in another window to get my prompt back.

```
% docker run -d --name ctrlz --init centos sleep 900

% docker logs -f ctrlz

^Z^Z^Z^Z^C^C^C^C^C^C

^C^C
^Z^Z^Z
```

```
% ps auxw|grep docker.cli
jamshid          56930   0.0  0.0  4417888    832 s012  S+    1:25PM   0:00.00 grep docker.cli
jamshid          56880   0.0  0.1  5043320  26452 s013  T+    1:22PM   0:00.04 /usr/local/bin/com.docker.cli logs -f ctrlz

% kill -9 56880
```

**Comment by mattlaw** [comment]
I'm experiencing the same thing. I noticed that there are three related processes in play:

```
  PID  PPID COMMAND
22654   660 docker compose ...
22656 22654 /Applications/Docker.app/Contents/Resources/bin/com.docker.cli compose ...
22659 22656 $HOME/.docker/cli-plugins/docker-compose compose ...
```

I can suspend the process normally by `kill -STOP 22654`. Then `fg` is able to resume it in the other shell.

If I hit Ctrl-Z, only the grandchild process is suspended - `kill -CONT 22659` can resume it but it's otherwise completely unresponsive as described.

**Comment by groner** [comment]
I'm hitting this today.

It looks like `/usr/local/bin/docker` is a symlink to `/Applications/Docker.app/Contents/Resources/bin/docker`, which spawns `/Applications/Docker.app/Contents/Resources/bin/com.docker.cli`. Hitting `^Z` suspends the `com.docker.cli` process but not the parent (`docker`) process. 

I'm not sure what the intermediate process is, but running `com.docker.cli` directly seems to work fine without it. Changing the `/usr/local/bin/docker` symlink to point to `com.docker.cli` seems like a way to work around this until docker addresses this.

**Comment by rolodato** [comment]
Also running into this. To avoid messing with the symlink, I created an alias in my `~/.zshrc` per @groner's suggestion:

```
alias docker=/Applications/Docker.app/Contents/Resources/bin/com.docker.cli
```

**Comment by karman-docker** [comment]
Ctrl-Z on `docker logs -f <container>` should work now on 4.23.0

**Comment by mattlaw** [comment]
Still not working for me on 4.23.0 😊. also still seeing similar arrangements of subprocesses

**Comment by karman-docker** [comment]
my apologies, yes it is still an outstanding issue. I was using a wrong cli.

**Comment by MihaelaStoica** [comment]
This has been fixed in the latest version on Docker Desktop.
We verified that Ctrl-Z and Ctrl-C on `docker logs -f <container>` works in v4.27.0.
