### ISSUE TITLE
Apple Silicon　Docker doesn't start

### ISSUE THREAD

**Issue by moesuke** [docker/for-mac#5573]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:AD1A5731-5A23-4C3E-B9B4-324D4921D88C/20210413235804

### Expected behavior
After PC crashed, Docker containers doesn't start.

### Actual behavior

https://user-images.githubusercontent.com/81308242/114636082-236ff500-9d01-11eb-816b-f2ad6c0f8d3d.mov

### Information
  - macOS Version:mac OS（M1） Big Sur 11.2.3
  - Docker Desktop Version:3.3.0
 ![image](https://user-images.githubusercontent.com/81308242/114635890-b8beb980-9d00-11eb-9c6c-6d960a452662.png)
I've repeatedly reinstalled and tried removing traces of previous installations.

### Steps to reproduce the behavior
upgrading to macos 11.2.3
Crashed MacOS
Run containers

**Comment by adtrevor** [comment]
I had a pretty similar issue where it was forever trying to start without ever succeeding, restoring to factory settings and re-installing helped.

**Comment by moesuke** [comment]
Thanks for the comments, @ adtrevor.

I have already restored to factory settings and uninstalled it.
But it doesn't fix 😢

**Comment by moesuke** [comment]
![スクリーンショット 2021-04-15 8 51 02](https://user-images.githubusercontent.com/81308242/114797497-43b9b580-9dce-11eb-9160-b310db002668.png)

Today this screen appeared.

**Comment by itsmekhmtz** [comment]
Facing same issue

**Comment by itsmekhmtz** [comment]
Docker not starting.
<img width="1236" alt="Screenshot 2021-04-15 at 4 28 40 PM" src="https://user-images.githubusercontent.com/64073602/114862223-b3986200-9e07-11eb-9b81-98dab1999b40.png">

**Comment by moesuke** [comment]
It was fixed.
MacOS Internet Sharing　was ON.

**Comment by itsmekhmtz** [comment]
Internet sharing is already off but its still not working

<img width="659" alt="Screenshot 2021-04-16 at 10 38 04 AM" src="https://user-images.githubusercontent.com/64073602/114976738-eaba5200-9e9f-11eb-8da4-9bbd8296846f.png">

**Comment by adtrevor** [comment]
I had the same issue as @itsmekhmtz even though my internet sharing was off, I'm not even exactly sure of what exactly was useful in order to make it work (I did a factory reset and tried to uinstall but the uninstall partly failed, after that and restarting it finally worked but this might just be out of luck as it hadn't worked immediately after the factory reset IIRC). Maybe a new issue would make sense since the author solved their problem which had a different cause.

**Comment by itsmekhmtz** [comment]
its resolved after do factory reset, installed helping tools and then restart

**Comment by andymac4182** [comment]
Worth checking how your firewall is set up. If it blocks the docker app or is set to block all connections it won't start. https://github.com/docker/for-mac/issues/5140
