### ISSUE TITLE
Docker fatal error on updating from to 3.5.2... and all up to 4.1.0+: Request failed: GET /analyze/startup-failure failed: no response

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5834]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D18F7D40-640E-4A7A-B066-68B034F7E8BA/20210711130810

### Expected behavior

Normal upgrade

### Actual behavior

Fatal Error: "Request failed: GET /analyze/startup-failure failed: no response"

I'm pretty sure I saw this on every one of 5 upgrades of macOS test runners and my own computer. 

If you click the "Exit" button it seems to continue and finish the upgrade successfully.

I think I saw this on the 3.5.0->3.5.1 upgrade as well, just didn't stop to analyze and report it.

<img width="505" alt="Cursor_and_testbot-macos-drud1" src="https://user-images.githubusercontent.com/112444/125196502-7cbfc580-e217-11eb-9869-280e2cddad01.png">

### Information

  - macOS Version: Big Sur and Catalina
  - Intel chip or Apple chip:both
  - Docker Desktop Version: 3.5.1 upgrade to 3.5.2

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by lorenrh** [comment]
Thanks for the report. We are investigating this, and will update the ticket when we have more information.

**Comment by StefanScherer** [comment]
The workaround so far is to press "Exit" button in that dialog and start Docker Desktop again. It either does the update then or you walk through "Checking for Updates..." and "Update and restart" in the whale menu. It normally works the second time.
We're tracking that issue internally and will come up with a fix in a future version.

**Comment by rfay** [comment]
I got this same exact error upgrading from 3.5.2 to 3.6.0

**Comment by rfay** [comment]
Same exact error upgrading from 3.6.0 to 4.0.0.

**Comment by rfay** [comment]
Same error upgrading from 4.0.0 to 4.0.1, Apple M1.

<img width="506" alt="Screen Shot 2021-09-14 at 4 24 24 PM" src="https://user-images.githubusercontent.com/112444/133342118-fd478b8a-642b-4c06-8e2d-d4e262315da5.png">

**Comment by rfay** [comment]
Same thing upgrading to 4.1.0
<img width="607" alt="rfay_istweb-content-local-web___var_www_html_docroot_and_rfay_d9-web___var_www_html_and_rfay_d9-web___var_www_html" src="https://user-images.githubusercontent.com/112444/135499999-76ff4394-8a9b-4c9e-9c68-83494ee5bfd5.png">

**Comment by StefanScherer** [comment]
Thanks @rfay for the constant reminder. Our internal ticket is still open, I'll speak to the engineering team and try to give it a higher priority.

**Comment by joe0BAB** [comment]
Hi! Please try version 4.2.0. The problem should have been fixed there.

**Comment by rfay** [comment]
Well, I'm glad you're working on this, but it's definitely not solved. Just saw this upgrading to 4.2.0. Are you saying that this should be fixed in future upgrades, or that I should not have seen this upgrading to 4.2.0? 

<img width="574" alt="Cursor_and_rfay-mba2013-macos" src="https://user-images.githubusercontent.com/112444/141017074-d642f0e2-7ff0-4a56-9d6b-caf953e74e5d.png">

**Comment by StefanScherer** [comment]
Thanks @rfay, yes it is fixed in 4.2.0, but it only will take effect in future updates. Looking forward to new releases where you don‘t have to go through this again. 🤞
