### ISSUE TITLE
NO_PROXY / no_proxy appears to be ignored when pulling images

### ISSUE THREAD

**Issue by spkane** [docker/for-mac#5844]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

With this manual proxy setup in Docker for Mac:

```
http_proxy=proxy.example.com:81
https_proxy=proxy.example.com:81
no_proxy=localhost,127.0.0.1,172.16.0.0/12,192.168.0.0/16,.dev.example.com
```

I would expect that I could pull image from Docker Hub via the proxy and pull internal images from registry.dev.example.com, however this does not work. It appears as if no_proxy is ignored in this use case.

### Actual behavior

When trying to pull from `registry.dev.example.com` it fails with a TLS error, very likely because it is trying to go through the proxy.

```
Error response from daemon: Get https://registry.dev.example.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

### Information

  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.5.1

### Steps to reproduce the behavior

  1. Be behind a proxy that can be used to access Docker Hub
  2. Have an internal registry that can be reached directly (and will not work when going through the proxy)
  3. Try to configure Docker so that you can pull images from both Docker Hub and the internal registry, as the same time.

**Comment by gfairchild** [comment]
I just encountered this on my Mac as well. I have to turn on the proxy settings during my `docker build` process so that I can reach out to the public internet for stuff, but then I have to disable my proxy settings when I `docker push` my built image to a local container registry. It's kind of a pain, and it would be wonderful if this got fixed.

**Comment by spkane** [comment]
And if you need both during something like a multi-stage build then there is basically nothing you can do. I am using an Ubuntu VM locally to work around this at the moment.

**Comment by sudoloic** [comment]
I have been encountering this issue as well for some time now, kind of frustrating.

**Comment by gfairchild** [comment]
It looks like this bug has been around for a while. I came across https://github.com/docker/for-mac/issues/2723 as well.

**Comment by mdsummers** [comment]
Finding this to be quite problematic when using a local container registry that should not use the proxy.

Last seen working on version 3.3.2, anything newer does not respect the no proxy configuration.

**Comment by ctrought** [comment]
+1 need to restart the docker vm depending on if I am building or pushing to a registry, this is the worst thing I have to say about my mac :) #2723

**Comment by sei-amellinger** [comment]
Everyone at my workplace has this issue. We have to turn off proxy settings to get to pull images from a local servers.

This happens with all our macs Intel and M1 versions.

**Comment by p1-0tr** [comment]
hi, fixes around handling proxy settings have been released in 4.5.0. Could you update and confirm whether that resolves the issue you've been seeing?

**Comment by sei-amellinger** [comment]
> hi, fixes around handling proxy settings have been released in 4.5.0. Could you update and confirm whether that resolves the issue you've been seeing?

It does not for me. I am running version 4.5.0 build 74594.  I still get the error:

Error response from daemon: Get "https://artifacts.sei.cmu.edu/v2/": net/http: TLS handshake timeout

**Comment by spkane** [comment]
I can not re-test this anymore, because I am no longer in the same environment, but I am hoping that others can test and confirm that this is fixed.

**Comment by colceagus** [comment]
this is still not fixed, on macos 12.3.1, running docker for mac 4.8.2.

**Comment by rumstead** [comment]
Same for me. On latest and still have to put in ip addresses/cidr ranges

**Comment by ctml91** [comment]
Still broken, it is unusable when interacting with anything not on my local machine. Last update made it even worse as it tries to refresh token from dockerhub when I login to a registry on local network... but that's not possible without proxy enabled, but then the internal registry cant be reached because it attempts to use proxy. Driving me crazy!

**Comment by pliurbc** [comment]
Still broken. Assuming you want to do `docker login repo.artifactory.some.com`, you will need to add the following values explicitly to the no_proxy list:

- `artifactory.some.com`
- `repo.artifactory.some.com`

This is just inconvenient for basically no reason, as far as I can tell. 

Optimally users should be able to set `*.some.com` in the no_proxy and be done with it.
