### ISSUE TITLE
Failed to start docker

### ISSUE THREAD

**Issue by fmq** [docker/for-mac#605]
This is a duplicate of https://github.com/docker/for-mac/issues/358, but I create this as a new issue since I updated both OS and Docker Beta version to latest release.

### Steps to reproduce

Install Docker Beta (25) on Mac OS Sierra
Open Docker app
Enter password for user to install privileged components

### Expected behavior

Docker should install itself and start running

### Actual behavior

Popup requesting password keeps appearing after I enter the correct password.

The following log is generated if ran from a command line:

```
fmq at tartarus in ~
$ /Applications/Docker.app/Contents/MacOS/Docker 
1473784666671393792 com.docker.docker Application version: 1.12.1-beta25 (11807)
1473784666671793920 com.docker.docker Administrator user: true
1473784666702755840 com.docker.docker OSX Version: Version 10.12 (Build 16A320)
kern.hv_support: 1
1473784666896069120 com.docker.docker migrator: start migration process
1473784666898182912 com.docker.docker migrator: previous install detected
1473784666898254848 com.docker.docker migrator: previous version is 1.12.1-beta25
1473784666898370048 com.docker.docker migrator: no migration needed, you are good to go!
1473784666898381824 com.docker.docker migrator: end of migration process
1473784666965399040 com.docker.docker event tracker initialized
1473784666966892032 com.docker.docker NSUserDefaults.synchronise() returned false
1473784666969143808 com.docker.docker NSUserDefaults.synchronise() returned false
1473784666969639936 com.docker.docker NSUserDefaults.synchronise() returned false
1473784666973359104 com.docker.docker NSUserDefaults.synchronise() returned false
1473784666973378048 com.docker.docker Bundle path: /Applications/Docker.app
1473784666995429888 com.docker.docker NSUserDefaults.synchronise() returned false
1473784667806297088 com.docker.docker NSUserDefaults.synchronise() returned false
1473784668621927936 com.docker.docker NSUserDefaults.synchronise() returned false
1473784669453123072 com.docker.docker NSUserDefaults.synchronise() returned false
1473784672653856000 com.docker.docker Failed to install networking components.
1473784672658637056 com.docker.docker NSUserDefaults.synchronise() returned false
1473784673463819008 com.docker.docker NSUserDefaults.synchronise() returned false
1473784674173635840 com.docker.docker applicationWillTerminate
fmq at tartarus in ~
$ 

```
Run the app as sudo to be able to generate diagnostics and here is the command line output:

```
$ sudo /Applications/Docker.app/Contents/MacOS/Docker 
Password:
1473784734814488832 com.docker.docker Application version: 1.12.1-beta25 (11807)
1473784734814818816 com.docker.docker Administrator user: true
1473784734844003840 com.docker.docker OSX Version: Version 10.12 (Build 16A320)
kern.hv_support: 1
1473784735037571072 com.docker.docker migrator: start migration process
1473784735038932992 com.docker.docker migrator: no previous version detected. This is a fresh install.
1473784735043180032 com.docker.docker NSUserDefaults.synchronise() returned false
1473784735043212800 com.docker.docker migrator: end of migration process
1473784735104528896 com.docker.docker NSUserDefaults.synchronise() returned false
1473784735104985088 com.docker.docker event tracker initialized
1473784735107065856 com.docker.docker NSUserDefaults.synchronise() returned false
1473784735109792000 com.docker.docker NSUserDefaults.synchronise() returned false
1473784735946424064 com.docker.docker NSUserDefaults.synchronise() returned false
1473784736756250880 com.docker.docker NSUserDefaults.synchronise() returned false
1473784737734583808 com.docker.docker NSUserDefaults.synchronise() returned false
1473784737741275904 com.docker.docker NSUserDefaults.synchronise() returned false
1473784737741317120 com.docker.docker Bundle path: /Applications/Docker.app
1473784737767683072 com.docker.docker Failed to install networking components.
1473784740502925824 com.docker.docker applicationWillTerminate
fmq at tartarus in ~
$ 
```
### Information

```
Diagnostic ID: 35C50EB4-C79B-40AC-B6E8-669511A8683F
Docker for Mac: 1.12.1-beta25 (Build 11807)
macOS: Version 10.12 (Build 16A320)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /var/root/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /var/root/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /var/root/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /var/root/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[ERROR]  moby
         /var/root/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by mchiang0610** [comment]
@fmq Thanks for reporting this. Possible for you to reset the app to factory defaults in settings? And let's troubleshoot it from there. I'll reopen this ticket after. 

Thanks!

**Comment by fmq** [comment]
@mchiang0610 Unfortunately it's not possible to reset to factory defaults from the menu since I can't get docker installed so the preferences menu never get's selectable.

If there is a way to reset this from the command line please let me know and I will do it asap. (I did remove ~/Library/Containers/com.docker.docker just in case)

I'm attaching screenshots (one with my user one with root) so you can see what I mean.

Regards
![screen shot 2016-09-14 at 12 08 56 am](https://cloud.githubusercontent.com/assets/881660/18498896/b85d9c30-7a10-11e6-9603-352f53e19ce4.png)
![screen shot 2016-09-14 at 12 09 25 am](https://cloud.githubusercontent.com/assets/881660/18498899/b9dae0ae-7a10-11e6-9bc3-4ee2cd981244.png)

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by fmq** [comment]
Hi @djs55, I updated to Docker Beta 26 and the error persists, I'm starting to believe it has something to do with my machine (or something of the sort).

Now I can't even upload a new issue (I will log a new issue with this), I'm attaching a screenshot of the diagnostics screen. 

Is there a way to manually uninstall everything that docker creates (besides the 2 or the? 

Let me know if there is a way I can help you diagnose this issue.

Thanks for the all the help..

regards

![screen shot 2016-09-15 at 4 01 26 pm](https://cloud.githubusercontent.com/assets/881660/18563599/a94697e8-7b5e-11e6-8c65-b4cba8c0cd91.png)

**Comment by djs55** [comment]
Thanks for the screenshot. I don't know why the diagnostics upload failed -- are you behind an HTTP proxy? There's a known issue where the `curl` upload fails to respect proxy settings.

The "Failed to install networking components" looks like the earliest failure. Are you still seeing the password prompt? Does it happen more than once? Could you verify your user/group settings? In particular check that the account you're authenticating with has admin access. Unfortunately the macOS API for installing privileged components (`SMJobBless`) isn't very helpful when there's a problem.

When the networking component installation succeeds there should be 3 side-effects:

1. the file `/Library/PrivilegedHelperTools/com.docker.vmnetd` should be created
2. the launchd service should be registered e.g.
```
$ sudo launchctl list | grep com.docker.vmnetd
33805	0	com.docker.vmnetd
```
3. the control socket should exist:
```
$ ls -l /var/tmp/com.docker.vmnetd.socket 
srw-rw-rw-  1 root  daemon  0 10 Sep 08:46 /var/tmp/com.docker.vmnetd.socket
```
I'd really like to understand why this isn't working.

If you'd like to experiment, it's possible to manually install the component using a sequence like:
```
sudo cp /Applications/Docker.app/Contents/Library/LaunchServices/com.docker.vmnetd /Library/PrivilegedHelperTools/
# Correct the permissions on the .plist to satisfy launchd
cp /Applications/Docker.app/Contents/Resources/com.docker.vmnetd.plist .
sudo chown root com.docker.vmnetd.plist 
sudo launchctl load com.docker.vmnetd.plist
```

It's possible to uninstall the component using:
```
sudo rm /Library/PrivilegedHelperTools/com.docker.vmnetd
sudo launchctl remove com.docker.vmnetd
```

Note there is another known issue which *might* be happening here, where a previous half-installation of the privileged component blocks or somehow prevents re-installation. The workaround for this is to `sudo rm  /Library/PrivilegedHelperTools/com.docker.vmnetd` and then run the app as normal.

**Comment by fmq** [comment]
@djs55 It's finally working..

The problem was that (I'm not sure why, probably something I touched) the launchd service was set to disabled, I noticed this when I installed the service manually:

```
$ sudo launchctl load com.docker.vmnetd.plist
/private/tmp/com.docker.vmnetd.plist: Service is disabled
fmq at tartarus in /tmp
$ sudo launchctl list | grep com.docker.vmnetd
fmq at tartarus in /tmp
$ sudo launchctl  load -w com.docker.vmnetd.plist
fmq at tartarus in /tmp
$ sudo launchctl list | grep com.docker.vmnetd
3732	0	com.docker.vmnetd
fmq at tartarus in /tmp
```
After this I re opened the app and everything seems to work.

Again, thanks for all the help, I will try and figure out why it got disabled in the first place, and I will continue testing your Betas.

Regards!
