### ISSUE TITLE
Docker paused will not resume after a while

### ISSUE THREAD

**Issue by jmaitrehenry** [docker/for-mac#6058]
- [x] I have tried with the latest version of Docker Desktop
  - [?] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2AC72C0C-F9FC-44D3-A6DA-E1D42B3DC250/20211123144429 and 2AC72C0C-F9FC-44D3-A6DA-E1D42B3DC250/20211122202700

### Expected behavior
Docker resume when I run a docker command or by clicking resume in the menu

### Actual behavior
Docker is paused:

```
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started

[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
```

### Information
  - macOS Version: 12.0.1 (21A559)
  - Intel chip or Apple chip: Apple M1 Pro
  - Docker Desktop Version: 4.2.0 (70708)

### Steps to reproduce the behavior

  1. Pause docker
  2. Put the Mac in sleep (closing the screen of the MBP)
  3. Run a docker compose command, docker info command, try to resume by clicking Resume on the dock icon

### Interesting finding in the logs:
```
 2021-11-22 15:09:54.675764-0500  localhost com.docker.driver.amd64-linux[10450]: Resuming vm, user agent is: Docker-Client/20.10.10 (darwin)
2021-11-22 15:09:54.677543-0500  localhost com.docker.driver.amd64-linux[10450]: (6e2a1d6d) d221324c-DriverCMD C->S BackendAPI POST /unpause
2021-11-22 15:09:54.679544-0500  localhost com.docker.backend[9569]: (6e2a1d6d) bf40619e-BackendAPI S<-C d221324c-DriverCMD POST /unpause[[STACK]]github.com/docker/pinata/common/pkg/backend.(*backendClient).Unpause(0x140000781f0)
	/Users/administrator/jenkins/workspace/op_desktop-build_master-merge_18/src/github.com/docker/pinata/common/pkg/backend/client.go:258 +0x60
github.com/docker/pinata/common/pkg/proxy.NewRouter.func2.1({0x102e69dd0, 0x140001b62a0}, 0x140000a0a00)
	/Users/administrator/jenkins/workspace/op_desktop-build_master-merge_18/src/github.com/docker/pinata/common/pkg/proxy/proxy.go:112 +0x3a4
github.com/docker/pinata/common/pkg/proxy.NewRouter.func1.1({0x102e69dd0, 0x140001b62a0}, 0x140000a0a00)
	/Users/administrator/jenkins/workspace/op_desktop-build_master-merge_18/src/github.com/docker/pinata/common/pkg/proxy/proxy.go:76 +0x184
github.com/docker/pinata/common/pkg/proxy.(*restrictions).Middleware.func1({0x102e69dd0, 0x140001b62a0}, 0x140000a0a00)
	/Users/administrator/jenkins/workspace/op_desktop-build_master-merge_18/src/github.com/doc<decode: missing data>
2021-11-22 15:09:54.679573-0500  localhost com.docker.backend[9569]: [...] ker/pinata/common/pkg/proxy/restrictions.go:74 +0x180
github.com/docker/pinata/common/pkg/proxy.(*GuiAnalytics).Middleware.func1({0x102e69dd0, 0x140001b62a0}, 0x140000a0a00)
	/Users/administrator/jenkins/workspace/op_desktop-build_master-merge_18/src/github.com/docker/pinata/common/pkg/proxy/analytics.go:62 +0xe0
github.com/gorilla/mux.(*Router).ServeHTTP(0x140001ec6c0, {0x102e69dd0, 0x140001b62a0}, 0x140000a0800)
	/Users/administrator/jenkins/workspace/op_desktop-build_master-merge_18/src/github.com/docker/pinata/vendor/github.com/gorilla/mux/mux.go:210 +0x1e4
2021-11-22 15:09:54.680238-0500  localhost com.docker.backend[9569]: (6e2a1d6d-1) e4b36909-PauseHDL C->S procd POST /unpause
2021-11-22 15:09:54.681068-0500  localhost com.docker.backend[9569]: (6e2a1d6d-1) e4b36909-PauseHDL C<-S NoResponse POST /unpause (809.583µs): Post "http://ipc/unpause": dial unix procd.sock: connect: connection refused
```

**Comment by StefanScherer** [comment]
Thanks for the report and for trying the new experimental feature. We're looking into it.

**Comment by SpadarShut** [comment]
Same issue with with Mac Intel chip.

**Comment by mat007** [comment]
We have now fixed this issue in Docker Desktop 4.4.2, thank you!

**Comment by ppastur** [comment]
> We have now fixed this issue in Docker Desktop 4.4.2, thank you!

I may have missed something but I have version Docker Desktop 4.4.2 (73305) and still have the problem.

**Comment by mat007** [comment]
@ppastur can you upload diagnostics so that we can have a look?

**Comment by ppastur** [comment]
Hi @mat007 , I just tried to reproduce the error (after it happened twice my morning) and it seems to be behaving.  Ill keep an eye on it and if it happens again ill grab diags and upload.

**Comment by SpadarShut** [comment]
I'm still having this issue in 4.4.2. Here's my diagnostics id 10DB2225-494C-4A4E-92BA-7106942338B3/20220119102459

**Comment by ebriney** [comment]
I can reproduce it, hope to do a fix!

**Comment by mvhayman-afs** [comment]
Also having this issue.  When selecting the restart option within docker desktop it goes into a loop.  Diagnosing also just seems to say 'Diagnosing...' for a long time so I can't give you a diagnostic id unfortunately.

**Comment by NReilingh** [comment]
I'm having this issue on Apple Silicon.

I think a compounding issue that needs fixing is that within the dashboard window, the interaction loop for clicking significant buttons like "restart and update" or "resume" has no immediate UI feedback. They seem to expect a command to return from the daemon or something before showing any visual feedback, and I suspect may even allow multiple commands to be dispatched asynchronously which can cause unexpected behavior. When a button like this is clicked, the UI needs to respond immediately by disabling further clicks of the button and showing a visual indicator that something is happening (or at least being attempted).

**Comment by owen-duncan-snobel** [comment]
Ya I am having this issue on Apple Silicon

**Comment by alexkingdom** [comment]
Same for me. MacBook Pro, Apple Silicon. The solution was for me just to use restart button and after this to click on resume and it worked.

Version of Docker Desktop: 4.5.0

**Comment by daniandl** [comment]
> Same for me. MacBook Pro, Apple Silicon. The solution was for me just to use restart button and after this to click on resume and it worked.
> 
> Version of Docker Desktop: 4.5.0

This is my temp fix too at the moment.
MacBook Pro, M1 Pro, Monterrey 12.2.1, Docker 4.5.0

**Comment by domarmstrong** [comment]
Still having this problem on MacBook pro intel 12.3, Docker 4.6.1.

I was in love with the pause button due to our heavy dev environment, so this no longer working makes me sad.

**Comment by mouhradBendjillali** [comment]
> Still having this problem on MacBook pro intel 12.3, Docker 4.6.1.
> 
> I was in love with the pause button due to our heavy dev environment, so this no longer working makes me sad.

M1 Pro macOS 12.3, Docker 4.6.1
exactly the same case :/ The "pause" button work fine but impossible to resume without restart Docker 😢

I'll try it again when this issue will be closed ^^

**Comment by AlexFate** [comment]
Same for me. (Apple Silicon M1). But resume button works fine, before my mac going to sleep. After mac os wake up resume button do nothing

**Comment by markkkkas** [comment]
> Same for me. (Apple Silicon M1). But resume button works fine, before my mac going to sleep. After mac os wake up resume button does nothing
> 
> Docker Desktop 4.6.1

Same! After hibernate mode, i tried to spam resume button several times - nothing, also found on internet that any docker cli command should unpause it - it just hangs.

**Comment by melnik0v-me** [comment]
Docker Desktop 4.7.0 - same thing
After some delay when docker has been paused it hangs in pause mode and never alive
only restarting docker helps

**Comment by cramhead** [comment]
Maybe the events request to change the state is blocked, as I can see there are some cases where the state of UI components is out of sync. 
On Docker Desktop version 4.7.0 (77141) with MacOS 12.3.1
<img width="555" alt="image" src="https://user-images.githubusercontent.com/386035/162999602-8287f437-9336-491e-8693-4fc3a629f2c7.png">

**Comment by skoczko** [comment]
Docker Desktop 4.7.1 using the "Experimental Features" on MBP with M1 MAX -- same thing. Once paused, after a while it cannot be resumed and requires a "restart". Quite annoying as I tend to pause often -- Docker is the most significant battery consumer on the laptop.

**Comment by NotTimIsReal** [comment]
I feel like this only happens with the new big Sur virtualisation framework experimental feature

**Comment by nightpool** [comment]
I am using a normal non-Silicon macbook with the Big Sur virtualization framework and having the same issue. Diagnostics ID:     412927C9-E4F3-4591-A8C9-69CDAF5EFD2F/20220509152219

**Comment by rogermilroy** [comment]
I also have this problem
No experimental features turned on, M1 Pro and version 4.7.0 - managed to kill my install trying to restart as it also would not restart.
Diagnostics ID: 24197558-9E80-4912-A983-0E8326EF863C/20220512094251

**Comment by NotTimIsReal** [comment]
yeah I don't think restart even works when this occurs

**Comment by adamwlarson** [comment]
I can confirm restart doesn't work either, I end up having to hard exit and relaunch docker to move past this. Version 4.8.0 - also on Apple M1

**Comment by bobross419** [comment]
Same issue, Docker 4.9.0 M1 Pro Monterrey

**Comment by barius** [comment]
And clicking restart when pause and resume not responding might lead to 2 docker icons in the task bar, each can open up an individual docker desktop window (that shares the same docker backend).
Mac Monterey 12.4, docker desktop 4.9.0, m1 max macbook.

**Comment by dpr-0** [comment]
Same issue, Docker 4.9.1 (81317) on M1 Max MacBook Pro w/latest Monterey OS

**Comment by akshaypawar123** [comment]
Wow.. a core functionality is broken for over 7 months now. Please help.

**Comment by arkbriar** [comment]
Hi folks, I'm facing the same issue. Are there any updates?

Env:
  + Docker 4.9.1 (81317)
  + M1 Pro MacBook Pro / Monterrey
  + Big Sur virtualization framework

**Comment by andaden** [comment]
Hi folks, I also have this problem.
- M1 Pro / Monterrey 12.4 (21F79)
- Docker 4.9.1 (81317)

**Comment by ellthompson** [comment]
Hi, same issue here.

- MacOS Monterey 12.4 (21F79)
- M1 Max
- Docker Desktop 4.9.1 (81317)
- No experimental features

**Comment by SamCritch** [comment]
Same issue here:

- Mac OS Monterey 12.4
- M1 Max
- Docker Desktop 4.8.2 (79419)

**Comment by ch1seL** [comment]
Same issue here:

Mac OS Monterey 12.5
M1 Max
Docker Desktop 4.10.1 (82475)

**Comment by zurez** [comment]
Same issue here:

Mac OS Monterey 12.2.1
M1 Pro (10 core / 32 Gigs)
Docker Desktop 4.10.1 (82475)

**Comment by barius** [comment]
For a workaround, I'm now using a Linux VM running Docker inside in macOS. The VM can be paused to save battery and resumed even across mac reboots. No supports for x86 images though.

**Comment by Radiergummi** [comment]
Same issue on an Intel Mac. I can't get it back to live, even after hard-quitting Docker and starting it again. It still says "Paused", and nothing helps. My last resort is rebooting the entire machine... Why is the feature not even marked as experimental anymore if it clearly doesn't work for lots of people?

**Comment by efstathiosntonas** [comment]
@Radiergummi  no need to restart the machine, open Activity Monitor and after tapping the kill button (X) select Force Quit.

![Screenshot at Aug 10 15-03-04](https://user-images.githubusercontent.com/717975/183896455-7b092af3-9609-4ecb-be65-d44c330761eb.png)


other than that, totally agree with you.

**Comment by Radiergummi** [comment]
> @Radiergummi  no need to restart the machine, open Activity Monitor and after tapping the kill button (X) select Force Quit.
> 
> 
> 
> ![Screenshot at Aug 10 15-03-04](https://user-images.githubusercontent.com/717975/183896455-7b092af3-9609-4ecb-be65-d44c330761eb.png)
> 
> 
> 
> 
> 
> other than that, totally agree with you.

I did that actually, but after starting Docker again it would be stuck in paused mode, unresponsive, the Daemon not talking.

A reboot fixed it.

**Comment by hambone01** [comment]
Same issue apple M1. I had to kill DD twice to get it out of pause.

**Comment by realies** [comment]
randomly stumbled upon this issue, and can report that pausing, sleeping (closing laptop), and resuming (10 hours later) appears to be working on a m1max/Monterey 12.5.1/Docker Desktop 4.11.1 (84025)

**Comment by lprimak** [comment]
> sleeping (closing laptop), and resuming (10 hours later) 
@realies that is not the issue described in this issue.
This issue deals with docker pause from the mac context menu, not sleeping the whole laptop

**Comment by realies** [comment]
@lprimak I mean the issue described here + sleeping the laptop. Sleeping Docker Desktop, sleeping the laptop, waking up the laptop, and resuming Docker Desktop. I think the resuming keyword I used above made it clear, but here's a more verbose confirmation.

**Comment by lprimak** [comment]
@realies cool just want to clarify if there is any confusion thanks!

**Comment by MahatmaFatalError** [comment]
Issue still existing in M1 macOS 12.5.1 and and docker desktop 4.11.1 (84025) with engine 20.10.17

**Comment by realies** [comment]
> Issue still existing in M1 macOS 12.5.1 and and docker desktop 4.11.1 (84025) with engine 20.10.17

how to replicate?

**Comment by realies** [comment]
> > Issue still existing in M1 macOS 12.5.1 and and docker desktop 4.11.1 (84025) with engine 20.10.17
> 
> how to replicate?

Ok, just happened for me too. Not sure what was different than last pause/resume, although the terminal that was open said this for all compose services:
```
dial unix docker.raw.sock: connect: no such file or directory
```

Trying to resume Docker Desktop does nothing.

**Comment by z4nr34l** [comment]
Same issue happened to me few times already.

- M1 Pro
- macOS 12.6
- docker desktop 4.12.0 (85629) w/ engine 20.10.17

Diagnostics ID: `3FC9E43B-C291-41CB-95BB-16F64F95F918/20220921063956`

**Comment by omertoast** [comment]
Still have this problem
M1 Air
4.11.1
MacOs 12.6

**Comment by lprimak** [comment]
Does anyone has this problem with 4.14.1? So far it's lasted for 2 days... Maybe...??? fixed?

**Comment by realies** [comment]
> Does anyone has this problem with 4.14.1? So far it's lasted for 2 days... Maybe...??? fixed?

Possibly fixed, it survived a couple of sleeps here too.

**Comment by keann** [comment]
- M1 Air
- macOS 13.0.1
- Docker desktop 4.15.0 (93002)
- Docker 20.10.21

same issue here

**Comment by lprimak** [comment]
Broke again in docker 4.15 as well

**Comment by Sangeppato** [comment]
Same here, worked fine in 4.14 but broke with 4.15

**Comment by mootari** [comment]
I'm running into the same issue with Docker Desktop 4.15.0 (93002) on macOS 12.6 which also prevents me from quitting Docker Desktop. Note that this might only happen when Docker was paused during standby.

When it happens I see the following repeated over and over again in Console:
```
unable to inject 4 events for 3h5m0.000302581s
```
and repeated attempts to query `/unpause` and `/ping`.

**Comment by montanaflynn** [comment]
Same issue for me

**Comment by bgovindarajan** [comment]
Same issue. Version 4.15.0 (93002).
Once it goes into this mode, restarting gives this error: failed to run backend processes

**Comment by wmitsuda** [comment]
Same with latest docker desktop, mac os, intel.

**Comment by emulgeator** [comment]
Same here

**Comment by lzx404243** [comment]
same here...
OS: macOS Monterey 12.6.1
docker: 4.14.0

**Comment by yohoho-ua** [comment]
It got worse - after force-quitting, you can't start dockerApp again. You need to reboot the OS.
OS: macOS Ventura 13.0.1
docker: 4.15.0

**Comment by montanaflynn** [comment]
> It got worse - after force-quitting, you can't start dockerApp again. You need to reboot the OS. OS: macOS Ventura 13.0.1 docker: 4.15.0

Yeah docker > 4.12 is completely unusable, the only thing that could let me continue work is downgrading to 4.12 which you can find download links to here:

https://docs.docker.com/desktop/release-notes/#4120

**Comment by bekharsky** [comment]
Same here:
Apple M2 24 GB
Docker 4.15.0 (93002)
macOS 13.1 (22C65)

**Comment by laggage** [comment]
Same problem

2.3 GHz 8-Core Intel Core i9
macOS 13.1 (22C65)
Docker 4.15.0 (93002)

**Comment by Sangeppato** [comment]
Possibly fixed in 4.16, it behaved normally so far..

**Comment by BretFisher** [comment]
Same issue. Mine has happened for well over six months on M1 Pro with macOS 13.1, 13.0, and 12.x.

Two ways it doesn't wake up:
- When the computer sleeps, and I come back later. This happens less than 50% of the time.
- When I pause DD and come back later. This happens 100% of the time to the point I no longer use DD sleep (though I love the idea). It may be because the mac went to sleep; I'll have to pay more attention to that.

This has happened in every DD version since pause was added, and a DD reset doesn't help.

Diagnostics ID 93D7D68F-14B0-4AD0-86C7-3F4473A9C98B/20230120183017

**Comment by Sangeppato** [comment]
That's weird, for me the issue consistently presented itself up until version 4.15 (with the exception of 4.14) but now with version 4.16 I've never encountered it.. I've reset the VM when updating though, could this explain it?

**Comment by BretFisher** [comment]
Did a reset Friday on 4.16.1, then paused it. Plot twist, on Saturday I had now two Docker icons showing somehow on the menubar, both unresponsive, so had to kill it all in Activity Monitor.
![Xnapper-2023-01-22-15 19 54](https://user-images.githubusercontent.com/792287/213938413-a9df6c1f-fd01-464c-a919-d2007e8acf2b.jpg)

**Comment by yingshaoxo** [comment]
> Did a reset Friday on 4.16.1, then paused it. Plot twist, on Saturday I had now two Docker icons showing somehow on the menubar, both unresponsive, so had to kill it all in Activity Monitor. ![Xnapper-2023-01-22-15 19 54](https://user-images.githubusercontent.com/792287/213938413-a9df6c1f-fd01-464c-a919-d2007e8acf2b.jpg)

I think there has a simple solution, in the `Activity Monitor`, kill all docker process, then open the `docker desktop` again, everything should work fine.

**Comment by BretFisher** [comment]
Sorry, no. Read the history. This isn't a one-time issue. The double Docker Desktop was a one-off though.

**Comment by Sangeppato** [comment]
FWIW, I still haven't been able to reproduce on my M1 (DD has been running pretty much since 4.16 came out)

**Comment by eosmantis** [comment]
The issue (Docker paused and will not resume) is still reproducible Version in Docker Desktop Version 4.16.2 (95914) on MacOS Ventura 13.0

**Comment by eosmantis** [comment]
Error-Message: "Unable to calculate image disk size"  (but not visible by using the mini-menu)

**Comment by lprimak** [comment]
Maybe fixed again?
Surviving through multiple pauses for 3 days now... fingers crossed!
version 4.17.0 (99724)

**Comment by alishaevn** [comment]
Apple Macbook Pro 2020
Docker 4.15.0 (93002)
macOS 13.2.1

I paused docker last night. Upon waking the OS from sleep this morning, I was unable to get Docker to resume by pressing "resume" from the Docker icon drop down nor the Docker dashboard. Running a docker command from the terminal hung without any messages. Restarting Docker didn't do anything, so I tried restarting a second time. The second time....it froze me out from any options from the icon drop down at all. The Docker app icon still showed the containers going up and down as though something was happening, but nothing appeared to be.

Force closing Docker from Activity Monitor and then restarting the app is what eventually worked.

**Comment by infoman** [comment]
I'm having the opposite problem, I pause the engine and after a while it silently un-pauses itself without any commands or other obvious interaction

**Comment by lprimak** [comment]
Yup. Me too. Latest update broke pause on the opposite way

**Comment by NotTimIsReal** [comment]
Yeah it also unpauses for me randomly

**Comment by AShuba** [comment]
Still repriducible. Cant resume Docker Desktop after 3 days pause.

Docker Desktop 4.19.0 (106363)
Ubuntu 22.04.2 LTS
11th Gen Intel® Core™ i7-11850H @ 2.50GHz × 16
64.0 GGB RAM
58GB free space on disk

**Comment by simonberger** [comment]
I also have the problem of auto resuming docker engine which is annoying, especially when using in battery mode and not needing docker for a while.
Auto resuming is not just rarely happening but at least after like 15-30min so I end up having it not paused a long time which hurts battery runtime a lot. I couldn't yet really find out why this is happening. In logs could just see the same of the initial posting

```
standard	17:03:24.311490+0200	com.docker.backend	HTTP 82 CONNECT desktop.docker.com:443: with direct connection
standard	17:03:24.311490+0200	com.docker.backend	HTTP 83 CONNECT desktop.docker.com:443: with direct connection
standard	17:03:24.311500+0200	com.docker.backend	HTTP 84 CONNECT desktop.docker.com:443: with direct connection
standard	17:03:24.312158+0200	com.docker.backend	HTTP 85 CONNECT desktop.docker.com:443: with direct connection
standard	17:03:24.473253+0200	com.docker.backend	HTTP 84 CONNECT desktop.docker.com:443: 200 OK
standard	17:03:24.473423+0200	com.docker.backend	HTTP 84 CONNECT desktop.docker.com:443: proxying to desktop.docker.com:443
standard	17:03:24.513351+0200	com.docker.backend	HTTP 85 CONNECT desktop.docker.com:443: 200 OK
standard	17:03:24.513566+0200	com.docker.backend	HTTP 85 CONNECT desktop.docker.com:443: proxying to desktop.docker.com:443
standard	17:03:24.543088+0200	com.docker.backend	HTTP 82 CONNECT desktop.docker.com:443: 200 OK
standard	17:03:24.543078+0200	com.docker.backend	HTTP 83 CONNECT desktop.docker.com:443: 200 OK
standard	17:03:24.543257+0200	com.docker.backend	HTTP 82 CONNECT desktop.docker.com:443: proxying to desktop.docker.com:443
standard	17:03:24.543312+0200	com.docker.backend	HTTP 83 CONNECT desktop.docker.com:443: proxying to desktop.docker.com:443
standard	17:03:24.799576+0200	com.docker.backend	HTTP 83 CONNECT desktop.docker.com:443: successful (7 active requests)
standard	17:03:24.827802+0200	com.docker.backend	HTTP 82 CONNECT desktop.docker.com:443: successful (6 active requests)
standard	17:03:25.378329+0200	com.docker.backend	dropping ICMP 77.220.243.252 -> VM type 1 *icmp.DstUnreach
standard	17:03:25.378453+0200	com.docker.backend	dropping ICMP 77.220.243.252 -> VM type 1 *icmp.DstUnreach
standard	17:03:25.378530+0200	com.docker.backend	dropping ICMP 77.220.243.252 -> VM type 1 *icmp.DstUnreach
standard	17:03:25.496726+0200	com.docker.backend	dropping ICMP 77.220.243.252 -> VM type 1 *icmp.DstUnreach
standard	17:03:25.598625+0200	com.docker.backend	Resuming vm, user agent is: Go-http-client/1.1
standard	17:03:25.598804+0200	com.docker.backend	(2c0504e6) 040f623e-DriverCMD C->S BackendAPI POST /unpause
standard	17:03:25.599596+0200	com.docker.backend	(2c0504e6) d7f45bfe-BackendAPI S<-C 040f623e-DriverCMD POST /unpause
standard	17:03:25.618005+0200	com.docker.backend	(2c0504e6-1) 3f4fe8e5-PauseHDL C->S procd POST /unpause
standard	17:03:25.624882+0200	com.docker.backend	3f4fe8e5-PauseHDL /pause/events <-- [2023-05-31T17:03:25.654382339+02:00] (17eb0198) pause resuming : Docker Desktop is resuming...
standard	17:03:25.769934+0200	com.docker.backend	error copying: write unix <HOME>/Library/Containers/com.docker.docker/Data/lifecycle-server.sock->: write: broken pipe
standard	17:03:25.770113+0200	com.docker.backend	error copying: write unix <HOME>/Library/Containers/com.docker.docker/Data/lifecycle-server.sock->: write: broken pipe
standard	17:03:25.770320+0200	com.docker.backend	error copying: write unix <HOME>/Library/Containers/com.docker.docker/Data/lifecycle-server.sock->: write: broken pipe
standard	17:03:25.771280+0200	com.docker.backend	(cca3d18a) b85ec40c-VMDiskUsageClient C<-S 1e305d46-VMDockerdAPI GET /vm/disk-usage (4m19.123526841s): {"availableBytes":15685668864,"totalBytes":101129359360,"usedBytes":80273006592}
standard	17:03:25.771462+0200	com.docker.backend	(205efe8c) b85ec40c-VMDiskUsageClient C->S VMDockerdAPI GET /vm/disk-usage
```

**Comment by ravi-rafay** [comment]
Still facing this issue on docker desktop for mac v4.30.0

**Comment by hoschi** [comment]
I have also the problem that DD doesn't resume.

**Comment by lprimak** [comment]
I think this has been fixed now
