### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by oursland** [docker/for-mac#6071]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Continue operating software that worked in Docker Desktop for Mac v4.2.0

### Actual behavior

Several systems failed with errors indicating "too many open files".

### Information

  - macOS Version: 12.0.1 Monterey
  - Intel chip or Apple chip: Intel 
  - Docker Desktop Version: 4.3.0

### Steps to reproduce the behavior

This error was present with my use of node application with file watching as well as through kubernetes tooling (i.e. prometheus).

The error was resolved by rolling back to v4.2.0.

**Comment by StefanScherer** [comment]
Thanks for the report. Do you have more precise repro steps, maybe a sample project on GitHub or compose file etc. to reproduce the problem? We haven't seen this error in our CI.

**Comment by mat007** [comment]
Could you upload diagnostics, please? See https://docs.docker.com/desktop/mac/troubleshoot/#diagnose-and-feedback

**Comment by djs55** [comment]
Just in case the diagnostics fails (because of too many open files), could you try
```
lsof -Pn
```
This should list all the open files making it easier to spot where the leak is.

**Comment by yunussandikci** [comment]
I am having the same issue with M1 CPUs when I create a Kind cluster with about 40 pods.

**Comment by oursland** [comment]
I encounter this issue when deploying a k3d cluster with a similar number of pods including a live-reloading NodeJS application with many open files.

Again, this issue is not present in previous releases.  I believe it to be a misconfiguration of the VM's Linux kernel.

**Comment by sbueringer** [comment]
Just fyi, looks like we have the same issue when running kind and a few more containers.  (https://github.com/kubernetes-sigs/cluster-api/issues/5940).

@killianmuldoon posted a workaround on our issue: https://github.com/kubernetes-sigs/cluster-api/issues/5940#issuecomment-1013300053

**Comment by dims** [comment]
cc @thaJeztah

**Comment by StefanScherer** [comment]
We've released Docker Desktop 4.5.0 which fixes this issue.

**Comment by killianmuldoon** [comment]
Thanks @StefanScherer this is working for me 😄

**Comment by moisesrodriguez** [comment]
I still have the issue with 4.5.0, I get bunch of `Error: EIO: i/o error, open` errors and eventually too many open files error. I too have file watching for my node app. Reverted to 4.2.0
