### ISSUE TITLE
High CPU usage (~100%) while not running any containers, host=MacOS, new issue in version=4.5.0

### ISSUE THREAD

**Issue by pvarga-dni** [docker/for-mac#6166]
For a **WORKAROUND**: see [comment 1047792776](#issuecomment-1047792776)

---

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics IDs:
    - `754E1C8B-3C1D-4587-AFB8-66045B522EFB/20220219174509`
    - `5862CFC3-F131-44DC-8DE4-9D6AD3BD856F/20220223103231`
    - `B8FCFB38-E655-48C7-8608-3E25D5E3D479/20220221142933` from @twiny [below](#issuecomment-1044597397)

### Expected behavior

Low CPU usage while Docker is inactive.

### Actual behavior

After upgrading to 4.5.0, there is high CPU usage even while not running any containers and not having the Dashboard open. The previous version (4.4.2) didn't exhibit this issue.

`top`:
<img width="567" alt="Screen Shot 2022-02-23 at 11 02 06 am" src="https://user-images.githubusercontent.com/58729567/155306994-2d59bd54-ba24-4b1f-9c15-2e4cc3cdc256.png">

### Information

  - macOS Version: 12.2.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.5.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[042:00:52:25.622][I] i<USER>c.NewClient: a77efb5f-diagnose-network -> Library/Containers/com.docker.docker/Data/diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xdd
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x4d4ccc0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x4d4ccc0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x4d4ccc0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x4d4ccc0, 0xc000579828)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000203000, 0xc000579828)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x46bdf00, 0xc00035f968)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x4d4cb40, 0x45f994f, {0xc00035faf8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc000032050, 0x6, 0x4}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x296
[042:00:52:25.622][I] (13ec3b77) a77efb5f-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"i<USER>s":["192.168.1.237"]}
[042:00:52:26.126][E] (13ec3b77) a77efb5f-diagnose-network C<-S a08d6a05-diagnosticsd POST /check-network-connectivity (504.192436ms): failed to <USER>ing host: exit status 1
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:35 +0x15b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x4d4ccc0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x4d4ccc0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x4d4ccc0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x4d4ccc0, 0xc000579828)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000203000, 0xc000579828)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x46bdf00, 0xc00035f968)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x4d4cb40, 0x45f994f, {0xc00035faf8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc000032050, 0x6, 0x4}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x296

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.
```
(The VM actually has network access working fine)

### Steps to reproduce the behavior

  1. Start Docker Desktop 4.5.0 for Mac
  2. Close the Dashboard window if it automatically opens
  3. Observe high CPU usage of the `Docker` process

**Comment by kszafran** [comment]
I just updated to 4.5.0 and faced the same issue (~100% CPU usage with no containers).

I went into "Troubleshoot" > Clean / Purge data. Didn't seem to help. So I quit Docker Desktop. Then I tried running `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check` as in the opening post, realized it needs Docker to be running, so I ^C a bunch of times, started Docker Desktop... and it's not using ~100% CPU anymore. I'll post again if the problem reoccurs.

**Comment by philippefutureboy** [comment]
Experiencing similar issues.

**Configuration:**

macOS Big Sur (11.6)
MacBook Pro 16-inch 2019
Processor: 2.4 GHz 8-Core Intel Core i9
Memory: 32 GB 2667 MHz DDR4

Docker Desktop version: 4.4.2

**Description:**

- Docker Desktop takes ~98-99% of a CPU (stable). At restart, takes up to 400% CPU for ~1-2min with spikes lasting 15 sec at a time

Not sure if related:

- com.docker.hyperkit takes 100% of the allocated RAM, even if not running any container (in my case I tested at 15GB, 20GB). 
- com.docker.hyperkit exceeds 100% of the allocated RAM sometimes after wakeup from sleep (experienced 31GB in use by the process, everything slowed down to a crawl). Had zombie container that I had to stop manually (Postgres 11).

**Comment by pvarga-dni** [comment]
@kszafran For me the issue reoccurs reliably. High CPU usage doesn't always start immediately after starting up Docker Desktop but eventually it always comes, within a few minutes.

**Comment by kszafran** [comment]
Today it happened again. Quitting Docker Desktop and opening it again seems to have helped. It's been some time, and the usage has not spiked back up to 100%.

For reference:
OS: macOS Monterey (12.2)
Processor: 2,8 GHz Quad-Core Intel Core i7
Memory: 16 GB 1600 MHz DDR3

**Comment by twiny** [comment]
Having same issue. 100%  CPU usage - no container running. Quitting & opening it again seems to have helped.

```
MacBook Pro
CPU: 2,3 GHz Dual-Core Intel Core i5
RAM: 8 GB 
```

**Comment by darrylmorley** [comment]
Same issue here Docker Desktop 4.5.0 (74594)

**Comment by fredericdalleau** [comment]
We are investigating this issue.
Could you upload diagnostic informations when this occurs ? You can refer to : https://docs.docker.com/desktop/mac/troubleshoot/
There is also the possibility to diagnostic from the command line if the UI fails to start.
Thanks

**Comment by hermawanramadhan** [comment]
same issue... 

version Docker Desktop 4.5.0 
macOS Big Sur 11.6.4
CPU usage always 100 % even if new install.

here no issue with Docker 4.4.2

Macbook pro retina 13, 2013 late. intel core i5 8GB RAM

**Comment by rogerclan** [comment]
Same Issues.  Started after the upgrade from 4.4.2 to 4.5.0.

Configuration:
macOS Monterey 12.2.1
MacBook Pro 16-inch 2019
Processor: 2.3 GHz 8-Core Intel Core i9
Memory: 16 GB 2667 MHz DDR4

Docker Desktop version: 4.5.0

I uninstalled and reinstalled with same issue.  Then I uninstalled and installed 4.4.2 and all issues went away.

**Comment by pvarga-dni** [comment]
@fredericdalleau
> We are investigating this issue. Could you upload diagnostic informations when this occurs ? 

Diagnostics ID: `754E1C8B-3C1D-4587-AFB8-66045B522EFB/20220219174509`

**Comment by fate8383** [comment]
> I noticed after adjusting the setting (increasing resource) - it seems to fix it. <img alt="Screen Shot 2022-02-18 at 3 13 34 PM" width="526" src="https://user-images.githubusercontent.com/59224605/154698671-0fc8cbd4-c0fe-4a81-8a26-a63afe87f206.png">
> 
> any body can confirm

life saver, yes this fixed it for me like instantly. So defaults are not good enough.

**Comment by rogerclan** [comment]
> Diagnostic id
FB1C59AD-7D24-46FD-9C7A-E81392E9C887/20220221114833

**Comment by p1-0tr** [comment]
hi, we are still investigating a proper fix, but the issue can be worked around by unchecking "Open Docker Dashboard at startup" in general settings.
![high-cpu-wa-settings](https://user-images.githubusercontent.com/6625761/155140611-a65e69a8-43d3-4d0d-b136-d8165c648aee.jpg)
Or by setting `"openUIOnStartupDisabled": true` in `~/Library/Group Containers/group.com.docker/settings.json`.

**Comment by fate8383** [comment]
> hi, we are still investigating a proper fix, but the issue can be worked around by unchecking "Open Docker Dashboard at startup" in general settings.
> ![high-cpu-wa-settings](https://user-images.githubusercontent.com/6625761/155140611-a65e69a8-43d3-4d0d-b136-d8165c648aee.jpg)
> Or by setting `"openUIOnStartupDisabled": true` in `~/Library/Group Containers/group.com.docker/settings.json`.

it was never enabled/checked for me at the first place. I am not sure how this can be a workaround.

**Comment by p1-0tr** [comment]
@fate8383 - that's interesting, would it be possible for you to create a diagnostic?

**Comment by fate8383** [comment]
> @fate8383 - that's interesting, would it be possible for you to create a diagnostic?

My workaround was also mentioned above posts: increasing default CPU from 2 to 3 and swap from 1 to 2. It is working fine now. I am not going to roll back and get the diagnostics, it was above 200% plus cpu before my workaround applied, docker dashboard on startup was never enabled. Now I am on 10%.

**Comment by rogerclan** [comment]
So I have an i9 in my mac and had 8 of my 16 "CPU" with double your memory and swap and was still having issues.  I went through and clicked through the purge/clean data and reset factory default for a third time and it seems now to have fixed itself.  I had previously gone as far as  uninstall, reboot and reinstall and was still having issues.  I never had Open Dashboard on Startup checked.  I don't know what was causing it but it currently is working as normal.

**Comment by pvarga-dni** [comment]
I have changed a couple of settings around, no idea what solved it but can no longer reproduce this issue. Didn't update or downgrade Docker Desktop, still running 4.5.0. Also, I have the "Open Dashboard at startup" setting checked, still, yet the issue is gone.

**Comment by p1-0tr** [comment]
> There might be multiple unrelated issues with high CPU usage, for me it was the "Docker" process (I guess that's the Dashboard UI) taking 100% CPU, that is, fully utilizing one core. The hyperkit process had normal, very low CPU usage.

Yes, seeing the most recent comments, it's safe to say that other issues than the reported one are being signalled in the comments. The original issue boils down to a condition in which a receive routine started on behalf of the `Docker` process starts spinning. The issue is not a 100% reproducible, and we are still working to pin down the root cause. However, it would definitely not lead to using up more than one core, so e.g. usage of 200% CPU points to something else (especially if it's not the `Docker` process that's using up cycles). If increasing the VM's resource allocation helps, that points to the VM being busy, most likely running containers (e.g. operating close to or over its RAM allocation, which would lead to significant swapping). Another thing that can lead to significant CPU usage across our processes is sharing a large amount of files with a container(s), especially if the shared files are frequently updated.

**Comment by pvarga-dni** [comment]
@fredericdalleau @p1-0tr 
Spoke too soon.. now I get the issue again, uploaded another Diagnostics run: `5862CFC3-F131-44DC-8DE4-9D6AD3BD856F/20220223103231`
This is from a different box than the previous one, this one running MacOS 12.2.1

**Comment by p1-0tr** [comment]
@pvarga-dni - Could you try the workaround I suggested?

**Comment by kelp404** [comment]
I have the same issue.
<img width="1272" alt="截圖 2022-02-25 下午3 19 59" src="https://user-images.githubusercontent.com/1680868/155672111-309b6fd0-ef75-4d13-81c9-406f24418eba.png">

**Comment by jameshfisher** [comment]
Increasing resources (all of them) did nothing for me, but the "Open Docker Dashboard at startup" workaround does fix the issue. Perhaps there are two separate bugs being discussed here.

Note that disabling "Open Docker Dashboard at startup" does not disable the Dashboard, and opening the Dashboard after startup does not cause the 100% CPU issue. So it seems to just be a bug with the "open on startup" logic.

**Comment by kgrandly** [comment]
> hi, we are still investigating a proper fix, but the issue can be worked around by unchecking "Open Docker Dashboard at startup" in general settings. ![high-cpu-wa-settings](https://user-images.githubusercontent.com/6625761/155140611-a65e69a8-43d3-4d0d-b136-d8165c648aee.jpg) Or by setting `"openUIOnStartupDisabled": true` in `~/Library/Group Containers/group.com.docker/settings.json`.

✅ Thank you. It really works!

**Comment by nx-josepcrespo** [comment]
Docker update = Docker break

**Comment by imjimcap** [comment]
I am using version 4.6.1 on a MacBook Air 2020 (Intel), tried on both 10.15.7 and 12.3.1.  I never got to run any containers except docker/getting-started.  I uninstalled Docker before upgrading macOS, I didn't manually delete anything.  I'm new with Docker.

The work around [comment 1047792776](https://github.com/docker/for-mac/issues/6166#issuecomment-1047792776) had no effect for me, nor did enabling/disabling various options in the Preferences, I deleted all the bind mounts, for example.

Then, I followed @kszafran 's suggestion exactly, and the issue is gone.  This included pressing Ctrl+C manically after letting it run for a bit while the Docker GUI was not running, seeing all the errors "oh docker isn't running what are you doing." I started docker/getting-started:latest , and the problem still seems gone! 🤞 [1036229371](https://github.com/docker/for-mac/issues/6166#issuecomment-1036229371). I'm afraid to reboot.

I didn't notice the issue on my iMac 27 2020 (Intel), running macOS 12.3.1, but perhaps it was there.  

I do have a time machine backup of Catalina, I'm willing to roll-back later if anybody is curious for testing; I don't actually work on this MacBook Air, I just wanted to see how well it ran on light-weight hardware (I'm new here).  

Not sure how to help from here, let me know.

**Comment by bzamecnik** [comment]
Same problem with Docker 4.6.1 on MacOS Catalina. `"openUIOnStartupDisabled": true` helped.

Here's a sample using Activity Monitor when Docker was eating the whole CPU:
[Docker_4.6.1_high_cpu_usage_sample.txt](https://github.com/docker/for-mac/files/8406904/Docker_4.6.1_high_cpu_usage_sample.txt)

**Comment by kedramon** [comment]
Uncheck **Open Docker Dashboard at startup** helped! Have no idea how it was related. Also changed resources size a bit. But until uncheck and restart, nothing helped.

Docker 4.6.1, Monterey 12.3.1, MacBook Air (2018)

**Comment by caokhang91** [comment]
Same issue on MacOS 12.3 Intel Chip. Fixed with configuration
Uncheck "Open Docker Dashboard on startup"

![Snip20220411_1](https://user-images.githubusercontent.com/1905093/162673675-0aa7b774-86fd-4708-b44c-365ae017ba6f.png)
![Snip20220411_2](https://user-images.githubusercontent.com/1905093/162673694-3ec11dfa-530f-45c4-8a2e-2aab81ee2e6c.png)

**Comment by djs55** [comment]
Although we've still not figured out the root cause, I found some suspicious code in the "Open Docker Desktop at startup" codepath. I've fixed the problems I found (which I think could cause undefined behaviour) but I don't know if it fixes this issue or not, because I can't reproduce it. If anyone would like to try an experimental build, here it is:

- [Apple Silicon](https://desktop-stage.docker.com/mac/main/arm64/77619/Docker.dmg)
- [Intel](https://desktop-stage.docker.com/mac/main/amd64/77619/Docker.dmg)

Note that neither of these builds are notarized so you'll be prompted to explicitly Open them via Finder.

If it still reproduces, could you upload a fresh diagnostics and let me know the ID?

**Comment by bmedicke** [comment]
> * Intel

This fixed the issue for me. I have not tested if a regular reinstall had done the same, though.

**Comment by ddfreiling** [comment]
Incredibly @caokhang91 solution helped me as well. Simply turned off "Open Docker Desktop on Startup" on my Intel MacBook.

**Comment by leberman** [comment]
the issue for me was fixed by turning off "Open Docker Dashboard at startup" in ubuntu 21.04

**Comment by shinuza** [comment]
Same issue here on a 2017 MacBook Pro ( 2,3 GHz Dual-Core Intel Core i5, 8Gb )

How "I fixed it":

I increased the CPU from 2 to 3 cores and  memory from 4gb to 6gb and upgraded to v4.10.1. CPU went from 99% to 3% with 3 containers running.

**Comment by hotrush** [comment]
Wake me up in year 3000 and ask what's going on with docker on mac - I'll answer it still have issue with cpu usage (same with fs)

**Comment by QETHAN** [comment]
> hi, we are still investigating a proper fix, but the issue can be worked around by unchecking "Open Docker Dashboard at startup" in general settings. ![high-cpu-wa-settings](https://user-images.githubusercontent.com/6625761/155140611-a65e69a8-43d3-4d0d-b136-d8165c648aee.jpg) Or by setting `"openUIOnStartupDisabled": true` in `~/Library/Group Containers/group.com.docker/settings.json`.

Thanks. This works for me!
