### ISSUE TITLE
Dock icon missing

### ISSUE THREAD

**Issue by bschuhmann** [docker/for-mac#6173]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 47F5A49A-A85A-4D86-9086-F28F33CF237B/20220216194806

### Expected behavior
Docker icon instead of default icon should be displayed in dock when Docker Desktop is running.

### Actual behavior
Default icon is displayed in dock instead of the expected Docker icon when Docker Desktop is running.
### Information

  - macOS Version: 12.2.1
  - Intel chip or Apple chip: M1 Pro
  - Docker Desktop Version: 4.5.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.
### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Show dock

**Comment by jnous-5** [comment]
Confirmed it's also happening on my end after upgrading to `v4.5.0`. What's odd though is that, the icon is displaying correctly on my main display (mac). When I move it to my external display, that's where the issue comes in.

**Comment by nmarley** [comment]
I also don't have the regular dock icon after upgrading to 4.5.0 (74594). I have a generic OSX canvas icon with a pencil and paintbrush at the bottom.

```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

This is the icon I have instead:

<img width="78" alt="docker-desktop" src="https://user-images.githubusercontent.com/1735354/154763975-121ae9d2-2dc8-4f6a-b43a-2e6d45699dd1.png">

**Comment by miklof63** [comment]
I also see same as noted previously: https://github.com/docker/for-mac/issues/6173#issuecomment-1045212174
Mac OS 10.15.7 (19H1615)
Docker desktop version 4.5.0 (74594)

**Comment by hubgit** [comment]
A workaround is to open Dashboard from the Docker menu bar icon, then close it again - the Dock icon then disappears.

**Comment by hubgit** [comment]
> Also cannot hide / close the docker window in addition to this blank icon always being present in the dock now

A workaround is to open Dashboard from the Docker menu bar icon, then close it again - the Dock icon then disappears.

**Comment by laurazard** [comment]
Thanks for reporting this, we're looking into it.

**Comment by frddl** [comment]
Icon has disappeared both in dock and on windows switching (cmd + tab) for me after upgrading to Monterey 12.2.1, but is shown on the launchpad.

**Comment by StefanScherer** [comment]
Thanks for the report. We tried it on several machines here and couldn't reproduce the problem.  
But I found a gist "Clear the icon cache on a Mac when you start seeing generic icons in Finder or the Dock" that seems to help users when the wrong icon is displayed. -> https://gist.github.com/ismyrnow/e92c6010cda9325b2d8811387a05f224
It would be great if someone could try this to see if this helps. Thanks.

**Comment by frddl** [comment]
@StefanScherer tried it, it worked. I am seeing the icons both in dock and in window switcher. Thank you!
Meanwhile, right now I am seeing 3 Docker icons on my dock. Any thoughts about that?

**Comment by frddl** [comment]
Nevermind. Fixed it from dock settings.

**Comment by bschuhmann** [comment]
@StefanScherer, tried the command from the gist. Unfortunately and contrary to @frddl it didn't work for me - still no icon in Dock and window switcher. Haven't rebooted yet though in case that would help. I'm on a MBP with only the built-in (main) display.

**Comment by StefanScherer** [comment]
Thanks @bschuhmann for the feedback and that you have tried it.
We're investigating further.

**Comment by trungutt** [comment]
Could you please try out these builds to see if it could improve your situation? @bschuhmann @jnous-5 @flanger001 @nmarley @miklof63 @jlandersen @frddl 
Mac Intel https://desktop-stage.docker.com/mac/main/amd64/75226/Docker.dmg
Mac M1 https://desktop-stage.docker.com/mac/main/arm64/75226/Docker.dmg

**Comment by bschuhmann** [comment]
@trungutt, stopped Docker, installed the new drop and started it - for me icon is now back to normal - maybe it's even better now as there is now only one dock icon even if Dashboard is open compared to before. Thanks a lot!

**Comment by frddl** [comment]
@trungutt Did the same as @bschuhmann. Icons are okay, but with Docker being active and on, it imitates a quit action when I close the window (no dot under the icon on Dock), even though it's still in top bar and the containers are running. And when I open the app from Spotlight/Launchpad, I get double icons in Dock.

**Comment by evilsideburns** [comment]
I've got this issue. Dock shows Docker with the default App icon. Docker menu does not contain "Dashboard". And that "Clear the icon cache on a Mac" gist did not do the trick. I'm running Docker Desktop 4.5.0 (74594) on Catalina 10.15.7 (19H1715).

![Screen Shot 2022-03-08 at 4 49 14 PM](https://user-images.githubusercontent.com/51449984/157331606-9918fb42-ba53-4dbb-ba9e-044bb9ad2608.png)

![Screen Shot 2022-03-08 at 4 49 36 PM](https://user-images.githubusercontent.com/51449984/157331623-132c7f5b-1a81-49c0-b5a5-0a1fdb7e9d54.png)

**Comment by lockieRichter** [comment]
I'm still seeing the missing icon in the Dock after updating to v4.6.0. Running a MacBook Pro (16-inch, 2019), Intel chip.

**Comment by mat007** [comment]
We have released Docker Desktop 4.6.0, with a fix for this issue. See https://docs.docker.com/docker-for-mac/release-notes/.

**Comment by Spiral90210** [comment]
fyi, still missing here, but it does respond to cmd+q again, so it's much less annoying!

<img width="218" alt="Screenshot 2022-03-15 at 10 20 40" src="https://user-images.githubusercontent.com/8685965/158356964-85e1fd5b-dac8-4b4a-8a30-889fe93400cd.png">
<img width="381" alt="Screenshot 2022-03-15 at 10 20 52" src="https://user-images.githubusercontent.com/8685965/158356994-341b2623-1d44-4bb2-b5b1-2911bf032c40.png">

**Comment by dmitry-ivanov** [comment]
@mat007 Same problem with the Dock icon on `macOS Catalina 10.15.7` _(Cmd+Q works on 4.6.0, though 👌)_:

![Dock](https://user-images.githubusercontent.com/1286821/158368679-d7e77a6d-4db9-464c-a2f2-1d762735e156.jpg)

**Comment by mat007** [comment]
Let’s re-open the issue.

@trungutt did I mix-up the issues in the release notes?

**Comment by StefanScherer** [comment]
@mat007 It was the correct ticket, we did some adjustments in the code, but we don't had the problem on our dev/CI machines so we couldn't reproduce it in the first place.
For 4.5.0 we got feedback from other users and customers that the icon appeared some days later without doing anything. Others reported that an uninstall/install of 4.5.0 did the trick. My assumption still is that something in the macOS icon cache has a hick-up and fixes itself after some time. 🤷 
At least it's good to remove the "Keep in Dock" flags of all Docker icons that someone has, then stop and start DD and maybe that also helps?

**Comment by Spiral90210** [comment]
@StefanScherer I don't currently (and don't think I ever had) docker desktop pinned in my dock. I've also tried the linked script to clear the icon cache, which did not work. I would try re-installing, but I need my current environment for the next few weeks so sadly I can't risk it right now. If there's anything I can help to collect any specific diagnostics or anything like that until then, please let me know.

I don't know if it's related, but I had a lot of issues with the update that caused this (prior to 4.6.5) - it was a nightmare to get installed, really didn't seem to want to. I wonder if there was something under the hood going on that this is just a symptom of. Thinking on that, it really makes me want to do a complete re-install just in case! 

Sorry to not be much more use :(

**Comment by dmitry-ivanov** [comment]
_JFYI: I've reinstalled Docker Desktop, and it helped - the icon in Dock became "normal"._

_PS: All my containers are still there, so no issues with that too 👌_

**Comment by Spiral90210** [comment]
Finally got some downtime, confirming that removing the app and installing a new copy has fixed it. How bizzarre.

**Comment by samparmenter** [comment]
None of the updates fixed the icon for me but deleting the app and re-downloading it worked fine.

**Comment by IvanKostyuk** [comment]
I suspect, the file with Icons is corrupted.
I consider it is an issue in docker package and during upgrade it had to be taken care.

I see two icons in resources 
/Applications/Docker.app/Contents/Resources/AppIcon.icns
and ten icons
/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Resources/icon.icns
I guess, the later is used by Docker Desktop application.
after doing
- open "/Applications/Docker.app/Contents/MacOS/"
- Get Info on Docker Desktop.app
- select small icon in the left corner
- press on keyboard Delete

The icon on top corner appeared ugly
![image](https://user-images.githubusercontent.com/17881160/173095924-61af52db-b45b-49e5-b87c-fbdabe6caa38.png)

But it was beautiful in the folder and info preview
![image](https://user-images.githubusercontent.com/17881160/173096143-aaa3c15f-0315-4244-b457-3dd47f33576e.png)
![image](https://user-images.githubusercontent.com/17881160/173096214-e3e03780-4e3c-4f74-a56f-6b6dc3bf2281.png)

The icon now look correct in the Dock and when changing applications with Cmd+Tab
![image](https://user-images.githubusercontent.com/17881160/173096667-1bfc246f-0a38-4880-8b44-7ac2f371f39d.png)
