### ISSUE TITLE
Link to open Docker Dashboard missing from menubar icon on Mac

### ISSUE THREAD

**Issue by streetlogics** [docker/for-mac#6192]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 525DFAFE-9B6B-431C-A0CE-0E3D63545334/20220222182044

### Expected behavior
When clicking the Docker icon in the menu bar, there should be a link to open the "Docker Dashboard" / Docker desktop app.  

### Actual behavior
The link is missing and the only way to get to the dashboard is by hitting cmd + space and launching docker.app from there.
![image](https://user-images.githubusercontent.com/249509/155195189-cbe3dad2-71a3-45a2-ae18-cc81fe845950.png)

### Information
  - Is it reproducible?
    - Yes, started happening after restarting the computer after the latest update
  - Is the problem new?
    - Yes
  - Did the problem appear with an update?
    - Happened after updating to 4.5.0
  - macOS Version: 
    - 12.1
  - Intel chip or Apple chip: 
    - Apple M1
  - Docker Desktop Version: 
    -  4.5.0
    -  <img width="427" alt="image" src="https://user-images.githubusercontent.com/249509/155195275-e4bcd15d-849f-41d0-bebe-84058f2a3a86.png">

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.
```

### Steps to reproduce the behavior
  1. Upgrade to 4.5.0
  2. Restart
  3. Wait for docker to launch / show up in menu bar
  4. Click menu bar icon

**Comment by ericpoe** [comment]
This is also seen on x86_64 Mac, Monterey & Big Sur.

**Comment by niccolomineo** [comment]
I am observing the same issue.

**Comment by nmeegama** [comment]
Experiencing the same issue

**Comment by GM-Alex** [comment]
I expecting the same issue since the last update.

**Comment by ozzyjr** [comment]
Same issue on an Intel iMac, Monterey 12.2.1

In addition, even if I enter my username, it does not remain logged in.

<img width="872" alt="image" src="https://user-images.githubusercontent.com/12512993/155530733-504ed7cb-4ed7-417e-91aa-dd0fb83f992e.png">

<img width="1382" alt="Captura de Tela 2022-02-24 às 10 20 52" src="https://user-images.githubusercontent.com/12512993/155532128-94170ba6-5885-41a8-b477-7fd61382cd75.png">

**Comment by einord** [comment]
Same here. Quite the surprise this morning when starting work.

**Comment by mrmachine** [comment]
Yep. Same here. Without access to the dashboard there is no way to change resources allocated to the Docker VM anymore. Or factory reset.

**Comment by StefanScherer** [comment]
Thanks for the diagnostics. For all others if you can, please upload your diagnostics from the command line as described at https://docs.docker.com/desktop/mac/troubleshoot/#diagnosing-from-the-terminal

With 4.5.0 we've introduced a new whale icon. In case of a problem there's a workaround to switch back to the old menu described in this blog post https://www.docker.com/blog/new-docker-menu-improved-release-highlights-with-docker-desktop-4-5/

We're investigating further to improve the experience with the new menu. Sorry for the inconvenience.

**Comment by StefanScherer** [comment]
The `features-overrides.json` is only a temporary workaround as we plan to remove the old code in the next scheduled release. We really want to understand the root cause why this happens to some users, so diagnostics could really help us to understand the issue. Thanks.

**Comment by streetlogics** [comment]
I don't know if this helps or not @StefanScherer, but on my Mac, if I `cmd + space` and type `docker` and launch `Docker.app` from there, the dashboard does launch, but the menu doesn't update.  

Also worth noting that I did the latest Monterey update yesterday (now on MacOS v12.2.1), and I'm not sure what else I did, but the menu bar was working without having to do anything special (it's possible I did the cmd+space launch trick, but this time the menu bar dropdown had dashboard and all the other expected stuff).  This morning after a fresh restart, it's back to how it's been acting / as reported.

**Comment by GM-Alex** [comment]
Here are my observations. If I activate the old menu the docker icon isn't shown at the dock at start up (which I prefer a lot more than having this annoying icon at the dock), with the new menu the docker icon is shown in the dock. If I click on it nothing happens. With the new menu if I quit docker and restart it again, sometime the menu appears normal as expected. Hope that helps.

**Comment by mat007** [comment]
We have released Docker Desktop 4.6.0, with a fix for this issue. See https://docs.docker.com/docker-for-mac/release-notes/.

**Comment by streetlogics** [comment]
@mat007 (and anyone else who comes back to this issue).  The problem persisted for me after upgrading to 4.6.0 .  I ended up backing out and trying a different approach this time troubleshooting.  
1) I traced down through my dock what was pinned / being started up at login.  It ends up that what I had pinned in the dock was the `Docker Desktop.app` package embedded within the `Docker.app` package.  
2) I right clicked on the `Docker Desktop.app` icon on my dock and unchecked "open at login" and clicked "remove from dock"
3) I dragged the top level `Docker.app` icon into my dock, clicked "keep in dock" and "open at login"
4) After restarting, my docker menu drop is fully populated with all the options I'd expect to see.

**Comment by streetlogics** [comment]
Ends up my workaround didn't stick, I still have to manually launch the `Docker.app` using `cmd + space` to search for it.

**Comment by ozzyjr** [comment]
With me it's unstable. Yesterday it worked and today it doesn't

<img width="827" alt="Captura de Tela 2022-03-28 às 07 59 34" src="https://user-images.githubusercontent.com/12512993/160699045-0063141c-7e62-4f4d-99c0-b756bf7664ad.png">

<img width="792" alt="Captura de Tela 2022-03-29 às 08 40 22" src="https://user-images.githubusercontent.com/12512993/160699078-290f1c8f-890d-467c-9073-f8c693a940ec.png">

**Comment by wammaster** [comment]
It is the same issue for me

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[FAIL] DD0008: is the native API responding? failed to ping tray application with error: Get "http://ipc/ping": read unix ->backend.native.sock: i/o timeout (Client.Timeout exceeded while awaiting headers)
[2022-04-05T13:26:06.570501000Z][com.docker.diagnose][I] ipc.NewClient: 99ed820c-diagnose -> <HOME>/Library/Containers/com.docker.docker/Data/backend.native.sock SwiftAPI
[common/pkg/gui.NewClientForPath({0x477ad4d, 0xc000363620}, {0xc0001160a0, 0x47aece0})
[	common/pkg/gui/client.go:70 +0x3d
[common/pkg/gui.NewClient({0x477ad4d, 0x8})
[	common/pkg/gui/client.go:57 +0x5a
[common/pkg/diagkit/gather/diagnose.glob..func8()
[	common/pkg/diagkit/gather/diagnose/ipc.go:40 +0x25
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x4d508e0, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000203000, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x46c1e00, 0xc00035f968)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x4d50b60, 0x45fd7af, {0xc00035faf8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00012c010, 0x6, 0x4}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x296
[2022-04-05T13:26:06.572955000Z][com.docker.diagnose][I] (7c5fafa6) 99ed820c-diagnose C->S SwiftAPI GET /ping
[2022-04-05T13:26:16.580917000Z][com.docker.diagnose][E] (7c5fafa6) 99ed820c-diagnose C<-S NoResponse GET /ping (10.007977321s): Get "http://ipc/ping": read unix ->backend.native.sock: i/o timeout (Client.Timeout exceeded while awaiting headers)
[common/pkg/gui.(*guiClient).Ping(0x477ad4d)
[	common/pkg/gui/client.go:103 +0x39
[common/pkg/diagkit/gather/diagnose.glob..func8()
[	common/pkg/diagkit/gather/diagnose/ipc.go:41 +0x31
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x4d508e0, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000203000, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x46c1e00, 0xc00035f968)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x4d50b60, 0x45fd7af, {0xc00035faf8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00012c010, 0x6, 0x4}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x296
[2022-04-05T13:26:16.584970000Z][com.docker.diagnose][I] (7c5fafa6-1) 99ed820c-diagnose C->S SwiftAPI GET /ping
[2022-04-05T13:26:17.589433000Z][com.docker.diagnose][E] (7c5fafa6-1) 99ed820c-diagnose C<-S NoResponse GET /ping (1.004402657s): Get "http://ipc/ping": read unix ->backend.native.sock: i/o timeout (Client.Timeout exceeded while awaiting headers)
[common/pkg/gui.(*guiClient).Ping(0x477ad4d)
[	common/pkg/gui/client.go:103 +0x39
[common/pkg/diagkit/gather/diagnose.glob..func8()
[	common/pkg/diagkit/gather/diagnose/ipc.go:41 +0x31
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x4d508e0, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000203000, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x46c1e00, 0xc00035f968)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x4d50b60, 0x45fd7af, {0xc00035faf8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00012c010, 0x6, 0x4}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x296
[2022-04-05T13:26:18.590986000Z][com.docker.diagnose][I] (7c5fafa6-2) 99ed820c-diagnose C->S SwiftAPI GET /ping
[2022-04-05T13:26:19.594442000Z][com.docker.diagnose][E] (7c5fafa6-2) 99ed820c-diagnose C<-S NoResponse GET /ping (1.003411509s): Get "http://ipc/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[common/pkg/gui.(*guiClient).Ping(0x477ad4d)
[	common/pkg/gui/client.go:103 +0x39
[common/pkg/diagkit/gather/diagnose.glob..func8()
[	common/pkg/diagkit/gather/diagnose/ipc.go:41 +0x31
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x4d508e0, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000203000, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x46c1e00, 0xc00035f968)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x4d50b60, 0x45fd7af, {0xc00035faf8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00012c010, 0x6, 0x4}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x296
[2022-04-05T13:26:20.595469000Z][com.docker.diagnose][I] (7c5fafa6-3) 99ed820c-diagnose C->S SwiftAPI GET /ping
[2022-04-05T13:26:21.596575000Z][com.docker.diagnose][E] (7c5fafa6-3) 99ed820c-diagnose C<-S NoResponse GET /ping (1.001099339s): Get "http://ipc/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[common/pkg/gui.(*guiClient).Ping(0x477ad4d)
[	common/pkg/gui/client.go:103 +0x39
[common/pkg/diagkit/gather/diagnose.glob..func8()
[	common/pkg/diagkit/gather/diagnose/ipc.go:41 +0x31
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x4d508e0, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000203000, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x46c1e00, 0xc00035f968)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x4d50b60, 0x45fd7af, {0xc00035faf8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00012c010, 0x6, 0x4}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x296
[2022-04-05T13:26:22.598145000Z][com.docker.diagnose][I] (7c5fafa6-4) 99ed820c-diagnose C->S SwiftAPI GET /ping
[2022-04-05T13:26:23.601821000Z][com.docker.diagnose][E] (7c5fafa6-4) 99ed820c-diagnose C<-S NoResponse GET /ping (1.003666963s): Get "http://ipc/ping": read unix ->backend.native.sock: i/o timeout (Client.Timeout exceeded while awaiting headers)
[common/pkg/gui.(*guiClient).Ping(0x477ad4d)
[	common/pkg/gui/client.go:103 +0x39
[common/pkg/diagkit/gather/diagnose.glob..func8()
[	common/pkg/diagkit/gather/diagnose/ipc.go:41 +0x31
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x4d508e0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x4d508e0, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000203000, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x46c1e00, 0xc00035f968)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x4d50b60, 0x45fd7af, {0xc00035faf8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00012c010, 0x6, 0x4}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x296

[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-04-05T13:26:23.607833000Z][com.docker.diagnose][I] ipc.NewClient: 81636146-diagnose-network -> <HOME>/Library/Containers/com.docker.docker/Data/diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xdd
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x4d50ce0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x4d50ce0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x4d50ce0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x4d50ce0, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000203000, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x46c1e00, 0xc00035f968)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x4d50b60, 0x45fd7af, {0xc00035faf8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00012c010, 0x6, 0x4}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x296
[2022-04-05T13:26:23.608724000Z][com.docker.diagnose][I] (3a4c9a8a) 81636146-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["10.39.12.176","10.250.1.39"]}
[2022-04-05T13:26:24.214247000Z][com.docker.diagnose][E] (3a4c9a8a) 81636146-diagnose-network C<-S f6b1355e-diagnosticsd POST /check-network-connectivity (606.134328ms): failed to ping host: exit status 1
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:35 +0x15b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x4d50ce0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x4d50ce0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x4d50ce0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x4d50ce0, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000203000, 0xc0006a9828)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x46c1e00, 0xc00035f968)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x4d50b60, 0x45fd7af, {0xc00035faf8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00012c010, 0x6, 0x4}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x296

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.

2 : The test: is the native API responding?
    Failed with: failed to ping tray application with error: Get "http://ipc/ping": read unix ->backend.native.sock: i/o timeout (Client.Timeout exceeded while awaiting headers)

The native API server is needed to start Docker engine.
```

**Comment by joergmoldenhauer** [comment]
Why is this closed? The problem is not solved yet.
