### ISSUE TITLE
--env-file option messes up .env path when stopping app in Desktop

### ISSUE THREAD

**Issue by plueschpruem** [docker/for-mac#6229]
I posted this [here](https://github.com/docker/compose/pull/6535#issuecomment-1065935028) already, but it seems the bug is on the Desktop App side…

I am building a workflow to use a single docker-compose.yml to manage several similar projects.
I want to solve that with several .env files to use with the --env-file shell option:
`docker-compose --env-file ./Docker_Config/env_files/test1.env -f ./Docker_Config/docker-compose.yml --project-name test1 up -d --build`
Inside the test1.env is this:
`DOCKER_NAME=test1`

File structure:
root
— Docker_Config
—— env_files
——— test1.env
—— docker-compose.yml

This works as expected, the app builds, starts, all containers are correctly named via the variabel – so far so dandy.
But when I try to stop the app (with the STOP button in Docker Desktop / Apps), I get an error that Docker Desktop could not find the test1.env file.
It seems that Docker is always prepending the full folder of the docker-compose.yml to the .env.
So in my case it tries to open the file at _[…]Docker_Config/Docker_Config/env_files/test1.env_
To confirm I also moved my .yml a level further into another folder – that then also got prepended.
So basically the ONLY possibility to use this new (and frankly very useful) option is to keep all your docker-compose.yml and .env files in the root level. But I guess this is an error, not the desired functionality?

The shell command `down` works – it lists all containers and takes them down one by one.
The button DELETE (trashcan) works in the Desktop App. Only STOP fails for me.

Additionally the app console echos some of these on startup:
`time="2022-03-12T19:19:25+01:00" level=warning msg="The \"DOCKER_NAME\" variable is not set. Defaulting to a blank string."`
Guess that could be connected? Because I only used that var in the docker-config.yml, not in the app itself. It is never passed to the containers and all the functionality the var does provide to the docker-config.yml is working as expectd.

Screenshot of the error:
<img width="967" alt="Bildschirmfoto 2022-03-12 um 20 13 49" src="https://user-images.githubusercontent.com/26715829/158060065-4addad10-542f-405c-bb51-a6298200a647.png">

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Use the provided .env file passed by the --env-file option
### Actual behavior
Prepends the docker-compose.yml folder path to the .env and thus fails.
### Information

  - macOS Version: 12.2.1 (21D62)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.5.0 (74594)
  - Docker version 20.10.12, build e91ed57
  - Docker Compose version v2.2.3

**Comment by StefanScherer** [comment]
Thanks @plueschpruem for the report. I can reproduce it with Docker Desktop 4.5.0. 
I have good news for you. We've just released Docker Desktop 4.6.0 which doesn't have this problem any longer.

**Comment by plueschpruem** [comment]
Thanks for the swift action, but I still get the same error :-(
Updated to Docker Desktop 4.6.0 (75818) right away, also to OSX 12.3 and ran all XCode updates.

But there are two differences:
1 - The DELETE button in the App now also gives me the same error (except the different command).
2 - The startup errors in my Apps' console regarding the missing env-vars are not showing anymore. So that's good.

<img width="1571" alt="Bildschirmfoto 2022-03-16 um 12 21 41" src="https://user-images.githubusercontent.com/26715829/158579852-e3eb94da-8c12-416c-92b1-3ef9d7d07507.png">

**Comment by StefanScherer** [comment]
Yes you need to delete the old app containers.

**Comment by plueschpruem** [comment]
> Yes you need to delete the old app containers.

I just did deleted all images, volumes and containers, pruned the system, rebuild all images and the container under a new name – and still get the exact same error.
Changing the env-files' path and rebuilding leads to the new path being included in the error. So I feel the error was not handled entirely.

As noted the startup errors in the container are gone, so _something_ changed…

**Comment by StefanScherer** [comment]
I tried to reproduce your steps, this is what I did and I don't see any errors.

```
$ cd
$ cd Documents/
$ mkdir Docker_Config
$ cd Docker_Config/
$ mkdir env_files
$ vi env_files/test1.env
$ vi docker-compose.yml
$ cd ..
$ docker-compose --env-file ./Docker_Config/env_files/test1.env -f ./Docker_Config/docker-compose.yml --project-name test1 up -d --build
```

I can stop the app from the UI without any error. 🤔 

BTW: I use Compose V2:

```
$ docker-compose --version
Docker Compose version v2.3.3
```

Maybe you are on Compose V1?

**Comment by StefanScherer** [comment]
If you still have the problem maybe you could upload the diagnostics, then we can have a closer look.

**Comment by StefanScherer** [comment]
Thank you, yes the Start action still shows this error. 😬 I've re-opened the ticket.

**Comment by plueschpruem** [comment]
Made a simple test project, results are the same.
- STOP and DELETE work as expected
- START does not work – same error as initially with the other buttons.
- Both vars from file and shell are errored as unset in the app container

Further testing:
**1: Starting without the --env-file option:**
- All buttons works as expected.
- Container still errors the vars as not set, although they are not used inside the app, only in the .yml for naming – and are also used correctly.

**2: Starting without shell exports/vars:**
- START button fails.
- Container still errors passed vars

<img width="949" alt="Bildschirmfoto 2022-03-17 um 11 13 55" src="https://user-images.githubusercontent.com/26715829/158787699-523c5cdb-ebe7-4168-bf91-af0680834aa5.png">

Docker Compose version v2.3.3
Docker version 20.10.13, build a224086

**Comment by plueschpruem** [comment]
> Thank you, yes the Start action still shows this error. 😬 I've re-opened the ticket.

Just when I hit that SEND button :-P

Thank you!
