### ISSUE TITLE
Docker stops working after php debugger is stopped

### ISSUE THREAD

**Issue by gyosko** [docker/for-mac#6235]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID: Diagnostic is not being generated

### Expected behavior
After I stop the Visual Studio "Listen for Xdebug" debugger configuration, Docker should keep working as usual.

### Actual behavior
Docker stops working after Visual Studio debugger is stopped.

### Information

  - macOS Version: 12.3
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.6.0 (75818) 

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```

Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.

```

### Steps to reproduce the behavior

  1. Start any lamp application with docker-compose
  2. Start Visual Studio PHP Debugger
  3. Debug request
  4. Stop Visual Studio PHP Debugger

**Comment by malis42** [comment]
I believe I have the same problem, although I used intelliJ IDE for debugging with xdebug and PHP 7.4. After downgrading to Docker Desktop version 4.4.2 problem disappeared.

**Comment by gyosko** [comment]
Same here, I downgraded to 4.5 and the problem disappeared.

**Comment by mrgyf1** [comment]
Same problem solved with downgrade to 4.5 (Apple Chip)

**Comment by luancschmitz** [comment]
same problem here. The website gives error 502 bad gateway.
Downgrading to version 4.5.0 resolved the issue.
(Apple Silicon M1)

**Comment by ubermaniac** [comment]
Same issue here as well with M1 and Intel. Downgrading to 4.5.0 works fine.

**Comment by darkniki** [comment]
Same issue here as well with m1 and intel, in phpstorm, disabling chrome xdebug helper solves this problem

**Comment by Zekvyrin** [comment]
There is a new desktop version 4.6.1 that fixes this #6233 

Tests stopped initiating from me today but they started again after the upgrade. So maybe it is fixed?

**Comment by gyosko** [comment]
@Zekvyrin it looks like #6233 solves the diagnostic tools, but it does not fix this issue

**Comment by froboy** [comment]
Confirming the issue is still present in 4.6.1

**Comment by froboy** [comment]
Running diagnostics while the system is in this broken state doesn't throw any errors:

```
❯ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

Logs for the containers didn't contain any useful errors... hitting my site from the browser or even `curl -I ...` just hung indefinitely.

**Comment by rfay** [comment]
Diagnostics: 165EF212-DB99-4FE1-90A4-E516A309B23F/20220323170553

This is with ddev on port 9003.  I'll edit with a repro scenario in a moment. When the OP says "docker doesn't work" after turning off the xdebug listener, that seems to mean that HTTP requests are no longer fulfilled, things just hang. `docker ps` and such still work.

**Comment by ClaudioCrespo** [comment]
I'm experiencing the same issue, v4.6.1, gonna have to roll back till a fix comes out, which sucks cause the VirtioFS were great

**Comment by fredericdalleau** [comment]
@rfay in your use case, `nc` can't handle multiple connections. You can try with `socat`.

**Comment by rfay** [comment]
I think the actual description of the problem is probably what is in 
* https://github.com/drud/ddev/issues/3735

1. `ddev xdebug on`
2. PhpStorm listener enabled (telephone on) and breakpoint set
3. `ddev launch` opens browser and stops at breakpoint
4. Let it run through the page (continue)
5. Disable the PhpStorm listener
6. Try to load a page again in browser... it hangs forever. 

In previous versions of Docker Desktop, loading a page without a listener available would result in an error because xdebug can't connect to host.docker.internal:9003.

Now, despite the fact that PhpStorm has closed port 9003 (connecting on host shows connection refused), you can still connect to it inside the container. `telnet host.docker.internal 9003` will connect and hang. So that's what's happening here, despite the fact that the host-side listener has closed the port, it's still available inside the container, resulting in an infinite hang. And because xdebug finds it there, it tries to connect and does not error out like it usually would.

The issue should be retitled to "Docker Desktop keeps port open inside container even after it has been closed on by host-side listener"

**Comment by rivalindi** [comment]
Tried today and v4.7 still does not fix it.

**Comment by grimabe** [comment]
Same problem. Did not work with 4.6 and still not today with 4.7.

**Comment by smepti** [comment]
Same problem with xdebug on 4.6+
@fredericdalleau will it be fixed?

**Comment by fredericdalleau** [comment]
Yes we have a simpler way to reproduce and are working on it.

**Comment by rfay** [comment]
Issue remains in Docker Desktop 4.7.1

**Comment by fredericdalleau** [comment]
Hi, sorry it took a while, can you try this build ?
https://desktop-stage.docker.com/mac/main/amd64/78146/Docker.dmg
https://desktop-stage.docker.com/mac/main/arm64/78146/Docker.dmg
Thanks!

**Comment by smepti** [comment]
> Hi, sorry it took a while, can you try this build ? https://desktop-stage.docker.com/mac/main/amd64/78146/Docker.dmg https://desktop-stage.docker.com/mac/main/arm64/78146/Docker.dmg Thanks!

Yeah, xdebug work correctly on this build!

Start button not working in gui and throw error, but I don't it's related to this issue :)
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/12631539/165374676-0c591329-b1a2-44c5-86bb-e31fd8f966f2.png">

Thank's a lot!

**Comment by fredericdalleau** [comment]
@smepti thanks for feedback, i'll tell the team!

**Comment by dustinsilva** [comment]
I can confirm both 4.5.0 and Build 78146 work, while any build between them is broken.

**Comment by samuelcastello** [comment]
I also can confirm 4.5.0 works fine with xDebug when I'm back of listening connections, but seems 4.7.1 with VirtioFS works faster.

**Comment by TheCelavi** [comment]
@fredericdalleau Hi, thanks for the update - tried the build for 7 days now and it works, but it is heavily unstable. Whole engine breaks/gets stuck after just 30 minutes to an hour of work. Hard restart is required and it has to be killed from Activity Monitor (Mac M1, 16GB RAM).

**Comment by fredericdalleau** [comment]
@TheCelavi are you using virtualization framework, with (or without virtiofs?) ? If that's the case, you may want to try macOS 12.4 beta 3 which contains fixes for issues of containers freezing or VM crashing some time after enabling virtiofs.  See  https://github.com/docker/for-mac/issues/6256#issuecomment-1110742280

**Comment by samuelcastello** [comment]
> @TheCelavi are you using virtualization framework, with (or without virtiofs?) ? If that's the case, you may want to try macOS 12.4 beta 3 which contains fixes for issues of containers freezing or VM crashing some time after enabling virtiofs. See [#6256 (comment)](https://github.com/docker/for-mac/issues/6256#issuecomment-1110742280)

I've just installed macOS 12.4 beta 4 and the problem continues

**Comment by samuelcastello** [comment]
It works! Superb! Many thanks @fredericdalleau

**Comment by rfay** [comment]
This problem is unfortunately *not* solved in Docker Desktop 4.8.0

**Comment by aguedeney** [comment]
Unfortunately. I can attest to this problems still be an issue with 4.8.0 (tested it today), going back to 4.5.0.

**Comment by fredericdalleau** [comment]
@rfay, @aguedeney oops, I'll double check that.

**Comment by gyosko** [comment]
It's working for me now on an apple m1.

Docker Desktop 4.8.0 (78933)
macOS Version: 12.3.1
Intel chip or Apple chip: Apple

**Comment by fredericdalleau** [comment]
@rfay @aguedeney  here is my test procedure : I have a ddev website that contains a simple phpinfo() lamed from the ddev site.

* mkdir junk && cd junk && ddev config --auto && printf "<?php\nphpinfo();\n" >index.php && ddev launch
* confirm I can browse the site locally
* `ddev xdebug enable` 
* `nc -l 9003`
* browse the site and I can see the xdebug connection, the site does not load.
* close `nc`, the site loads in the browser.
* browse the site, the site loads, the answer is immediate

Could you confirm you're running the correct vpnkit version?
```
/Applications/Docker.app/Contents/Resources/bin/com.docker.vpnkit --version
e67cca0d141730c7e50a3a70deea5b980c4d3773
```

**Comment by fredericdalleau** [comment]
There was only one important fix unrelated to this issue. I wondered if anything else could have occured : Do you have several DD installations that could coexist in weird ways?  Or maybe having the connection pattern is a little bit different. In any case, if you see it again, let me know!

**Comment by rfay** [comment]
Only one installation. When installing 4.8.0, I did it by downloading 4.8.0 and installing, because update was turned off. When installing 4.8.1 I did it with the check-for-updates and download technique.

**Comment by aguedeney** [comment]
4.8.1 passed the following test for me.

```
1. Listen on a given port with netcat: nc -l -k 3333
2. Run a linux image: docker run -it --entrypoint /bin/bash node:14-buster-slim
3. Inside it, install netcat: apt-get update && apt-get install -y netcat
4. Run netcat towards the ip+port you are listening at step 1: nc <YOUR IP> 3333
5. Kill the listening netcat process. The netcat command inside docker dies as expected.
6. Without restarting the listening command, re-run the netcat command inside docker.

Expected result: connection refused.
Actual result: the connection seems established.

Credit goes to:[sebmjoll](https://github.com/sebmjoll)
```

**Comment by ClaudioCrespo** [comment]
4.8.1 fixed the issue for me, Thank you!!!!

**Comment by fredericdalleau** [comment]
@aguedeney what do you mean by passed? did you get the expected result?

**Comment by aguedeney** [comment]
Yes, I got the expected result. It’s working fine for me. Thank you.

**Comment by lorenrh** [comment]
I'm closing this issue, as a fix for this has been released on Docker Desktop 4.8.1!
