### ISSUE TITLE
fork/exec [docker-app-path]/bin/docker-compose-v1: permission denied

### ISSUE THREAD

**Issue by drpiou** [docker/for-mac#6400]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: Cannot process diagnostics. Reason: Error invoking remote method 'desktop-go-backend': [object Object]

### Expected behavior

I can update from 4.9.1 to 4.10.1 and still start docker containers from the desktop app.

### Actual behavior

I can update from 4.9.1 to 4.10.1 but I cannot start anymore docker containers from the desktop app.

```
Cannot start Docker Compose application. Reason: fork/exec [docker-app-path]/bin/docker-compose-v1: permission denied
```

### Information
  - Is it reproducible? I don't know.
  - Is the problem new? Yes.
  - Did the problem appear with an update? Yes.
  - macOS Version: Mac OS 12.4.
  - Intel chip or Apple chip: Intel chip.
  - Docker Desktop Version: v4.10.1.

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
Cannot process diagnostics. Reason: Error invoking remote method 'desktop-go-backend': [object Object]
```

### Steps to reproduce the behavior

  1. Update Docker desktop to 4.10.1.

**Comment by cjones-altair** [comment]
Same issue for me. I had to revert back to 4.9.1.

**Comment by ShadeDream** [comment]
Same issue. Have been working around by manually starting with `docker-compose up -d` from the command line. Tried resetting docker, reinstalling and building everything from scratch in the new version, no help.

**Comment by askazion** [comment]
Same here

**Comment by revox91** [comment]
the same for me

**Comment by trungutt** [comment]
Hi everyone, we can reproduce this bug on our side as well. We're working on a fix for next release

**Comment by nasersobhan** [comment]
I have the same issue, but only with Docker Desktop, I can run docker from terminal.

**Comment by lporras** [comment]
I'm having the same problem trying to run `docker compose up`

**Comment by joelataylor** [comment]
Same. Have downgraded to 4.9.1.

**Comment by nguyenvudao** [comment]
Same problem, I have to run my containers by command line 😢

**Comment by 0fs** [comment]
Same problem 😏

**Comment by zulfikar4568** [comment]
Same problem :(, I used on Mac M1

**Comment by nguyenvudao** [comment]
You guys could try to start the containers by command line, next time you can start by docker desktop.
Tested on Macbook pro 2020 Intel.

**Comment by nguyenvudao** [comment]
> Same problem, I have to run my containers by command line 😢

You guys could try to start the containers by command line, next time you can start by docker desktop.
Tested on Macbook pro 2020 Intel.

**Comment by MironGr** [comment]
HI!
I have the same problem only with Docker Desktop, terminal haven't got this problem.
the solve for me:
`docker kill $(docker ps -q)`
`docker rm $(docker ps -a -q)`
`docker-compose up -d --build`

information:
- macOS Version: Mac OS 12.0.1
- chip: M1
- Docker Desktop 4.10.1

**Comment by BeliliFahem** [comment]
same problem for me :'(

**Comment by Vitaly1025** [comment]
For me too :(

**Comment by tim-tsui** [comment]
Starting/stopping containers in terminal works on mac for me. Just not the GUI.

`docker-compose start`
`docker-compose stop`

**Comment by cantonalex** [comment]
I was hesitant to update because I thought I would have a problem. Lo and behold..

**Comment by AndreasHerz** [comment]
same here...

**Comment by tangxiangmin** [comment]
same proble for me after upgrade docker desktop to Version4.10.1 (82475)

**Comment by dgtllion** [comment]
+1 Mac Intel Chip

**Comment by xiayuyuyu** [comment]
same for me,
macos version:12.4 (21F79)
chip: M1
docker:4.10.1 (82475)

**Comment by arananegra** [comment]
+1 On Mac M1 Pro

**Comment by tmrsiteops** [comment]
Same here. Docker Desktop v4.10.1 (82475). Mac OS 12.4, Intel chip.

**Comment by trungutt** [comment]
Hi all, could you try out these custom builds to see if the problem still persists?

Mac M1: https://desktop-stage.docker.com/mac/main/arm64/83254/Docker.dmg
Mac Intel: https://desktop-stage.docker.com/mac/main/amd64/83254/Docker.dmg
Windows: https://desktop-stage.docker.com/win/main/amd64/83254/Docker%20Desktop%20Installer.exe

**Comment by LuisLSousa** [comment]
@trungutt the problem is fixed for me with that custom build (Mac M1). Thanks!

**Comment by cjones-altair** [comment]
@trungutt, Thank you. It's fixed for me on Mac Intel as well.

**Comment by yamadar** [comment]
@trungutt, Thank you! It's fixed.
macOS Version: Mac OS 12.4
chip: Intel

**Comment by nguyenhongngoc09** [comment]
@trungutt Thank you. This issue on my Mac is fixed.
MacOS is the same with @yamadar :D

**Comment by kennym** [comment]
@trungutt confirmed fix on m1

**Comment by tangxiangmin** [comment]
@trungutt, Thanks! It works fine on MacOS 11.6 with Intel chip.

**Comment by DrBlackBird** [comment]
fix for M1 :) thank you so much!

**Comment by vrdriver** [comment]
Working now on 2018 i7 Mac Mini.  12.3.1 (21E258). Thanks heaps.

**Comment by gavin-timbrell** [comment]
We've just released [Docker Desktop 4.11.0](https://docs.docker.com/desktop/release-notes/#docker-desktop-4110) which includes a fix for this.

**Comment by imanassypov** [comment]
Running Version 4.11.1 (84025) - issue still persists with default distro

**Comment by slavanorm** [comment]
@gavin-timbrell hello, why close issue if it persists?
4.11.1 mac m1 here

**Comment by gavin-timbrell** [comment]
@imanassypov @slavanorm thanks for the feedback, I've reopened this now so we can take another look.

**Comment by nicks** [comment]
Chatted with Gavin off-list. We're going to close this, given that the original repro steps no longer reproduce the issue. If you're still getting this error, please file a new issue with additional repro steps and a diagnostics id.
