### ISSUE TITLE
Docker Desktop GUI issue with OSX Ventura

### ISSUE THREAD

**Issue by jquick** [docker/for-mac#6465]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E3A0E50C-B9DE-4F85-8910-BC9AD9E20A7E/20220831133424

### Expected behavior
It starts up correctly and GUI is responsive.

### Actual behavior
The GUI cannot connect to the backend and is none responsive. The error from the logs seems to be (over and over):
```
(c0cb2e51-19) 60169025-BackendCMD C<-S NoResponse GET /ping (5.520334ms): Get "http://ipc/ping": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x<decode: missing data>
```
and frontend looks like:
<img width="1243" alt="Screenshot 2022-08-31 at 9 21 12 AM" src="https://user-images.githubusercontent.com/574637/187688269-dd3c0c42-7e7a-4097-a2d2-e838d1f50f9a.png">
The backend itself looks to work OK though:
```
❯ curl --unix-socket /var/run/docker.sock 'http://localhost/v1.41/_ping'
OK%
```
```
❯ curl --unix-socket /var/run/docker.sock 'http://localhost/v1.41/info'
{"ID":"MRI7:L37C:LFRL:V5MD:6X6B:JTHI:YE6M:FBFA:JMG6:I6D5:YPB7:PDKT","Containers":0,"ContainersRunning":0,"ContainersPaused":0,"ContainersStopped":0,"Images":0,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","extfs"],["Supports d_type","true"],["Native Overlay Diff","true"],["userxattr","false"]],"Plugins":{"Volume":["local"],"Network":["bridge","host","ipvlan","macvlan","null","overlay"],"Authorization":null,"Log":["awslogs","fluentd","gcplogs","gelf","journald","json-file","local","logentries","splunk","syslog"]},"MemoryLimit":true,"SwapLimit":true,"KernelMemory":false,"KernelMemoryTCP":false,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"PidsLimit":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":44,"OomKillDisable":false,"NGoroutines":46,"SystemTime":"2022-08-31T13:29:32.267843751Z","LoggingDriver":"json-file","CgroupDriver":"cgroupfs","CgroupVersion":"2","NEventsListener":4,"KernelVersion":"5.10.104-linuxkit","OperatingSystem":"Docker Desktop","OSVersion":"","OSType":"linux","Architecture":"aarch64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"AllowNondistributableArtifactsCIDRs":[],"AllowNondistributableArtifactsHostnames":[],"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":[],"Secure":true,"Official":true},"hubproxy.docker.internal:5000":{"Name":"hubproxy.docker.internal:5000","Mirrors":[],"Secure":false,"Official":false}},"Mirrors":[]},"NCPU":4,"MemTotal":8232873984,"GenericResources":null,"DockerRootDir":"/var/lib/docker","HttpProxy":"http.docker.internal:3128","HttpsProxy":"http.docker.internal:3128","NoProxy":"hubproxy.docker.internal","Name":"docker-desktop","Labels":[],"ExperimentalBuild":false,"ServerVersion":"20.10.17","Runtimes":{"io.containerd.runc.v2":{"path":"runc"},"io.containerd.runtime.v1.linux":{"path":"runc"},"runc":{"path":"runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null},"LiveRestoreEnabled":false,"Isolation":"","InitBinary":"docker-init","ContainerdCommit":{"ID":"10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1","Expected":"10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1"},"RuncCommit":{"ID":"v1.1.2-0-ga916309","Expected":"v1.1.2-0-ga916309"},"InitCommit":{"ID":"de40ad0","Expected":"de40ad0"},"SecurityOptions":["name=seccomp,profile=default","name=cgroupns"],"Warnings":null}
```

I am able to pull/start a container as expected. 

### Information

  - macOS Version: 13.0 Beta (22A5331f)
  - Intel chip or Apple chip: Apple Silicon
  - Docker Desktop Version: 2.11.1

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
❯ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
(never continues past this point)
```

### Steps to reproduce the behavior

  1. Install Ventura Beta6 on m1 mac
  2. Start Docker Desktop and try and use the GUI

**Comment by nicks** [comment]
Thanks for reporting. I know at least one docker desktop engineer has been using it regularly with the macos Ventura beta. That variable might be a red herring. DD 4.12 will be out soon and I want to double check if this persists for you in 4.12.

**Comment by zimmix** [comment]
I am no longer able login into AWS ECR from my M2  since I updated to Ventura Beta 6.  The Docker Desktop reports: It looks like there is an error with Docker Desktop, restart it to fix it.  Restarting doesn't fix it.  Also none of the following work:

Clean / Purge data
This will solve problems with disk corruption, Docker Engine not booting...

Reset to factory defaults
All settings and data will be removed.

Uninstall
We’re sorry to see you go. This completely uninstalls Docker Desktop.

**Comment by jquick** [comment]
@zimmix I was seeing the same issue with unable to do any of the Troubleshooting (uninstall/purge). I ended up manually nuking using https://stackoverflow.com/a/65468254/1432060 and trying multiple versions. But everything I have tried has the same error. I wonder if you look up the `docker` logs in console while its running if your having the same 
```
"http://ipc/ping": net/http: HTTP/1.x transport connection broken: malformed HTTP response
```

**Comment by jquick** [comment]
@nicks It looks like the new version 4.12.0 fixes this issue! 🥳 🚀 

 I still have a minor issue with SSO just sitting on 
```
validating credentials...
```
 forever until I kill Docker. But that is a minor issue at the moment.

**Comment by eshwen** [comment]
Same for me. The development build of 4.12.0 appears to be working fine except the "validating credentials" hang after attempting to log in

**Comment by koodeau** [comment]
Same issue here. Colima is working fine for me but looks like a lot of complexity because of more advanced access to `lima` /`rancher`. But it works really fast and no issues with it. Bot for me as a beginner in Kubernetes I'd prefer using Minikube for creating my Kubernetes clusters rather than k3s used by `Colima`. But Docker really has its own magic and more stable that other solutions. So while I'm using Mac I'll stick to Docker, in linux you'd have more options available if not running on Apple Silicon.

Also, if Docker Desktop now an issue for you with kind of "freeware" all-in-one solution, then I'd buy and configure Raspberry PI or use some cloud solution for a while where you can natively without virtualization run docker daemon.

**Comment by koodeau** [comment]
For now I had Kubernetes working when first ran Docker Desktop after fresh install but it now fails to start constantly and Desktop app seems to have some previous issues from v4.11.1. At least everything else is working fine, maybe except some settings that don't use actively

**Comment by koodeau** [comment]
I suppose it's not only a Docker Desktop GUI issue here but probably something else is going in the background, I suppose it also has to do something with partial support for Apple Silicon in some parts. But I might be wrong.

**Comment by drosskopp** [comment]
I got same Problems. Where can I get the development build of 4.12.0?

**Comment by arag0re** [comment]
version 4.12 fixes the issue for me, thanks guys

**Comment by eshwen** [comment]
@drosskopp https://github.com/docker/for-mac/issues/6435#issuecomment-1232921520

**Comment by DiegoGiovany** [comment]
Still unable to quit docker, and the daemon log still showing malformed http on ping request

**Comment by nicks** [comment]
hooray! I'm going to mark this as fixed in 4.12. There's a separate issue for the more narrow credentials issue: https://github.com/docker/for-mac/issues/6469

**Comment by Dids** [comment]
What exactly does 4.12 fix in relation to this/Ventura issues? Because I'm still seeing all of these issues, even on 4.12, where virtually every action done through the desktop/dashboard app does nothing, including restarting, resetting and shutting down Docker.

**Comment by kaorihinata** [comment]
@Dids Nothing, that I can tell. After a period of time the backend becomes unresponsive, and any action that requires communication with the backend ceases to function (like the "Sign In" button, checking for updates, etc), but even before that, checking for updates doesn't function for me. I've tried killing and restarting all Docker processes, I've tried removing Docker, and wiping all traces of it from `$HOME/Library`, and nothing seems to help. For the people for whom it appears to be working, I wonder if it actually *is* or if it only appears to be because their backend is so far gone that it's just no longer resulting in an error.

**Comment by jedisct1** [comment]
`colima` works *except* when assigning a reachable IP to the virtual host. That feature is unfortunately broken on Ventura.

But at least, everything else works.

**Comment by arag0re** [comment]
> What exactly does 4.12 fix in relation to this/Ventura issues? Because I'm still seeing all of these issues, even on 4.12, where virtually every action done through the desktop/dashboard app does nothing, including restarting, resetting and shutting down Docker.

Yes restarting, stopping and all this stuff is still scuffed.

**Comment by kaorihinata** [comment]
With macOS Ventura Developer Beta 7 (which is, I think, Public Beta 5?) which just dropped yesterday, it looks like communication with the backend daemon is now fixed, and for me this finally fixed restarting, signing in, most of the stuff in the debug menu, etc. It also seems to have fixed `docker login` (and by extension, `docker-credential-desktop`) on the command line (which I believe is the cause of #6469.) Is anyone on Beta 7 still having these issues?

**Comment by LorenzoS92** [comment]
I confirm that right now the situation seems working.
No more issues with the communication with backend.
Also from console logging, **no more strange errors** of ipc/ping.

So, everything ok.

**Comment by Dids** [comment]
Worked sporadically for me on the latest macOS Ventura beta at first, but now Docker is refusing to even start. Just stuck starting, and terminating all Docker processes doesn't help, even though this used to help at least get it started.

Surely I'm not the only one who is still seeing issues with Docker for Mac on macOS Ventura?

**Comment by arag0re** [comment]
> Worked sporadically for me on the latest macOS Ventura beta at first, but now Docker is refusing to even start. Just stuck starting, and terminating all Docker processes doesn't help, even though this used to help at least get it started.
> 
> Surely I'm not the only one who is still seeing issues with Docker for Mac on macOS Ventura?

I had to reinstall it completely, then it was starting.

**Comment by kaorihinata** [comment]
> Worked sporadically for me on the latest macOS Ventura beta at first, but now Docker is refusing to even start. Just stuck starting, and terminating all Docker processes doesn't help, even though this used to help at least get it started.
> 
> Surely I'm not the only one who is still seeing issues with Docker for Mac on macOS Ventura?

Same as @arag0re, I have essentially wiped Docker entirely a few times for this pair of tickets, and am relatively stable for now. Unfortunately, I use Docker as little as possible (just for image building and pushing from the CLI), so I recognize that I may not be especially representative of those with more complicated use cases where you can't just wipe to solve problems.

**Comment by sanarena** [comment]
I am having this issue in 4.12.0. here is the diagnosis ID 0DE2584C-17A4-4359-9A11-365C5C43E538/20220915081442
