### ISSUE TITLE
"Docker Desktop is stopping" on macOS M1 Max and hanging

### ISSUE THREAD

**Issue by avioli** [docker/for-mac#6472]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F2606449-114C-4887-8E78-7926B365C0EE/20220905023134

### Expected behavior

Docker Desktop starts and I can use the cli tool.

### Actual behavior

I cannot run the cli tool, nor Docker Desktop is usable - it shows "Docker Desktop is stopping" and the whole UI is unusable, except for the bug report/reset tool (and various not so useful views).

### Information

  - macOS Version: 12.5.1 (21G83)
  - Intel chip or Apple chip: Apple chip - M1 Max
  - Docker Desktop Version: 4.12.0 (85629)

This behaviour is not reproducible on any other Mac computer I have access to other than the one I used to produce the diagnostics.

The problem is new - Docker Desktop used to work last week (This is Friday and today is Monday), which was running a previous version - either 4.11 or 4.7 or something close, since I did not note it except that I have a memory of seeing a version number when trying to re-install via homebrew.

The problem did not appear with an update, but with a restart of the computer and an update to the latest Docker Desktop did not resolve it.

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
$ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[FAIL] DD0031: does the Docker API work? Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-09-05T02:33:16.780765000Z][com.docker.diagnose][I] ipc.NewClient: 08ac81ec-com.docker.diagnose -> lifecycle-server.sock VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:59
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x100ad5e20, 0x13})
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:53 +0x90
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[	common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x28
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1011e3940)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x40
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1011e3940)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x40
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x1011e3a40?, 0x1011e3940)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x80
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1011e3940, 0x1400059f718)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x38
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1011e3a40?, 0x1400059f718)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x74
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x20?, 0x1400059f718)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x74
[common/pkg/diagkit/gather/diagnose.walkOnce(0x100ca1660?, 0x1400059f890)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x1011e3cc0, 0x140002a21e0?, {0x1400059fb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x160
[main.checkCmd({0x140001aa010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0xdc
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x30c
[2022-09-05T02:33:16.781725000Z][com.docker.diagnose][I] (4aba8ee2) 08ac81ec-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2022-09-05T02:33:16.782051000Z][com.docker.diagnose][W] (4aba8ee2) 08ac81ec-com.docker.diagnose C<-S NoResponse GET /docker (321.334µs): Get "http://ipc/docker": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-09-05T02:33:16.782277000Z][com.docker.diagnose][I] (4aba8ee2-1) 08ac81ec-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T02:33:16.782547000Z][com.docker.diagnose][W] (4aba8ee2-1) 08ac81ec-com.docker.diagnose C<-S NoResponse GET /ping (269.125µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-09-05T02:33:17.783651000Z][com.docker.diagnose][I] (4aba8ee2-2) 08ac81ec-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T02:33:17.786448000Z][com.docker.diagnose][W] (4aba8ee2-2) 08ac81ec-com.docker.diagnose C<-S NoResponse GET /ping (2.790875ms): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-09-05T02:33:18.787894000Z][com.docker.diagnose][I] (4aba8ee2-3) 08ac81ec-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T02:33:18.790422000Z][com.docker.diagnose][W] (4aba8ee2-3) 08ac81ec-com.docker.diagnose C<-S NoResponse GET /ping (2.51675ms): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-09-05T02:33:19.791560000Z][com.docker.diagnose][I] (4aba8ee2-4) 08ac81ec-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T02:33:19.793782000Z][com.docker.diagnose][W] (4aba8ee2-4) 08ac81ec-com.docker.diagnose C<-S NoResponse GET /ping (2.285791ms): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-09-05T02:33:20.794599000Z][com.docker.diagnose][I] (4aba8ee2-5) 08ac81ec-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T02:33:20.797034000Z][com.docker.diagnose][W] (4aba8ee2-5) 08ac81ec-com.docker.diagnose C<-S NoResponse GET /ping (2.432708ms): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-09-05T02:33:21.797765000Z][com.docker.diagnose][I] (4aba8ee2-6) 08ac81ec-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T02:33:21.800243000Z][com.docker.diagnose][W] (4aba8ee2-6) 08ac81ec-com.docker.diagnose C<-S NoResponse GET /ping (2.470583ms): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-09-05T02:33:22.801217000Z][com.docker.diagnose][I] (4aba8ee2-7) 08ac81ec-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T02:33:22.803775000Z][com.docker.diagnose][W] (4aba8ee2-7) 08ac81ec-com.docker.diagnose C<-S NoResponse GET /ping (2.547917ms): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-09-05T02:33:23.806518000Z][com.docker.diagnose][I] (4aba8ee2-8) 08ac81ec-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T02:33:23.809398000Z][com.docker.diagnose][W] (4aba8ee2-8) 08ac81ec-com.docker.diagnose C<-S NoResponse GET /ping (2.888416ms): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory

[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": dial unix diagnosticd.sock: connect: no such file or directory
[2022-09-05T02:33:23.811509000Z][com.docker.diagnose][I] ipc.NewClient: 049ec18d-diagnose -> diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func12()
[	common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x8c
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1011e38c0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x40
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1011e38c0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x40
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x1011e3940?, 0x1011e38c0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x80
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1011e38c0, 0x140000d1718)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x38
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1011e3940?, 0x140000d1718)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x74
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1011e3a40?, 0x140000d1718)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x74
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x20?, 0x140000d1718)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x74
[common/pkg/diagkit/gather/diagnose.walkOnce(0x100ca1660?, 0x1400059f890)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x1011e3cc0, 0x140002a21e0?, {0x1400059fb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x160
[main.checkCmd({0x140001aa010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0xdc
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x30c
[2022-09-05T02:33:23.813326000Z][com.docker.diagnose][I] (9b3bad8b) 049ec18d-diagnose C->S diagnosticsd GET /ping
[2022-09-05T02:33:23.814174000Z][com.docker.diagnose][W] (9b3bad8b) 049ec18d-diagnose C<-S NoResponse GET /ping (841.584µs): Get "http://ipc/ping": dial unix diagnosticd.sock: connect: no such file or directory

[FAIL] DD0016: is the LinuxKit VM running? vm is not running: failed to open kmsg.log: open log/vm/kmsg.log: no such file or directory
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: failed to open kmsg.log: open log/vm/kmsg.log: no such file or directory
[PASS] DD0015: are the binary symlinks installed?
```

The tool never finishes!

### Steps to reproduce the behavior

  1. ...
  2. ...

I cannot provide steps, since I'm unable to reproduce it on any other machine I've got access to.

I'll create a new user account and see if Docker Desktop loads within that.

**Comment by avioli** [comment]
Quick update. When I quit Docker Desktop from the menubar - the `com.docker.diagnose check` tool resumed outputting data:

```
[PASS] DD0015: are the binary symlinks installed?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0013: is the $PATH ok?
[FAIL] DD0007: is the backend responding? failed to ping com.docker.backend with error: Get "http://ipc/ping": dial unix backend.sock: connect: no such file or directory
[2022-09-05T02:50:40.788714000Z][com.docker.diagnose][I] ipc.NewClient: ee494a31-diagnose -> backend.sock BackendAPI
[common/pkg/backend.NewClientForPath({0x100acd4b6?, 0x0?}, {0x14000492140?, 0x100bd4560?})
[	common/pkg/backend/client.go:170 +0x3c
[common/pkg/backend.NewClient({0x100acd4b6, 0x8})
[	common/pkg/backend/client.go:165 +0x54
[common/pkg/diagkit/gather/diagnose.glob..func8()
[	common/pkg/diagkit/gather/diagnose/ipc.go:25 +0x28
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1011e3d40)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x40
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1011e3d40)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x40
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x1011e3d40)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x80
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1011e3d40, 0x14000717718)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x38
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x20?, 0x14000717718)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x74
[common/pkg/diagkit/gather/diagnose.walkOnce(0x100ca1660?, 0x1400059f890)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x1011e3cc0, 0x140002a21e0?, {0x1400059fb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x160
[main.checkCmd({0x140001aa010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0xdc
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x30c

[FAIL] DD0014: are the backend processes running? 5 errors occurred:
	* qemu-system-aarch64 is not running
	* com.docker.backend is not running
	* vpnkit-bridge is not running
	* com.docker.vpnkit is not running
	* com.docker.driver.amd64-linux is not running
```

... but it stopped at that place and has not finished still.

Activity Monitor still reports a few items that have not been killed when I initiated the "Quit Docker Desktop" command.

<img width="1079" alt="Screen Shot 2022-09-05 at 12 54 26 pm" src="https://user-images.githubusercontent.com/524259/188351858-afa96327-618b-4608-97dc-6c6ab354d488.png">

**Comment by avioli** [comment]
Quick update. Starting under a separate user on the same machine didn't help. Also tried after a restart.

**Comment by anpr** [comment]
I have the same problem. Disabling the new virtualization framework made docker for mac start again.

1. Open activity monitor, search for "docker" and Force Quit docker for desktop and all other processes.
2. Edit the file `~/Library/Group Containers/group.com.docker/settings.json`: 
```useVirtualizationFramework": false```
3. Restart the docker process (and wait a few minutes).

This fixed it, at least on my machine.

**Comment by avioli** [comment]
Thanks @anpr. That fixed it for me too.

Feel free to close this issue.

**Comment by anpr** [comment]
Good to know. I still would like to know why this fails - I would actually prefer to use the virtualization framework.

**Comment by joeforshaw** [comment]
Also ran into the same issue after updating to the latest Docker Desktop. I downgraded back to 4.11.1 and the "stopping" issue disappeared and I was able to enable the virtualisation framework again. Would be great to get a solution for this.

**Comment by djs55** [comment]
@avioli thanks for the diagnostics. The logs have something interesting:
```
[2022-09-05T02:29:49.708705000Z][com.docker.backend][I] com.docker.vpnkit with pid: 32673 shutdown by signal: segmentation fault
```
The latest development build has a fix for this issue, could you try: 
- Apple Silicon: https://desktop-stage.docker.com/mac/main/arm64/86088/Docker.dmg
- Intel: https://desktop-stage.docker.com/mac/main/amd64/86088/Docker.dmg

If it still doesn't work, could you capture diagnostics while it's in the broken state with
```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
```
and quote the new ID here? Thanks!

**Comment by DiegoGiovany** [comment]
Hi, docker diagnose stops on: 
[PASS] DD0007: is the backend responding?

<img width="746" alt="Screenshot 2022-09-06 at 18 20 43" src="https://user-images.githubusercontent.com/9576315/188740926-2b98a583-a8b2-4cf3-9be7-a1b8c582c5ff.png">

**Comment by avioli** [comment]
My working version stopped working when I quit Docker Desktop and shut it down. Once started later on today - it didn't become operational afterwards.

@djs55 I downloaded the Apple Silicon version and replaced 4.12.0 with the new build 86088, but I'm still get the same endless "stopping".

I also got the following `Fatal Error` window, saying `connecting to VPNKit on vpnkit.eth.sock: EOF`:

<img width="710" alt="Screen Shot 2022-09-07 at 2 09 11 pm" src="https://user-images.githubusercontent.com/524259/188787307-3ed31689-92ca-407e-8353-d26e13c8a961.png">

I did a "Reset Docker to factory defaults", but that didn't improve anything.

Diagnostics ID: F2606449-114C-4887-8E78-7926B365C0EE/20220907040930

**Comment by djs55** [comment]
@avioli thanks for trying the build and the diagnostics. Could you see if you have any Apple diagnostics reports from Docker processes (in particular `com.docker.vpnkit`) in `~/Library/Logs/DiagnosticReports`? If so could you attach them here? Unfortunately the current diagnostics capture doesn't include them.

**Comment by avioli** [comment]
There are 18 from yesterday which have the name of `com.docker.vpnkit-2022-09-07-HHMMSS.ips`, but there are also three, named `Docker-2022-09-07-HHMMSS.ips` which I've also included in the below archive.

[DiagnosticReports - 2022-09-07.zip](https://github.com/docker/for-mac/files/9523143/DiagnosticReports.-.2022-09-07.zip)

**Comment by djs55** [comment]
@avioli thanks for the reports, they look very interesting. For the `com.docker.vpnkit` crashes there are 2 kinds:

1. the old version of `com.docker.vpnkit` crashes like this:

```
VM Region Info: 0x16ef5bff8 is in 0x16b758000-0x16ef5c000;  bytes after start: 58736632  bytes before end: 7
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_MEDIUM (reserved)    147800000-148000000    [ 8192K] rw-/rwx SM=NUL  ...(unallocated)
      GAP OF 0x23758000 BYTES
--->  STACK GUARD                 16b758000-16ef5c000    [ 56.0M] ---/rwx SM=NUL  ... for thread 0
      Stack                       16ef5c000-16f758000    [ 8176K] rw-/rwx SM=PRV  thread 0

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   com.docker.vpnkit             	       0x100cb9a8c camlStdlib__list__map_236 + 4
1   com.docker.vpnkit             	       0x100cb9ac8 camlStdlib__list__map_236 + 64
2   com.docker.vpnkit             	       0x100d64d60 caml_callback2_exn + 60
3   com.docker.vpnkit             	       0x100d247cc fs_callback + 232
4   com.docker.vpnkit             	       0x100d2fe64 uv__work_done + 192
5   com.docker.vpnkit             	       0x100d32b98 uv__async_io + 260
6   com.docker.vpnkit             	       0x100d41218 uv__io_poll + 904
7   com.docker.vpnkit             	       0x100d32fc8 uv_run + 372
8   com.docker.vpnkit             	       0x100d17df8 uwt_run_loop + 280
9   com.docker.vpnkit             	       0x100d6fe5c caml_c_call + 28
10  com.docker.vpnkit             	       0x1007609e0 camlUwt__run_3961 + 304
```
-- it looks like it overflows the stack running a (not tail-recursive `List.map` in the filesystem watch callback).

2. the new version of `com.docker.vpnkit` crashes like this:

```
VM Region Info: 0x16b3fbff8 is in 0x167bf8000-0x16b3fc000;  bytes after start: 58736632  bytes before end: 7
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_MEDIUM (reserved)    157800000-158000000    [ 8192K] rw-/rwx SM=NUL  ...(unallocated)
      GAP OF 0xfbf8000 BYTES
--->  STACK GUARD                 167bf8000-16b3fc000    [ 56.0M] ---/rwx SM=NUL  ... for thread 0
      Stack                       16b3fc000-16bbf8000    [ 8176K] rw-/rwx SM=PRV  thread 0

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   com.docker.vpnkit             	       0x104871e04 camlStdlib__list__map_236 + 4
1   com.docker.vpnkit             	       0x104871e40 camlStdlib__list__map_236 + 64
2   ???                           	       0x148324d70 ???
```

So a very similar `List.map` call hitting a stack guard page. It might be something as simple as updating the compiler toolchain used to build these binaries, or to adjust the stack size settings. I'll investigate.

**Comment by djs55** [comment]
@avioli would you mind trying a development build of vpnkit for me? I've made a PR for moby/vpnkit and built it locally.  I've attached the binary to this comment. It has the following shasum:
```
94f54180e6918cd3dad9072fbcb7736665608c20  com.docker.vpnkit
```
[vpnkit-ocaml-4.14.zip](https://github.com/docker/for-mac/files/9528272/vpnkit-ocaml-4.14.zip)

It can be installed by:

1. stop Desktop
2. run from a terminal

```
# take a backup
mv /Applications/Docker.app/Contents/Resources/bin/com.docker.vpnkit /Applications/Docker.app/Contents/Resources/bin/com.docker.vpnkit.orig
# overwrite file
cp com.docker.vpnkit /Applications/Docker.app/Contents/Resources/bin/com.docker.vpnkit
```

3. start Desktop

Hopefully it will work better. If it doesn't, hopefully there will be an exception in the logs rather than a segfault :sweat_smile: If it fails, could you upload a diagnostic and quote the ID:

```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
```
(Just in case it goes wrong, it's worth looking for a new DiagnosticResport too)

**Comment by avsm** [comment]
Just took a look at this with @djs55 and can confirm that the OCaml 4.14 build should have a better exception on the M1 Macs than the old (4.12-based) build. Linking https://github.com/ocaml/ocaml/pull/10549#issuecomment-905296300 for the record.

**Comment by avioli** [comment]
@djs55 🥳  The new `vpnkit` did the trick and Docker (4.12.0 85629) is now running on my rig as expected. I'll monitor how things go in the following few days. I'll do some restarts just to be sure and let you know if there are any hiccups.

Thank you

**Comment by anpr** [comment]
At least on my machine, using the new vpnkit did not help for being able to active the virtualization framework again...

**Comment by djs55** [comment]
@anpr could you upload some diagnostics and quote the ID here? Also take a look to see if there are any crash reports.

There's also a known issue switching the framework on and off: perhaps try turning it on, then stopping and starting Docker (avoid the "restart" menu item, completely stop and start)

**Comment by shff** [comment]
I was still having issues with 4.12.0 85629. It only shows "Docker Desktop stopping..." for several minutes and nothing happens. vmnetd seems crashed and unresponsive.

My problem seems to be due to blocking of the domain `sessions.bugsnag.com` domain in my DNS server. After unblocking it seems to work, but that seems like a non-solution to me.

**Comment by halfpastfouram** [comment]
Experiencing the same issue here, just uploaded diagnostics: 7B32AB05-AFDB-42F9-AD70-2059500A3485/20220919085834.

**Comment by coderslagoon** [comment]
@shff That ... worked for me too, this domain (sessions.bugsnag.com) is in a common kill-file I use. That's the issue, srsly?

**Comment by coderslagoon** [comment]
> I was still having issues with 4.12.0 85629. It only shows "Docker Desktop stopping..." for several minutes and nothing happens. vmnetd seems crashed and unresponsive.
> 
> My problem seems to be due to blocking of the domain `sessions.bugsnag.com` domain in my DNS server. After unblocking it seems to work, but that seems like a non-solution to me.

That ... worked for me too, this domain (sessions.bugsnag.com) is in a common kill-file I use. That's the issue, srsly?

**Comment by andyleanlibrary** [comment]
@halfpastfouram I am experiencing the same. Tried all the above but still hanging and can only run with experimental features off.

**Comment by coderslagoon** [comment]
I repeated my experiment @andyleanlibrary ...
* enabled my DNS blocker
* Docker went into "stopping..." stall
* killed all Docker processes in Activity monitor
* disabled DNS blocker
* restarted Docker
* went into "stopped" state and then after roughly a minute fell back onto its feet

**Comment by ddbrodsky** [comment]
For me, 4.12.0 was pretty stable, but 4.13.0 started to exhibit the issue above when I upgraded to it.

**Comment by avioli** [comment]
Just upgraded to 4.13.0 and it seems to be working fine for me. I'll keep you posted if anything changes.

**Comment by halfpastfouram** [comment]
My trouble also seems to have been fixed in 4.13.0.

**Comment by cassus** [comment]
> For me, 4.12.0 was pretty stable, but 4.13.0 started to exhibit the issue above when I upgraded to it.

Same here.

Even after installing the development build of vpnkit from https://github.com/docker/for-mac/issues/6472#issuecomment-1240891261

**Comment by internetcoffeephone** [comment]
Also experiencing this issue on Docker Desktop 4.13.0, MacOS 12.6 with Intel chip.
New virtualization framework is not enabled.

The docker container with image 

`2022-10-26 12:02:42.449320+0200  localhost com.docker.backend[23950]: com.docker.vpnkit with pid: 23986 shutdown by signal: segmentation fault`

**Comment by internetcoffeephone** [comment]
I was getting the same error on MacOS 12.6, Docker Desktop 4.13.0, Intel chip, no new virtualization framework enabled.

I would run the image
`docker run -it --user=0 debezium/connect:2.0.0.Final /bin/bash`

Then inside the container
```
bash-5.1# microdnf install vim -y
Downloading metadata...
Downloading metadata...
ERRO[0069] error waiting for container: invalid character 'c' looking for beginning of value
```
At this point the container exits and Docker Desktop goes into the Stopping state, from which it does not recover unless restarted.

The Docker Desktop logs would contain the error
`localhost com.docker.backend[23950]: com.docker.vpnkit with pid: 23986 shutdown by signal: segmentation fault`

Seems to be resolved for me by downgrading to Docker Desktop 4.12.0.

**Comment by ickeundso** [comment]
Also here MacOS 12.6 (21G115) on M1 
Docker Desktop: 4.13.0 (89412)
Engine: 20.10.20

Compose: 1.29.2

Credential Helper: v0.7.0

Kubernetes: v1.25.2

Snyk: v1.1025.0

got this :
 => ERROR [internal] load metadata for docker.io/library/aws-nginx:arm                                                                                                1.3s
------
 > [internal] load metadata for docker.io/library/aws-nginx:arm:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
- container-name-1 Error
- container-name-2 Error
- ...
Error response from daemon: pull access denied for container-name-2, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
..
Error response from daemon: Bad response from Docker engine

the the engine tries to stop , but without luck. Have to kill the docker processes with kill

**Comment by partymike** [comment]
same issue here

Macmini M1, 16GB, 2020
Ventura 13.0

Reverted to docker desktop 4.12.0 & had no further issues with docker "stopping"

**Comment by Brassrat** [comment]
Started having the same problem when i installed 4.13 on Intel MACOS 12.6.1

**Comment by ddbrodsky** [comment]
I downgraded to 4.12 and docker became much more stable again.  This is on an MacBook Pro, M1 Max, 64GB, Ventura 13.0.  Original comment above: https://github.com/docker/for-mac/issues/6472#issuecomment-1287976686

**Comment by kanintesova** [comment]
Having the same problems. Will try 4.12. Thanks.

**Comment by partymike** [comment]
new release of docker 4.13.1 fix's the issue for me - its also referenced in the release notes.

**Comment by kanintesova** [comment]
At first just overwriting the docker app with the new version I got a bit down as it was still the same problem. But a classic reboot fixed it. So, yes. I'd say it's fixed.

**Comment by yours-truly-phil** [comment]
Fyi, v4.13.1 didn't fix the issue for me. I'm running it on the M1 Max 64GB Ventura 13.0.

Docker Desktop runs for a couple hours but eventually it will always get stuck in a state " ... is stopping". I didn't trigger a restart or stop or quit the app, it just seems to, at some point, always switch from running to the "... is stopping" state where it becomes unresponsive.

To get it running again I open the Activity Monitor, search for 'docker', select all processes and force quit them. Then I can start Docker Desktop again and it'll run and work for a couple hours.

**Comment by letranloc** [comment]
v4.13.1 also didn't fix the issue for me
I think I will downgrade to v4.12 and wait for the next fixed version

**Comment by gauravojha** [comment]
I second @yours-truly-phil's comment above. I am on 4.13.1 as well. And I face the same thing, it runs fine for a couple of hours, then it enters the "Docker is stopping" stage. I also end up having to do the steps here: https://forums.docker.com/t/cannot-get-docker-working-in-macbook-pro-m1/120810/5 at times, when a docker restart complains something about `com.docker.backend` failed to start

**Comment by codethought** [comment]
> @avioli thanks for the diagnostics. The logs have something interesting:
> 
> If it still doesn't work, could you capture diagnostics while it's in the broken state with
> 
> ```
> /Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
> ```
> 
> and quote the new ID here? Thanks!

@djs55 

I just updated to 4.13.1 from a 4.12 release and am experiencing the same issue with Apple Silicon - disabling the new virtualization framework as per @anpr 's suggestion seems to have worked. 

```
~/Library/Group Containers/group.com.docker/settings.json:useVirtualizationFramework": false
```

I'll continue to watch..

If it works.. I can still switch it back on, run a diagnose command as you describe above and share the ID here if you would still find that of use.

**Comment by jankkm** [comment]
Still happening on 4.14
I just set useVirtualizationFramework to _false_, I hope that makes it work again.

**Comment by codethought** [comment]
@jankkm  - just failed for me - again. I'm running the `diagnose gather -upload` command now..

**Comment by codethought** [comment]
@djs55  I ran the diagnostics upload... hopefully something useful can be found..


727A54BA-58D6-456D-8A44-33609933ADC9/20221113154118

**Comment by kettenbach-it** [comment]
Did this:
```
❯ wget https://raw.githubusercontent.com/Homebrew/homebrew-cask/75b270f1e8c1efead74a7ccb1d6139661fd15e89/Casks/docker.rb
[...]
❯ brew reinstall --cask docker.rb
[...]
❯ brew cu pin docker
Pinned: docker in version 4.12.0,85629
```
and got docker downgraded to 4.12.0
We'll see if this is stable

**Comment by ddbrodsky** [comment]
So Interestingly enough, 4.12.0 was stable, 4.13.0 was not stable, 4.13.1 was stable, 4.14.0 is not stable again.

**Comment by jankkm** [comment]
> So Interestingly enough, 4.12.0 was stable, 4.13.0 was not stable, 4.13.1 was stable, 4.14.0 is not stable again.

I don’t think 4.13.1 was stable for me. I am not sure if I tried it though and I don’t want to now. I‘m back to 4.12 with no issue since.

**Comment by emadabdulrahim** [comment]
Still hangs for me after upgrading to `4.14.1 (91661)` on m1 Max running macOS Monterey

**Comment by jesseinit** [comment]
> Still hangs for me after upgrading to `4.14.1 (91661)` on m1 Max running macOS Monterey

Same for me.

**Comment by kurt-mueller-osumc** [comment]
I downgraded back Docker Desktop 4.12 to get my docker setup working properly again.

**Comment by hmphu** [comment]
> I downgraded back Docker Desktop 4.12 to get my docker setup working properly again.

Thank you, this works

**Comment by squarewave24** [comment]
same issue on 4.13.0 (89412) 
Monterey 12.6 (21G115)

one shortcut to activity monitor is you can just run this commond:
```sudo pkill -f Docker```

i also confirmed /Users/rafal.buch/Library/Group Containers/group.com.docker/settings.json
```
  "useVirtualizationFramework": false,
  "useVirtualizationFrameworkVirtioFS": false,
  ```

but this issue still comes up at least once a day.

**Comment by jankkm** [comment]
I've been running v4.15 for more than 24 hours without issues on an M1 MacMini with macOS 12.6.1. This problem might actually be fixed.

```
"useVirtualizationFramework": true,
"useVirtualizationFrameworkVirtioFS": false,
```

**Comment by wivaku** [comment]
Similar to: https://github.com/docker/for-mac/issues/6530 and #6435 

VPNKit is looking at EXC_BAD_ACCESS (SIGSEGV) issue: https://github.com/moby/vpnkit/issues/610

**Comment by ddbrodsky** [comment]
still happening to me on 4.15.0.  Macbook Pro M1 Max (Ventura).  4.12.0 is very stable.

**Comment by thuongtin** [comment]
> still happening to me on 4.15.0. Macbook Pro M1 Max (Ventura). 4.12.0 is very stable.

I agree

**Comment by scpedicini** [comment]
`EXC_BAD_ACCESS (SIGSEGV)` once again using the newest Docker 4.15.0 - lasts roughly 8 hours before it inexplicably crashes. Mac Monterey 12.6 on MacBook M1 Pro.

**Comment by wivaku** [comment]
No longer seeing the issue in the latest build mentioned here: https://github.com/docker/for-mac/issues/6530#issuecomment-1344029769

**Comment by codethought** [comment]
> @avioli thanks for the diagnostics. The logs have something interesting:
> 
> ```
> [2022-09-05T02:29:49.708705000Z][com.docker.backend][I] com.docker.vpnkit with pid: 32673 shutdown by signal: segmentation fault
> ```
> 
> (This may be related to [#6435 (comment)](https://github.com/docker/for-mac/issues/6435#issuecomment-1232921520) )
> 
> The latest development build has a fix for this issue, could you try:
> 
> * Apple Silicon: [desktop-stage.docker.com/mac/main/arm64/86088/Docker.dmg](https://desktop-stage.docker.com/mac/main/arm64/86088/Docker.dmg)
> * Intel: [desktop-stage.docker.com/mac/main/amd64/86088/Docker.dmg](https://desktop-stage.docker.com/mac/main/amd64/86088/Docker.dmg)
> 
> If it still doesn't work, could you capture diagnostics while it's in the broken state with
> 
> ```
> /Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
> ```
> 
> and quote the new ID here? Thanks!

Can you please look at this diagnostic and see what might be going on? ID 727A54BA-58D6-456D-8A44-33609933ADC9/20221209161131 

I cannot get docker desktop running at all now.. not with 4.12 or 4.15

Thanks.

**Comment by bclodius** [comment]
A colleague and I are also having this issue on our m1 mac's.  Docker for desktop will be running fine for a few hours - dozens of hours then suddenly moby icon is continuously "loading" and below status remains.

![image](https://user-images.githubusercontent.com/590724/207171701-a6b99b0b-da9a-474d-a2ba-fc19928ba9b3.png)

We are both having `Version: 4.15.0 (93002)`.

Once in this state I must forcefully kill and restart Docker thru Activity Monitor because the menu does not respond to most selections.

**Comment by nomansadiq11** [comment]
force to quit all the process resolve my issue. 

<img width="964" alt="image" src="https://user-images.githubusercontent.com/15877110/207364069-d075611a-dba1-4e70-a9dc-31b933c3df34.png">

**Comment by jankkm** [comment]
> No longer seeing the issue in the latest build mentioned here: [#6530 (comment)](https://github.com/docker/for-mac/issues/6530#issuecomment-1344029769)

I upgraded to the 4.16 test build 4 days ago and it seems stable.

**Comment by azelianouski** [comment]
Same issue for me on 4.15. It works for about 30 min, then freezes until I kill all docker processed.
I downgraded to 4.12, it is stable. Looks like need to wait for 4.16 release.

**Comment by codethought** [comment]
> > No longer seeing the issue in the latest build mentioned here: [#6530 (comment)](https://github.com/docker/for-mac/issues/6530#issuecomment-1344029769)
> 
> I upgraded to the 4.16 test build 4 days ago and it seems stable.

Where do I find test builds? I'm desperate.. I've even completely deleted everything from my system related to docker desktop or docker CLI tools and still it's crashing on me..

**Comment by jankkm** [comment]
> > > No longer seeing the issue in the latest build mentioned here: [#6530 (comment)](https://github.com/docker/for-mac/issues/6530#issuecomment-1344029769)
> > 
> > 
> > I upgraded to the 4.16 test build 4 days ago and it seems stable.
> 
> Where do I find test builds? I'm desperate.. I've even completely deleted everything from my system related to docker desktop or docker CLI tools and still it's crashing on me..

[arm64](https://desktop-stage.docker.com/mac/main/arm64/93533/Docker.dmg) 
[amd64](https://desktop-stage.docker.com/mac/main/amd64/93533/Docker.dmg)

**Comment by simonc** [comment]
Hi. As far as I'm concerned, the issue is fixed since v4.15.

**Comment by hackzilla** [comment]
Failing quicker for me with v4.15

In crashed state:
Diagnostics ID:     0F8EA56C-41AD-4621-8AFF-5BF89388FAFD/20221220172348 (uploaded)

Reloaded after crashed state:
Diagnostics ID:     0F8EA56C-41AD-4621-8AFF-5BF89388FAFD/20221220174844 (uploaded)

**Comment by dypublic** [comment]
Still not work for me. Docker v4.15, macos 12.6 amd64.
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": dial unix diagnosticd.sock: connect: no such file or directory
[2022-12-21T02:26:59.275832000Z][com.docker.diagnose][I] ipc.NewClient: b28ce8e4-diagnose -> diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func12()
[	common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x8c
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x100d5b940)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x100d5b940)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x4?, 0x100d5b940)
[	common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x100d5b940, 0xc000707720)
[	common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x100d5b9c0, 0xc000707720)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x100d5bac0, 0xc000707720)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100d5bd40, 0xc000707720)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x10070dba0?, 0xc00059f888)
[	common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x100d5bd40, 0x600?, {0xc00059fb18, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0001b4010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x2a7
[2022-12-21T02:26:59.277789000Z][com.docker.diagnose][I] (3c4e0fd8) b28ce8e4-diagnose C->S diagnosticsd GET /ping
[2022-12-21T02:26:59.290430000Z][com.docker.diagnose][W] (3c4e0fd8) b28ce8e4-diagnose C<-S NoResponse GET /ping (12.612439ms): Get "http://ipc/ping": dial unix diagnosticd.sock: connect: no such file or directory

[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-12-21T02:26:59.294327000Z][com.docker.diagnose][I] ipc.NewClient: 8da2618c-com.docker.diagnose -> lifecycle-server.sock VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:61
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x1007d34b4, 0x13})
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:55 +0x99
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[	common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x29
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x100d5b9c0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x100d5b9c0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x3?, 0x100d5b9c0)
[	common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x100d5b9c0, 0xc000707720)
[	common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x100d5bac0, 0xc000707720)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100d5bd40, 0xc000707720)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x10070dba0?, 0xc00059f888)
[	common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x100d5bd40, 0x600?, {0xc00059fb18, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0001b4010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x2a7
[2022-12-21T02:26:59.296314000Z][com.docker.diagnose][I] (7cac238e) 8da2618c-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2022-12-21T02:26:59.297071000Z][com.docker.diagnose][W] (7cac238e) 8da2618c-com.docker.diagnose C<-S NoResponse GET /docker (745.256µs): Get "http://ipc/docker": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-12-21T02:26:59.297911000Z][com.docker.diagnose][I] (7cac238e-1) 8da2618c-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-21T02:26:59.298881000Z][com.docker.diagnose][W] (7cac238e-1) 8da2618c-com.docker.diagnose C<-S NoResponse GET /ping (962.007µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-12-21T02:27:00.300728000Z][com.docker.diagnose][I] (7cac238e-2) 8da2618c-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-21T02:27:00.301760000Z][com.docker.diagnose][W] (7cac238e-2) 8da2618c-com.docker.diagnose C<-S NoResponse GET /ping (1.022919ms): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-12-21T02:27:01.302703000Z][com.docker.diagnose][I] (7cac238e-3) 8da2618c-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-21T02:27:01.303644000Z][com.docker.diagnose][W] (7cac238e-3) 8da2618c-com.docker.diagnose C<-S NoResponse GET /ping (935.058µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-12-21T02:27:02.304265000Z][com.docker.diagnose][I] (7cac238e-4) 8da2618c-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-21T02:27:02.305182000Z][com.docker.diagnose][W] (7cac238e-4) 8da2618c-com.docker.diagnose C<-S NoResponse GET /ping (901.329µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-12-21T02:27:03.305817000Z][com.docker.diagnose][I] (7cac238e-5) 8da2618c-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-21T02:27:03.306785000Z][com.docker.diagnose][W] (7cac238e-5) 8da2618c-com.docker.diagnose C<-S NoResponse GET /ping (976.585µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-12-21T02:27:04.307606000Z][com.docker.diagnose][I] (7cac238e-6) 8da2618c-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-21T02:27:04.308632000Z][com.docker.diagnose][W] (7cac238e-6) 8da2618c-com.docker.diagnose C<-S NoResponse GET /ping (1.017098ms): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-12-21T02:27:05.309377000Z][com.docker.diagnose][I] (7cac238e-7) 8da2618c-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-21T02:27:05.310059000Z][com.docker.diagnose][W] (7cac238e-7) 8da2618c-com.docker.diagnose C<-S NoResponse GET /ping (678.425µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-12-21T02:27:06.311324000Z][com.docker.diagnose][I] (7cac238e-8) 8da2618c-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-21T02:27:06.312246000Z][com.docker.diagnose][W] (7cac238e-8) 8da2618c-com.docker.diagnose C<-S NoResponse GET /ping (915.194µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?
[PASS] DD0013: is the $PATH ok?

**Comment by jimmygchen** [comment]
Same issue for me in v4.15.

Seems like a lot of people reported that it's fixed in the test build:

- [amd64](https://desktop-stage.docker.com/mac/main/amd64/93533/Docker.dmg)
- [arm64](https://desktop-stage.docker.com/mac/main/arm64/93533/Docker.dmg)

Source: https://github.com/docker/for-mac/issues/6530#issuecomment-1344029769

**Comment by jesseinit** [comment]
I'm still holding on 4.12

**Comment by LoganInTX** [comment]
I just tested 4.15 as well and get the same crash behavior as soon as something tries to download via SABNZBD.
Back to 4.12 and all is good.

**Comment by sahsu** [comment]
I got same issue in 2012 mac mini with v4.15, now I am using v4.12 with no problem at all over 12hrs.

**Comment by codethought** [comment]
Well,  I have good news and bad news..

4.15 works fine for me.. UNLESS I run my docker compose of filerun and do any indexing.. after about 30-60 minutes it will crash..  Strange that prior to 4.12 I didn't see this problem at all.. I figure at this point it is a configuration issue with Docker Desktop... if anyone has any suggestions this is my docker-compose file for filerun.. 

```yml
version: '2'
 
services:
  db:
    image: mariadb:10.1
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: xxx
      MYSQL_PASSWORD: yyy
      MYSQL_DATABASE: zzz
    volumes:
      - /Volumes/NASStorage/Docker/filerun/db:/var/lib/mysql
  web:
    image: filerun/filerun
    restart: always
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: XXX
      FR_DB_USER: YYY
      FR_DB_PASS: ZZZ
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db
      - tika
      - elasticsearch
    ports:
      - "5080:80"
    volumes:
      - /Volumes/NASStorage/Docker/filerun/html:/var/www/html
      - /Volumes/NASStorage/Documents:/user-files
      - /Volumes/NASStorage/Sourcecode:/sourcecode
  tika:
    image: logicalspark/docker-tikaserver
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    restart: always
    expose:
      - "9200"
    privileged: true
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - bootstrap.system_call_filter=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - /Volumes/NASStorage/Docker/filerun/esearch:/usr/share/elasticsearch/data

```

**Comment by bclodius** [comment]
Sad update `v4.16` has crashed for me in the similar fashion `v4.15` was crashing 😢 .   I downloaded and installed from [arm64](https://desktop-stage.docker.com/mac/main/arm64/93533/Docker.dmg).

**Comment by healchow** [comment]
> Same issue for me in v4.15.
> 
> Seems like a lot of people reported that it's fixed in the test build:
> 
> * [amd64](https://desktop-stage.docker.com/mac/main/amd64/93533/Docker.dmg)
> * [arm64](https://desktop-stage.docker.com/mac/main/arm64/93533/Docker.dmg)
> 
> Source: [#6530 (comment)](https://github.com/docker/for-mac/issues/6530#issuecomment-1344029769)

Great🎉 On my MacBook Pro with Apple M1 chip and Ventrua 13.1 OS, the test build works good for me✌️

**Comment by jankkm** [comment]
> Sad update `v4.16` has crashed for me in the similar fashion `v4.15` was crashing 😢 . I downloaded and installed from [arm64](https://desktop-stage.docker.com/mac/main/arm64/93533/Docker.dmg).

 I switched to [colima](https://github.com/abiosoft/colima). This may be the way to go for you too.

**Comment by cliss** [comment]
> I switched to [colima](https://github.com/abiosoft/colima). This may be the way to go for you too.

Can confirm — colima got me sorted.

**Comment by kettenbach-it** [comment]
Was already thinking about alternatives, too. Will try colima. Can it co-exist with docker-desktop? Does it work with docker-compose?

Are there any other alternatives?

**Comment by jankkm** [comment]
> Was already thinking about alternatives, too. Will try colima. Can it co-exist with docker-desktop? Does it work with docker-compose? Do you run it with containerd instead of docker (probably yes, otherwise you'd still have the problem with docker crashing)
> 
> Are there any other alternatives?

I don't think it would work well alongside docker desktop. On my Mac I uninstalled docker desktop from the gui and installed docker, docker-compose and colima with brew. It does not have the problem with crashes for me.
I have not checked out containerd and I don't know if it is a good idea to use it instead of docker.

**Comment by kettenbach-it** [comment]
Thanks for this info. I also just learned that there is a "brew cask" called "docker" (which is then the docker desktop that has the problem) and a package called "docker" - which is the docker runtime and cli that colima needs.
So I will uninstall my cask and install the package and see if colima will do the job better

**Comment by derekperkins** [comment]
Also seeing this on 4.15.0 on Intel 2019 MBP on Ventura 13.1

**Comment by jankkm** [comment]
> > I switched to [colima](https://github.com/abiosoft/colima). This may be the way to go for you too.
> 
> Can confirm — colima got me sorted.

My switching was actually thanks to you talking about it on your show ☺️

**Comment by yatesjr** [comment]
Adding another point to https://github.com/abiosoft/colima, I've switched as well because of this crashing issue. So far so good!

**Comment by jesseinit** [comment]
Curious to know what changed after the v4.12 release that has made it so unstable. I'm still riding with 4.12 for now until my requirements changes.

**Comment by kennethredler** [comment]
> @anpr could you upload some diagnostics and quote the ID here? Also take a look to see if there are any crash reports.
> 
> There's also a known issue switching the framework on and off: perhaps try turning it on, then stopping and starting Docker (avoid the "restart" menu item, completely stop and start)

@djs55 any news here? Still seeing this with build from #6530 ... didn't try vpnkit yet

Please let me (us) know if we can support with any testing. Thanks!

**Comment by bclodius** [comment]
> @djs55 any news here? Still eventually seeing "Docker is stopping" with build from #6530 ... didn't try vpnkit yet.
> 
> FWIW, diag check fails like this (all other tests pass) on my M1 Ventura 13.1 w/ 6530 build even while things appear to be working. (before they eventually fail)
> 
> <img alt="image" width="1441" src="https://user-images.githubusercontent.com/22832065/210083168-8fca8902-8bee-46fd-9637-02aaf0c13ef3.png">
> 
> Please let me (us) know if we can support with any testing. Thanks!

From my perspective the diagnostics tools do not help here because Docker has already crashed and will not gracefully respond to ANYTHING.  I always have to pull up activity monitor and force quit Docker.

**Comment by hikerwu** [comment]
there is the same issue at 4.15.0 version

**Comment by wslawski-printify** [comment]
For me it happens when there is some inactivity on mac and I go back to it, I have to just reboot to fix it, but it's kind of annoying.

**Comment by ianjukes** [comment]
> For me it happens when there is some inactivity on mac and I go back to it, I have to just reboot to fix it, but it's kind of annoying.

This is the same behaviour I am seeing as well. I have an Apple Mac Studio M1 Max running Ventura 13.1, and after a period of inactivity (stepping away from the computer), I will see the animated whale in the menu bar and a "Docker Desktop is stopping" message.

I am running 4.15.0.

Interestingly, I also have a MacBook Pro M1 Pro (also running Ventura 13.1) and I do not see the same issue there. 🤷‍♂️

**Comment by wslawski-printify** [comment]
For me actually it happens also on Macbook Pro with M1, running macOS 13.1

**Comment by wslawski-printify** [comment]
@ianjukes for me it's also kind of random, but defintely happening so far if there is some inactvity on my mac, but not always.

**Comment by verluci** [comment]
Still experiencing this on a 2018 Mac Mini with i7, MacOS 13.0.1. It doesn't correlate to inactivity for me, it just happens after a short period of running. 
This is made all the more frustrating by Docker seemingly randomly deciding to update itself. I'm 95% certain I turned off "Always download updates" a month ago (exactly a month ago even, a month before that it also randomly updated), and even then, I don't understand why that setting also _applies_ the update.

**Comment by jesseinit** [comment]
I'm stuck on 4.12.0 with auto check for updates and download options turned off.

**Comment by bclodius** [comment]
I tried the test build `4.16.0 (94771)`. It already crashed for me in less than 24 hours.  I was previously testing `4.16.0 (93533)` which was also crashing after some extended time.

**Comment by roksprogar** [comment]
So many comments on crashes (I'm sticking with 4.12 for the time being), but are any of the developers even looking into this issue?

**Comment by kettenbach-it** [comment]
Switched to colima.
The tool offers exactly what I need: compatible with docker and docker-compose as well as buildx.
Simple cli interface with autocompletions.
Direct ssh into the VM possible.
Everything else that Docker Desktop had, I don't need anyway and maybe it even is more annoying than useful.

**Comment by aguedeney** [comment]
For those interested in a good summarization.  I'm much happier using Colima.
https://kumojin.com/en/colima-alternative-docker-desktop/

**Comment by ddbrodsky** [comment]
An interesting data point.  I run Docker Desktop on a system that uses either AnyConnect or ZScalar to connect to a VPN.  I have been mostly using ZScalar and since 4.12 I have been seeing the above issue.  In the last couple of days I switched to AnyConnect and Docker Desktop has been stable for over 24 hours now.  Could the issue be a networking problem?

**Comment by ianjukes** [comment]
@verluci @ddbrodsky Another bit of evidence pointing to it being in the realm of a network/update issue. I am running 4.15 and have turned off **Automatically check for updates** and **Always download updates** and so far its been stable.

**Comment by kennethredler** [comment]
> An interesting data point. I run Docker Desktop on a system that uses either AnyConnect or ZScalar to connect to a VPN. I have been mostly using ZScalar and since 4.12 I have been seeing the above issue. In the last couple of days I switched to AnyConnect and Docker Desktop has been stable for over 24 hours now. Could the issue be a networking problem?

💡Zscalar is also in play for me. 🤔 I'm assuming that may be why I saw the diagnostic failure captured in the screenshot I shared above.

I might try disabling the checks @ianjukes mentioned to see if that stabilizes things for me as well.

**Comment by codethought** [comment]
I've tried both Rancher desktop and colima- and both completely reset all of my configurations when a restart occurs.. it's like they have no idea that I ever configured any of my containers and the ones I have tried so far all act like they are brand new container configurations... 

I'll stick to and fight with Docker Desktop a bit longer..

**Comment by ianjukes** [comment]
> I might try disabling the checks @ianjukes mentioned to see if that stabilizes things for me as well.

@kennethredler Did disabling updates work for you? I can confirm, when I re-eneabled automatically checking for updates, that the problem returned.

**Comment by zhiweio** [comment]
> > I might try disabling the checks @ianjukes mentioned to see if that stabilizes things for me as well.
> 
> @kennethredler Did disabling updates work for you? I can confirm, when I re-eneabled automatically checking for updates, that the problem returned.
> 
> EDIT: I can also confirm when I disabled the automatic check for updates, Docker Desktop is completely stable again. I have a Mac Studio M1 Max running Ventura 13.1.

It works for me 👍

**Comment by ianjukes** [comment]
Thank you @zhiweio - that's good to know.

So to the Docker Desktop team: it would appear that something about the automated update process, particularly when it tries to call back across the Internet, is causing Docker Desktop to fail in certain conditions.

**Comment by kennethredler** [comment]
> > > I might try disabling the checks @ianjukes mentioned to see if that stabilizes things for me as well.
> > 
> > 
> > @kennethredler Did disabling updates work for you? I can confirm, when I re-eneabled automatically checking for updates, that the problem returned.
> > EDIT: I can also confirm when I disabled the automatic check for updates, Docker Desktop is completely stable again. I have a Mac Studio M1 Max running Ventura 13.1.
> 
> It works for me 👍

Yeah, I haven't seen Docker go out to lunch since disabling auto version check. ZScalar is still in play for me, FWIW. FYI @djs55

**Comment by derekperkins** [comment]
I upgraded to v4.16.1 (95567), disabled auto version checks and downloads, and it still dies on me the same as before

**Comment by ianjukes** [comment]
> I upgraded to v4.16.1 (95567), disabled auto version checks and downloads, and it still dies on me the same as before

@derekperkins Do you have any extensions enabled by any chance?

**Comment by derekperkins** [comment]
Yes, I had Disk Usage and Performance extensions from Docker installed and running. I just disabled extensions, so we'll see how long I go before Docker dies again.

**Comment by ianjukes** [comment]
> Yes, I had Disk Usage and Performance extensions from Docker installed and running. I just disabled extensions, so we'll see how long I go before Docker dies again.

@derekperkins I suspect that will be the issue, as I enabled extensions and the problem returned. I think the extensions system also makes a network call back to Docker to check if there are updates to the extensions. My hunch is something is broken with the update system. I have also disabled extensions to see if its stable again. Fingers crossed! 🤞

**Comment by wslawski-printify** [comment]
Seems like disabling automatic updates fixed issue for me as well.

**Comment by fortran01** [comment]
> An interesting data point. I run Docker Desktop on a system that uses either AnyConnect or ZScalar to connect to a VPN. I have been mostly using ZScalar and since 4.12 I have been seeing the above issue. In the last couple of days I switched to AnyConnect and Docker Desktop has been stable for over 24 hours now. Could the issue be a networking problem?

I have Tailscale. I haven't tested yet by disabling Tailscale but putting this info just in case others have the same environment.

**Comment by jfbourne** [comment]
Im on a Mac Mini Intel i7 2012, disabling the update also seem to have fixed the issue for me. 🤞

Fyi: Additionally I disabled extension and everything else I don’t need lol

**Comment by Cromm** [comment]
Mac M1 Mini running Ventura 13.0.1
Docker Desktop 4.15
I switched off auto-update following reading this thread a few days ago. Ran smoothly for 3-4 days then the '..is stopping' issue recurred.

I'm now updating to 4.16.1 and disabling extensions...I'll report back. 
Thanks to all for documenting issue and possible fixes!

**Comment by HawaiiRyan** [comment]
4.16.1 with auto-update disabled with the Portainer + Logs Explorer extensions installed works fine on Ventura 13.1 w/ Intel processor.

**Comment by derekperkins** [comment]
@ianjukes 4.16.1 with extensions disabled and with auto-updates disabled still died on me today

**Comment by ianjukes** [comment]
> @ianjukes 4.16.1 with extensions disabled and with auto-updates disabled still died on me today

That's a real shame - I figured that would be it. Just to verify, you have uninstalled all extensions, and then unchecked the 'Enable Docker Extensions' option in the settings?

<img width="858" alt="Screenshot 2023-01-18 at 9 18 45 am" src="https://user-images.githubusercontent.com/6738441/213132067-080b7827-eecf-4416-8d3f-d7a2f0615eb5.png">

I have uninstalled and disabled extensions, and I'm stable again. At least so far.

**Comment by andyleanlibrary** [comment]
My company recently uninstalled Symantec from the mac.  It's been a lot better since then but not sure if its related.
Do you all have strict firewalls/protection set up? If so, could it be that it's interfering with the auto-update?

**Comment by ianjukes** [comment]
@andyleanlibrary I'm at home with quite a simple network set up, and do not have any antivirus software installed. Docker should be stable. 🤷‍♂️

**Comment by Cromm** [comment]
@andyleanlibrary yes, similar setup to ianjukes - domestic install without antivirus. Extensions was activated but I don't believe there were any installed at any point before I de-activated extensions - I can check later.

**Comment by andyleanlibrary** [comment]
@ianjukes thanks - good to rule it out, if only for me :-)

**Comment by jfbourne** [comment]
Even with extensions disabled, mine still stoped. Ran well for 22 hours Only. I’m on 4.15.1

Apparently is supposed to be fixed in 4.16 but I have not tried it yet 

https://github.com/docker/for-mac/issues/6606#issuecomment-1386272617

**Comment by derekperkins** [comment]
@nicks why would you close this issue with plenty of people still reporting issues even on 4.16? It's clearly not solved, and there's no repro steps other than it just dying after being open for a while.

**Comment by derekperkins** [comment]
FWIW, experimental features were enabled for me on 4.16.1. I don't remember enabling them recently, but it's very possible I manually did it 1+ years ago. It's now turned off to see if maybe that was causing it to crash.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/3588778/213287155-35feb96b-c7d1-4ec3-ac2c-9a3c72b11cf6.png">

**Comment by nicks** [comment]
@derekperkins re: "there's no repro steps other than it just dying after being open for a while." here's a good page on how to upload diagnostics when you don't have repro steps - https://docs.docker.com/desktop/troubleshoot/overview/#diagnose

re: "why would you close this issue with plenty of people still reporting issues even on 4.16?" - that's a very philosophical question! why would we close one bug when there are still other bugs that cause the same symptoms? I like this old-internet post - https://www.chiark.greenend.org.uk/~sgtatham/bugs.html
