### ISSUE TITLE
Sorry, something went wrong when uninstalling Docker: failed to remove preference keys from docker preferences

### ISSUE THREAD

**Issue by QianXuX** [docker/for-mac#651]
### Expected behavior
Uninstall docker on Mac.

### Actual behavior
Uninstallation failed. Error message:
Sorry, something went wrong when uninstalling Docker: failed to remove preference keys from docker preferences

### Information
I have installed docker with the latest OS X version 10.12 Beta, now I tried to uninstall docker.
If I reopen docker now, I will get this error message occasionally:
Internal error: failed to update machine migration state

I have run a diagnose after docker.app starts and suggest that it is time to run "docker version", it give following:
➜  service git:(master) ✗ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64
Error response from daemon: Bad response from Docker engine
➜  service git:(master) ✗ docker ps
Error response from daemon: Bad response from Docker engine

### Diagnose
Diagnostic ID: 964AF3E8-E98E-46E1-B03E-92E5516901C9
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/Qian/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/964AF3E8-E98E-46E1-B03E-92E5516901C9/20160916-013854/qemu-img-check.stdout 2> /tmp/964AF3E8-E98E-46E1-B03E-92E5516901C9/20160916-013854/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce the behavior

Open docker menu bar icon, from Preference select uninstall.

**Comment by djs55** [comment]
The macOS 10.12 Sierra builds trigger some bugs in Docker for Mac 1.12.0 -- including this one -- which have been fixed in the Docker for Mac beta channel. There will be an update of Docker for Mac stable before Sierra is released to the general public.

To uninstall Docker for Mac manually:
```
# remove the privileged component (if still installed)
rm -f /Library/PrivilegedHelperTools/com.docker.vmnetd
sudo launchctl remove com.docker.vmnetd

# remove container data
rm -rf ~/Library/Containers/com.docker.docker

# remove application preferences
rm -rf ~/Library/Group\ Containers/group.com.docker/
```
Then drag the application to trash.

**Comment by MagnusS** [comment]
This macOS Sierra issue is resolved in stable 1.12.1 which was released today and in beta26 released earlier this week. To uninstall the previous version you may use the manual instructions posted above, or alternatively install the latest release and then select "Preferences" -> "Uninstall" and drag the application to trash.

**Comment by QianXuX** [comment]
Docker version 1.12.1 still have issues with Docker daemon when I type "docker ps", but it has solved the uninstallation issue. So I have uninstalled by selecting "Preferences" -> "Uninstall" and drag the application to trash. 

I am using Docker beta version now and it seems that it is working great. The download link is  https://download.docker.com/mac/beta/Docker.dmg. If you are comfortable with a beta version, you should try that out.
