### ISSUE TITLE
Cannot bind to specific IPs: cannot assign requested address.

### ISSUE THREAD

**Issue by Ran-Xing** [docker/for-mac#6510]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip: 20.10.17
  - Docker Desktop Version: 4.12.0 (85629)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```log
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-10-10T02:22:39.314836000Z][com.docker.diagnose][I] ipc.NewClient: 93574f34-diagnose-network -> diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xc8
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x10531bb40)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x40
[common/pkg/diagkit/gather/diagnose.Run.func1(0x10531bb40)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x40
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x10531bb40)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x80
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x10531bb40, 0x140006b3718)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x38
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x20?, 0x140006b3718)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x74
[common/pkg/diagkit/gather/diagnose.walkOnce(0x104dd9660?, 0x1400059f890)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x10531bcc0, 0x0?, {0x1400059fb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x160
[main.checkCmd({0x140001aa010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0xdc
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x30c
[2022-10-10T02:22:39.315491000Z][com.docker.diagnose][I] (bae7ed67) 93574f34-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["192.168.0.101"]}
[2022-10-10T02:22:39.836718000Z][com.docker.diagnose][W] (bae7ed67) 93574f34-diagnose-network C<-S c256bd57-diagnosticsd POST /check-network-connectivity (521.246417ms): failed to ping host: exit status 1

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.
```

### Steps to reproduce the behavior

- #4209

- https://stackoverflow.com/questions/74009668/docker-port-bind-docker0-failed-on-macos

Is this problem solved? Currently my Docker still has this error

**Comment by nicks** [comment]
Hi! The problem you linked to is solved. I'm going to close this ticket, because there's not enough information to reproduce your issue or determine if it's even related to the one you linked to.

**Comment by Ran-Xing** [comment]
@nicks 
This problem is still there, I just found a historical issues
