### ISSUE TITLE
invalid character 's' looking for beginning of value

### ISSUE THREAD

**Issue by Yalchin403** [docker/for-mac#6575]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 37BCADF4-8FCF-4E92-B2F6-C0DDA2AFA113/20221115000422

### Expected behavior
I would normally expect my containers and docker to be running without a problem.
### Actual behavior
It usually doesnt happen with my other project set up, it only happens with one of my projects. But this problem doesnt happen in my windows with the exactly same setup. Once I start containers, after some time docker icon starts to play, and it stops. not just tops but it gets unable to restart or quit. I need to restart the laptop get it back. I tried reinstall, factory reset, deleting all images and containers, and making them again. But problem persists.
### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Apple chip m2
  - Docker Desktop Version:
  - 4.14.0

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Yalchin403** [comment]
The issue doesn't happen with the version 4.12.0

**Comment by stuartherbert** [comment]
I've been plagued with this exact same issue too. 

* Can confirm that it never happened with 4.12.0.
* I'm on Apple M1 not M2. 
* Happens for projects running x86 containers.
* Happens for projects running only arm64 containers.
* I can restart Docker by first going into Application Monitor and force-quitting all of the docker processes.

I have a second machine that has never run x86 containers. To date, it has never had this problem. May or may not be relevant.

This bug is _incredibly_ disruptive.

**Comment by sjuanati** [comment]
Same problem here with chipset Apple M1 Max.
After docker is running for a few minutes, I get the error:

    `invalid character 's' looking for beginning of value`

and then I have to kill all processes and restart docker.

**Comment by sjuanati** [comment]
I found a workaround that seems to prevent this issue although it's not a fix for the root cause.

So far I was running docker.app, executing a process through docker-compose and getting the error a few minutes afterwards that stopped docker. Then I was killing all docker processes manually through the Activity Monitor and restarting again docker.app. Let's say quite a painful iterating approach 😅

Instead, through a console, I just kill any docker process with:
`docker ps -q | xargs -L1 docker stop`
and then start docker with:
`open -a Docker`

So... if you don't need the docker.app, this might help in the meantime.

**Comment by sebmasterid** [comment]
Same problem with Intel Mac Book with or without Virtualiation framework, with gRPC Fuse or VirtioFS.
Docker desktop version 4.15.0

**Comment by crisanmm** [comment]
Same error on M1 Max, macOS 13.0.1, Docker Desktop 4.15.0

I downgraded Docker Desktop to 4.12.0 and it's working fine so far. The steps I followed for downgrading are here https://stackoverflow.com/questions/62217678/can-i-roll-back-to-a-previous-version-of-docker-desktop/64825028#64825028

**Comment by acbramley** [comment]
I was getting the same issue running selenium tests on one of my projects, downgrading to 4.12.0 also fixed it for me

**Comment by richardtape** [comment]
This is still an issue with version 4.15.0 (93002), M1, Mac OS 13.1.0.

I have no idea if it's related, but running `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check` after I have restarted Docker after a crash like above, I get one failed test with the error

```
[FAIL] DD0019: is the com.docker.vmnetd process responding? failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
```

**Comment by HendrikLevering** [comment]
I get the same error with 4.15.0, M1, Mac OS 13.1.0
After the error happens nothing works to restart docker. I have to restart my laptop to get docker running again.

**Comment by willbenica** [comment]
Just ran into this again. It's been plaguing me for a few months now.
docker v4.15.0 and running macos v12.6.2

**Comment by philimat** [comment]
I believe this thread may be suffering from the same issue as being discussed in #6530. There was a fix rolled into version 4.16, so I would encourage those of you in this thread to upgrade to that version and see if solves the issue.

**Comment by xkszltl** [comment]
We're seeing this very frequently on macOS 12 (x86) + 4.16.2 (95914), even with a simple interactive docker run of bash, sometimes it quit after a while of idling, with:
```
ERRO[0585] error waiting for container: invalid character 'c' looking for beginning of value 
```

The taskbar icon of docker desktop will show the booting animation, seems something's restarting, but taking forever.
After killing the docker desktop process, the next start will fail with that troubleshooting dialog, and factory reset won't help.

OS reboot, or killing `com.docker.backend`, will help restore everything back to normal.

I also found this old issue may be related, although not many answers there either:
- https://github.com/docker/for-mac/issues/5139

**Comment by willbenica** [comment]
> I believe this thread may be suffering from the same issue as being discussed in #6530. There was a fix rolled into version 4.16, so I would encourage those of you in this thread to upgrade to that version and see if solves the issue.

After seeing this, I updated docker and started the containers that I normally start. I left docker running over the weekend and didn't really do anything.

Came back to it this morning, and I have the same error as in the description. It doesn't seem that 4.16 fixes the issue.

**Comment by jrusev** [comment]
I am running Docker Desktop 4.15.0, on macOS Ventura, MacBook Pro 2019. I am getting `invalid character 's' looking for beginning of value` after running a cadence server container for a while (couple of minutes). Happens every time. I have to stop docker by killing the docker backend process, and restarting Docker Desktop. I was running the same container before without issues (last year).

**Comment by eduardocque** [comment]
+1

**Comment by falbuixech** [comment]
This happens to me on Windows, so it doesn't seem like a Mac only problem. More details on:

https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/336

**Comment by carlostrujillosamper** [comment]
![CleanShot 2023-02-27 at 16 58 51@2x](https://user-images.githubusercontent.com/50991922/221910718-4e27fc46-c736-4904-92f6-dfd293eb9646.png)
I deselected that and it seemed to fix the issue. I tried everything talked about on this thread and this is what ultimately fixed it. I'm on mac M1 , docker desktop version 4.16.2 (95914)
Hope this helps

**Comment by cybertunnel** [comment]
I can confirm turning off the Docker Compose V2 fixes the `invalid character '[char]' looking for beginning of value` error where `[char]` is any character. In this issue it is `s`.
I am running on macOS on latest version of docker and macOS with this issue. Hoping it is just a bug and a simple fix for the devs. Appreciate all the work everyone on this project does! 🥂

**Comment by RyadMM** [comment]
I am having the same issue and I tried everything mentioned, still get the error. Driving me crazy. Did multiple re-install, uncheck docker compose V2, clean purge data, factory resets etc. still getting the error.

Every time I have to kill all docker activity from the activity monitor.

I am running on mac m1, latest docker version v4.17.0, big sur

**Comment by samuelguesnier** [comment]
On Windows, I went to C:\Users\sam\AppData\Roaming\Docker , opened locked-directories file and replaced content with {} , then save file and restart docker desktop

**Comment by adamantal** [comment]
Unchecking compose V2, reinstalling Docker, clearing Docker cache, disabling experimental features did not resolve the problem for me.

Downgrading to [4.12.0](https://docs.docker.com/desktop/release-notes/#4120) solves the issue, but is not a long-term solution

**Comment by SammySkycrafts** [comment]
This issue is affecting me and another user too - Last known working version is 4.12.0 but as stated above, running this is not a long term solution and i am finding myself wanting to update however cannot due to the fact it will break some containers.

**Comment by ColeDCrawford** [comment]
Also experiencing this. Very disruptive.

**Comment by wimleers** [comment]
Just ran into this for the very first time, Docker Desktop `4.7.1`, which has been otherwise running fine for many months.

Docker pretends the container is still running when it is not. 😮

**Comment by nicks** [comment]
Hi all! Thanks for reporting these issues.

As far as I can tell, there are a few different bugs being reported here, and many (all?) of them have been fixed in newer versions of Docker Desktop (e.g., the selenium problem reported in this comment https://github.com/docker/for-mac/issues/6575#issuecomment-1363396096 which is tracked here: https://github.com/docker/for-mac/issues/6530)

The exact error message "invalid character 's' looking for beginning of value" is a bit of a red herring. It means that _something_ in the engine failed, but doesn't give you any useful information into what failed.

The message is due to a bug in the Docker CLI error-handling that is fixed here: https://github.com/moby/moby/pull/44739. We don't expect this error message to show up anymore in new versions of Docker Desktop.

If you still see issues after upgrading to Docker Desktop 4.22, please open a new issue, so we can track it separately. Thanks!

**Comment by CoderMiguel** [comment]
I am running several versions of Docker from 4.18 to 4.22 and still getting this error.

**Comment by Ruegen** [comment]
I'm viewing this issue too on an M1 mac
docker version: 4.24.2 (124339)
