### ISSUE TITLE
SSH connections to remote Docker host not closing properly

### ISSUE THREAD

**Issue by lucawint** [docker/for-mac#6834]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Using Docker with a remote context doesn't lead to unnecessary resource consumption.

### Actual behavior

Using Docker with a remote context leads to high memory usage on the remote host (likely also on the "client" but I haven't looked into that).

### Information

  - macOS Version: Ventura 13.2.1
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version: 4.19.0 (106363)
  
Using Docker through a remote context over SSH leads to high memory consumption on the remote Docker host. It seems the local "client" keeps opening new connections (every 15 minutes) to the remote and not closing them correctly. This spawns a new process on the remote host. Unfortunately this doesn't stop and new processes keep getting spawned.

I've tried this with 2 different remote Docker hosts:
- 1 in AWS - engine version 20.10.23, 
- 1 on local network - engine version 23.0.6

It happens on both so I'm thinking the local client is the more likely culprit. The resource consumption / connections increase seemed to happen more quickly/reliably with the AWS remote host.

From pstree output I think this is somehow caused by the `com.docker.build` process:

```
-+= 00001 root /sbin/launchd
 \-+= 97103 localuser /Applications/Docker.app/Contents/MacOS/Docker
   \-+= 97104 localuser /Applications/Docker.app/Contents/MacOS/com.docker.backend -watchdog -native-api
     |--- 01511 localuser docker serve --address unix:///Users/localuser/.docker/run/docker-cli-api.sock
     |-+- 01512 localuser com.docker.driver.amd64-linux -addr fd:3 -debug -native-api
     | |--- 01525 localuser /Applications/Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -addr fd:3 -debug -native-api
     | \--- 01536 localuser /Applications/Docker.app/Contents/MacOS/com.docker.virtualization --kernel /Applications/Docker.app/Contents/Resources/linuxkit/kernel --cmdline page_poiso
     |-+- 01513 localuser com.docker.extensions -address extension-manager.sock -watchdog
     | \--- 01524 localuser /Applications/Docker.app/Contents/MacOS/com.docker.extensions -address extension-manager.sock -watchdog
     |--- 01527 localuser com.docker.dev-envs
     |-+- 01529 localuser com.docker.build
     | |--= 02701 localuser ssh -l remotehostuser -- 192.168.1.70 docker system dial-stdio
     | |--= 02703 localuser ssh -l remotehostuser -- 192.168.1.70 docker system dial-stdio
     | |--= 02705 localuser ssh -l remotehostuser -- 192.168.1.70 docker system dial-stdio
     | |--= 02706 localuser ssh -l remotehostuser -- 192.168.1.70 docker system dial-stdio
     | |--= 02708 localuser ssh -l remotehostuser -- 192.168.1.70 docker system dial-stdio
     | |--= 02709 localuser ssh -l remotehostuser -- 192.168.1.70 docker system dial-stdio
     | \--= 02710 localuser ssh -l remotehostuser -- 192.168.1.70 docker system dial-stdio
     |--- 97110 localuser /Applications/Docker.app/Contents/MacOS/com.docker.backend -watchdog -native-api
     \-+- 97135 localuser /Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/MacOS/Docker Desktop --name=dashboard
       |--- 02066 localuser /Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Frameworks/Docker Desktop Helper (Renderer).app/Contents/MacOS/Docker Desktop Helper (R
       |--- 97176 localuser /Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Frameworks/Docker Desktop Helper (GPU).app/Contents/MacOS/Docker Desktop Helper (GPU) -
       \--- 97179 localuser /Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Frameworks/Docker Desktop Helper.app/Contents/MacOS/Docker Desktop Helper --type=utilit
```

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0038: is the connection to Docker working?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
	* com.docker.vpnkit is not running


[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[FAIL] DD0009: is the vpnkit API responding? dial unix vpnkit.diag.sock: connect: connection refused
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
	* com.docker.vpnkit is not running



Not all of the backend processes are running.
```

### Steps to reproduce the behavior

  1. Set up a remote context, e.g. `docker context create nuc --docker "host=ssh://remotehostuser@192.168.1.70"`
  2. Wait for at least 15 mins.
  3. Watch as the number of connections to the remote Docker host increases every 15 minutes, using for example `pgrep -c sshd` or check `pstree` output for the Docker process on the "local client". With the number of connections, the number of open processes and memory consumption increases:
  
<img width="603" alt="image" src="https://github.com/docker/for-mac/assets/24991340/7178b137-8411-4843-8752-e56b7789da28">

`smem` output on the remote host:

```
  PID User     Command                         Swap      USS      PSS      RSS
 1946 ec2-user docker system dial-stdio           0    10.3M    13.1M    36.2M
 1893 ec2-user docker system dial-stdio           0     9.9M    12.8M    35.9M
 2011 ec2-user docker system dial-stdio           0    10.0M    12.9M    35.9M
 1796 ec2-user docker system dial-stdio           0    10.0M    12.8M    35.8M
 1708 ec2-user docker system dial-stdio           0     9.8M    12.6M    35.7M
 1679 ec2-user docker system dial-stdio           0    10.0M    12.8M    35.7M
 1760 ec2-user docker system dial-stdio           0     9.8M    12.6M    35.6M
  893 ec2-user docker system dial-stdio           0     9.4M    12.3M    35.3M
  973 ec2-user docker system dial-stdio           0     9.2M    12.1M    35.3M
  922 ec2-user docker system dial-stdio           0     9.3M    12.1M    35.2M
 2183 ec2-user python ./smem -s rss -r -t         0     6.9M     7.0M     9.0M
29438 ec2-user -bash                              0     1.1M     1.6M     4.0M
31467 ec2-user -bash                              0     1.1M     1.6M     4.0M
29359 ec2-user -bash                              0     1.0M     1.5M     3.9M
```

I'm not sure why com.docker.build even needs to interact with the remote host every 15 mins, but that's not the point here I suppose.

I have configured SSH in a way that reuses connections btw , as described at 
https://docs.docker.com/engine/security/protect-access/#ssh-tips .

Not sure if I can dig any deeper by myself, let me know if I can provide any more information. Thank you for looking into this.

**Comment by ryan-shaw** [comment]
We are hitting this too, as soon as docker starts it opens SSH connections to _all_ SSH contexts and keeps opening more every 5 minutes. 

- macOS Version: Ventura 13.3.1
- Intel chip or Apple chip: Apple chip
- Docker Desktop Version: 4.19.0 (106363)

We have downgraded to 4.18.0 and blocked upgrading to 4.19.0 in our organisation until this is resolved.

**Comment by sanvean** [comment]
Same here, this really is a quite magnificent bug! A client update that slowly and steadily wipes out any server a developer has a docker ssh context configured for on their Mac.

**Comment by tetrode** [comment]
Same here (Docker desktop - Mac, server Debian Linux) both running the latest version of docker

**Comment by AndyA** [comment]
Same here. And I have no interest in Docker Desktop poking around in my configured contexts; I only want to run Docker images.

Is there any way to disable context discovery completely?

**Comment by DoubleREW** [comment]
Same here

macOS Version: Ventura 13.3.1
Intel chip or Apple chip: Apple chip
Docker Desktop Version: 4.19.0 (106363)

**Comment by jhofm** [comment]
just to add to the sense of urgency: same here. fortunately the bug knocked out a staging system first.

**Comment by frankfil** [comment]
Same issue here too.

macOS Ventura 13.4
Docker Desktop 4.19.0 (106363)

I have a context pointing to Docker running on a Synology NAS via SSH, and it will eventually cause the sshd process on the NAS to exhaust all memory essentially triggering a denial of service.

Like others this context is not being actively used but it still being connected to quite regularly.

**Comment by sacundim** [comment]
Ditto! I just troubleshooted a gradual memory starvation problem in a VM I set up in my NAS just to run Docker, and basically reproduced this ticket before I went on Google and found it. Apple Silicon, MacOS Ventura 13.3.1, Docker Desktop 4.19.0 (106363).

**Comment by frankfil** [comment]
Had to run Docker Desktop again today for a short time so thought I'd keep an eye on the remote connections from it.

Recap of my setup:

macOS Ventura 13.4
Docker Desktop 4.19.0 (106363)
Single remote context to a Synology NAS - this context is not the default as was not being used.

What I saw:

Upon startup it created 4 SSH connections to the NAS. Each connection results in ```docker system dial-stdio``` being started.

After 15 minutes it closed one of the connections it made previously and then opened another 6 new connections.

Another 15 minutes go by, it closes one of the connections from the last 6 it opened, then opens another 4 connections.

At this point I'd done what I needed to do and closed Docker Desktop, at which point all the remote connections get closed.

One thing I didn't do was note which of the connections it was closing, as in was it the first or last of the group each time. I only noted from which group of connections the closed one took place.

**Comment by lucawint** [comment]
I saw similar behavior during my debugging @frankfil .

It's been 3 weeks since I reported this and there seems to be no reaction whatsoever to an issue that is in my humble opinion, quite severe.

Sorry for the direct tag @bsousaa but I saw some comments from you in this repo and a PR, and I see Docker listed in your Github profile. Could you help us out here by making the correct people aware of this? Thank you!

**Comment by DoubleREW** [comment]
I still have this problem with v4.20

**Comment by trajano** [comment]
Seems to occur with Windows as well.

**Comment by tjsr** [comment]
I've been having this issue for a few months too, but it's only recently that I determined docker desktop was causing it.  I tried uninstalling every plugin just in case it was some kind of management plugin polling the contexts - but doesn't appear to be related.  It seems to be creating one new connection about every 5 minutes.
One of the little i3 NUCs I use as a docker dev server has been under so much load from the connections being made to it that it's basically getting DDoS'd - I've seen load averages as high as 340 (might even be higher - but when it is it's under so much load I can't get a response from it).  It hasn't managed to kill an i7 yet in the same way - but it did run out of ports to allocate connections to.

This would have to be one of the most serious bugs I've encountered in a long time - seems my only option is to just simply not have SSH remote contexts configured.

**Comment by niallnsec** [comment]
I've also been having this issue, its become an increasing nuisance over the past couple of months.

In the hopes of helping reach a resolution, I have done some tracing to try and identify the root of the problem. The ssh processes are spawned by `/Applications/Docker.app/Contents/MacOS/com.docker.build`

<details>
  <summary>com.docker.build Binary Version Info</summary>
  
```
linus@linus-M1 : ~
[0] % go version -m /Applications/Docker.app/Contents/MacOS/com.docker.build
/Applications/Docker.app/Contents/MacOS/com.docker.build: go1.20.4
	path	github.com/docker/desktop-build/cmd/com.docker.build
	mod	github.com/docker/desktop-build	(devel)
	dep	github.com/Masterminds/semver/v3	v3.2.0
	dep	github.com/agl/ed25519	v0.0.0-20170116200512-5312a6153412
	dep	github.com/beorn7/perks	v1.0.1
	dep	github.com/cenkalti/backoff/v4	v4.2.0
	dep	github.com/cespare/xxhash/v2	v2.2.0
	dep	github.com/containerd/console	v1.0.3
	dep	github.com/containerd/containerd	v1.7.0
	dep	github.com/containerd/continuity	v0.3.0
	dep	github.com/containerd/ttrpc	v1.2.1
	dep	github.com/containerd/typeurl/v2	v2.1.0
	dep	github.com/davecgh/go-spew	v1.1.1
	dep	github.com/docker/buildx	v0.11.0-rc1
	dep	github.com/docker/cli	v23.0.6+incompatible
	dep	github.com/docker/distribution	v2.8.2+incompatible
	dep	github.com/docker/docker	v23.0.6+incompatible
	=>	github.com/tonistiigi/docker	v0.10.1-0.20230516160859-7238f5e7d687

	dep	github.com/docker/docker-credential-helpers	v0.7.0
	dep	github.com/docker/go	v1.5.1-1.0.20160303222718-d30aec9fd63c
	dep	github.com/docker/go-connections	v0.4.0
	dep	github.com/docker/go-metrics	v0.0.1
	dep	github.com/docker/go-units	v0.5.0
	dep	github.com/emicklei/go-restful/v3	v3.10.1
	dep	github.com/felixge/httpsnoop	v1.0.3
	dep	github.com/fsnotify/fsnotify	v1.6.0
	dep	github.com/fvbommel/sortorder	v1.0.1
	dep	github.com/go-logr/logr	v1.2.3
	dep	github.com/go-logr/stdr	v1.2.2
	dep	github.com/go-openapi/jsonpointer	v0.19.5
	dep	github.com/go-openapi/jsonreference	v0.20.0
	dep	github.com/go-openapi/swag	v0.19.14
	dep	github.com/gofrs/flock	v0.8.1
	dep	github.com/gogo/googleapis	v1.4.1
	dep	github.com/gogo/protobuf	v1.3.2
	dep	github.com/golang-jwt/jwt	v3.2.2+incompatible
	dep	github.com/golang/protobuf	v1.5.2
	dep	github.com/google/gnostic	v0.5.7-v3refs
	dep	github.com/google/go-cmp	v0.5.9
	dep	github.com/google/gofuzz	v1.2.0
	dep	github.com/google/shlex	v0.0.0-20191202100458-e7afc7fbc510
	dep	github.com/gorilla/mux	v1.8.0
	dep	github.com/grpc-ecosystem/go-grpc-middleware	v1.3.0
	dep	github.com/grpc-ecosystem/grpc-gateway/v2	v2.11.3
	dep	github.com/imdario/mergo	v0.3.15
	dep	github.com/josharian/intern	v1.0.0
	dep	github.com/json-iterator/go	v1.1.12
	dep	github.com/klauspost/compress	v1.16.0
	dep	github.com/labstack/echo/v4	v4.10.0
	dep	github.com/labstack/gommon	v0.4.0
	dep	github.com/mailru/easyjson	v0.7.6
	dep	github.com/mattn/go-colorable	v0.1.13
	dep	github.com/mattn/go-isatty	v0.0.16
	dep	github.com/matttproud/golang_protobuf_extensions	v1.0.4
	dep	github.com/moby/buildkit	v0.11.0-rc3.0.20230411142536-333ee9158128
	dep	github.com/moby/locker	v1.0.1
	dep	github.com/moby/patternmatcher	v0.5.0
	dep	github.com/moby/spdystream	v0.2.0
	dep	github.com/moby/sys/sequential	v0.5.0
	dep	github.com/moby/sys/signal	v0.7.0
	dep	github.com/moby/term	v0.0.0-20221120202655-abb19827d345
	dep	github.com/modern-go/concurrent	v0.0.0-20180306012644-bacd9c7ef1dd
	dep	github.com/modern-go/reflect2	v1.0.2
	dep	github.com/morikuni/aec	v1.0.0
	dep	github.com/munnerz/goautoneg	v0.0.0-20191010083416-a7dc8b61c822
	dep	github.com/nasdf/ulimit	v0.0.1
	dep	github.com/opencontainers/go-digest	v1.0.0
	dep	github.com/opencontainers/image-spec	v1.1.0-rc2.0.20221005185240-3a7f492d3f1b
	dep	github.com/opencontainers/runc	v1.1.5
	dep	github.com/pelletier/go-toml	v1.9.5
	dep	github.com/pkg/errors	v0.9.1
	dep	github.com/prometheus/client_golang	v1.14.0
	dep	github.com/prometheus/client_model	v0.3.0
	dep	github.com/prometheus/common	v0.37.0
	dep	github.com/prometheus/procfs	v0.8.0
	dep	github.com/serialx/hashring	v0.0.0-20190422032157-8b2912629002
	dep	github.com/sirupsen/logrus	v1.9.0
	dep	github.com/spf13/cobra	v1.6.1
	dep	github.com/spf13/pflag	v1.0.5
	dep	github.com/theupdateframework/notary	v0.6.1
	dep	github.com/tonistiigi/fsutil	v0.0.0-20230105215944-fb433841cbfa
	dep	github.com/tonistiigi/units	v0.0.0-20180711220420-6950e57a87ea
	dep	github.com/tonistiigi/vt100	v0.0.0-20210615222946-8066bb97264f
	dep	github.com/valyala/bytebufferpool	v1.0.0
	dep	github.com/valyala/fasttemplate	v1.2.2
	dep	github.com/zeebo/xxh3	v1.0.2
	dep	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc	v0.40.0
	dep	go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace	v0.40.0
	dep	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp	v0.40.0
	dep	go.opentelemetry.io/otel	v1.14.0
	dep	go.opentelemetry.io/otel/exporters/otlp/internal/retry	v1.14.0
	dep	go.opentelemetry.io/otel/exporters/otlp/otlptrace	v1.14.0
	dep	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc	v1.14.0
	dep	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp	v1.14.0
	dep	go.opentelemetry.io/otel/metric	v0.37.0
	dep	go.opentelemetry.io/otel/sdk	v1.14.0
	dep	go.opentelemetry.io/otel/trace	v1.14.0
	dep	go.opentelemetry.io/proto/otlp	v0.19.0
	dep	golang.org/x/crypto	v0.2.0
	dep	golang.org/x/net	v0.7.0
	dep	golang.org/x/oauth2	v0.4.0
	dep	golang.org/x/sync	v0.1.0
	dep	golang.org/x/sys	v0.6.0
	dep	golang.org/x/term	v0.5.0
	dep	golang.org/x/text	v0.7.0
	dep	golang.org/x/time	v0.2.0
	dep	google.golang.org/genproto	v0.0.0-20230306155012-7f2fa6fef1f4
	dep	google.golang.org/grpc	v1.53.0
	dep	google.golang.org/protobuf	v1.28.1
	dep	gopkg.in/inf.v0	v0.9.1
	dep	gopkg.in/yaml.v2	v2.4.0
	dep	gopkg.in/yaml.v3	v3.0.1
	dep	k8s.io/api	v0.26.2
	=>	k8s.io/api	v0.25.4

	dep	k8s.io/apimachinery	v0.26.2
	=>	k8s.io/apimachinery	v0.25.4

	dep	k8s.io/client-go	v0.26.2
	=>	k8s.io/client-go	v0.25.4

	dep	k8s.io/klog/v2	v2.90.1
	dep	k8s.io/kube-openapi	v0.0.0-20221012153701-172d655c2280
	dep	k8s.io/utils	v0.0.0-20230220204549-a5ecb0141aa5
	dep	sigs.k8s.io/json	v0.0.0-20220713155537-f223a00ba0e2
	dep	sigs.k8s.io/structured-merge-diff/v4	v4.2.3
	dep	sigs.k8s.io/yaml	v1.3.0
	build	-buildmode=exe
	build	-compiler=gc
	build	-trimpath=true
	build	CGO_ENABLED=0
	build	GOARCH=arm64
	build	GOOS=darwin
	build	vcs=git
	build	vcs.revision=26ff8725d071cbd15d47470294004d81c0513c2f
	build	vcs.time=2023-05-18T10:15:50Z
	build	vcs.modified=false
```

</details>

In order to triage the issue, I needed to attach a debugger to the process. Unfortunately this is not straightforward on macOS as the binary is configured to use the hardened runtime and does not have the `com.apple.security.get-task-allow` entitlement enabled. The solution is to re-sign the binary with the entitlement enabled using a local code signing certificate. If anyone else using macOS wishes to continue debugging this issue I have included the steps to do this:

<details>
  <summary>Enable debugging for com.docker.build</summary>
 
1. If you don't already have a code signing certificate configured:
   1. Open Keychain Access
   2. On the menu bar, click Keychain Access -> Certificate Assistant -> Create Certificate Authority.
   3. Select Identity Type: Self-Signed Root CA, User Certificate: Code Signing and click Create
   4. On the menu bar, click Keychain Access -> Certificate Assistant -> Create a certificate.
   5. Give the certificate a name, in this example I used the name `dbg-server`, set the Identity Type to Leaf and the certificate type to Code Signing.
   6. Click Create
   7. You should now see the two certificates in Keychain Access in the login chain under the "My Certificates" tab. Double click the root CA you generated and expand the Trust section in the pop up window.
   8. Set "Code Signing" to "Always Trust" and close the dialog. You will be asked to enter your password to confirm the change.
2. Make a backup copy of `/Applications/Docker.app/Contents/MacOS/com.docker.build` as this process will replace the existing signature.
3. Sign the file using the following commands:
```
cat > debuggee-entitlement.xml <<ENTITLEMENT
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"\>
<plist version="1.0">
<dict>
    <key>com.apple.security.get-task-allow</key>
    <true/>
</dict>
</plist>
ENTITLEMENT
```

```
codesign --entitlements debuggee-entitlement.xml -fs dbg-server /Applications/Docker.app/Contents/MacOS/com.docker.build
```

4. Finally, restart docker desktop so that the privilege takes effect.

At this point you will be able to attach a debugger to the process. You can find the PID in Activity Monitor and attach to it using delve by running: `dlv attach <PID>`

</details>

After attaching to the process using delve I set a breakpoint on the osexec.Command function as that is what is used to spawn the SSH sub processes.

```
(dlv) break os/exec.Command
Breakpoint 1 set at 0x1005ec6a0 for os/exec.Command() os/exec/exec.go:376
(dlv) continue
```

After waiting for a little while, the breakpoint was hit and there were 3 interesting goroutines:

```
  Goroutine 233 - User: net/http/transport.go:2638 net/http.(*persistConn).roundTrip (0x1007c02d8) [select]
  Goroutine 234 - User: net/http/transport.go:1382 net/http.(*Transport).getConn (0x1007b9388) [select]
* Goroutine 235 - User: os/exec/exec.go:376 os/exec.Command (0x1005ec6a0) (thread 23340660)
```

<details>
  <summary>Stack for Goroutine 235</summary>

```
(dlv) stack
0  0x00000001005ec6a0 in os/exec.Command
   at os/exec/exec.go:376
1  0x00000001005f1cf8 in golang.org/x/sys/execabs.Command
   at golang.org/x/sys@v0.6.0/execabs/execabs.go:99
2  0x00000001007fc588 in github.com/docker/cli/cli/connhelper/commandconn.New
   at github.com/docker/cli@v23.0.6+incompatible/cli/connhelper/commandconn/commandconn.go:40
3  0x00000001007fee14 in github.com/docker/cli/cli/connhelper.getConnectionHelper.func1
   at github.com/docker/cli@v23.0.6+incompatible/cli/connhelper/connhelper.go:50
4  0x00000001007b87cc in net/http.(*Transport).dial
   at net/http/transport.go:1176
5  0x00000001007bb004 in net/http.(*Transport).dialConn
   at net/http/transport.go:1614
6  0x00000001007b9dcc in net/http.(*Transport).dialConnFor
   at net/http/transport.go:1456
7  0x00000001007b9d1c in net/http.(*Transport).queueForDial.func1
   at net/http/transport.go:1425
8  0x0000000100522134 in runtime.goexit
   at runtime/asm_arm64.s:1172
```

</details>

The stack trace shows that the issue may be inside of `github.com/docker/cli`, however, due to the http transports system asynchronous nature we have to look at the other goroutines to find the calls the triggered this stack trace.

<details>
  <summary>Stack for Goroutine 234</summary>

```
(dlv) stack
 0  0x00000001004f0df4 in runtime.gopark
    at runtime/proc.go:382
 1  0x0000000100501190 in runtime.selectgo
    at runtime/select.go:327
 2  0x00000001007b9388 in net/http.(*Transport).getConn
    at net/http/transport.go:1382
 3  0x00000001007b5670 in net/http.(*Transport).roundTrip
    at net/http/transport.go:590
 4  0x000000010079f3cc in net/http.(*Transport).RoundTrip
    at net/http/roundtrip.go:17
 5  0x0000000100761190 in net/http.send
    at net/http/client.go:252
 6  0x0000000100760b08 in net/http.(*Client).send
    at net/http/client.go:176
 7  0x0000000100762924 in net/http.(*Client).do
    at net/http/client.go:716
 8  0x000000010088098c in net/http.(*Client).Do
    at net/http/client.go:582
 9  0x000000010088098c in github.com/docker/docker/client.(*Client).doRequest
    at github.com/docker/docker@v23.0.6+incompatible/client/request.go:137
10  0x000000010087c8b4 in github.com/docker/docker/client.(*Client).Ping
    at github.com/docker/docker@v23.0.6+incompatible/client/ping.go:28
11  0x0000000100867e34 in github.com/docker/docker/client.(*Client).NegotiateAPIVersion
    at github.com/docker/docker@v23.0.6+incompatible/client/client.go:227
12  0x0000000100867c7c in github.com/docker/docker/client.(*Client).getAPIPath
    at github.com/docker/docker@v23.0.6+incompatible/client/client.go:194
13  0x000000010088060c in github.com/docker/docker/client.(*Client).sendRequest
    at github.com/docker/docker@v23.0.6+incompatible/client/request.go:116
14  0x000000010086cb98 in github.com/docker/docker/client.(*Client).get
    at github.com/docker/docker@v23.0.6+incompatible/client/request.go:36
15  0x000000010086cb98 in github.com/docker/docker/client.(*Client).ContainerInspect
    at github.com/docker/docker@v23.0.6+incompatible/client/container_inspect.go:18
16  0x0000000100f2c8fc in github.com/docker/buildx/util/dockerutil.(*ClientAPI).ContainerInspect
    at <autogenerated>:1
17  0x0000000100f7d0f0 in github.com/docker/buildx/driver/docker-container.(*Driver).Info
    at github.com/docker/buildx@v0.11.0-rc1/driver/docker-container/driver.go:281
18  0x0000000100f29398 in github.com/docker/buildx/driver.(*cachedDriver).Info
    at <autogenerated>:1
19  0x0000000100f5fa54 in github.com/docker/buildx/builder.(*Node).loadData
    at github.com/docker/buildx@v0.11.0-rc1/builder/node.go:173
20  0x0000000100f5f840 in github.com/docker/buildx/builder.(*Builder).LoadNodes.func2.1
    at github.com/docker/buildx@v0.11.0-rc1/builder/node.go:118
21  0x0000000100c9626c in golang.org/x/sync/errgroup.(*Group).Go.func1
    at golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75
22  0x0000000100522134 in runtime.goexit
    at runtime/asm_arm64.s:1172
```

</details>

<details>
  <summary>Stack for Goroutine 234</summary>

```
(dlv) stack
 0  0x00000001004f0df4 in runtime.gopark
    at runtime/proc.go:382
 1  0x0000000100501190 in runtime.selectgo
    at runtime/select.go:327
 2  0x00000001007c02d8 in net/http.(*persistConn).roundTrip
    at net/http/transport.go:2638
 3  0x00000001007b56b4 in net/http.(*Transport).roundTrip
    at net/http/transport.go:603
 4  0x000000010079f3cc in net/http.(*Transport).RoundTrip
    at net/http/roundtrip.go:17
 5  0x0000000100761190 in net/http.send
    at net/http/client.go:252
 6  0x0000000100760b08 in net/http.(*Client).send
    at net/http/client.go:176
 7  0x0000000100762924 in net/http.(*Client).do
    at net/http/client.go:716
 8  0x000000010088098c in net/http.(*Client).Do
    at net/http/client.go:582
 9  0x000000010088098c in github.com/docker/docker/client.(*Client).doRequest
    at github.com/docker/docker@v23.0.6+incompatible/client/request.go:137
10  0x000000010087c8b4 in github.com/docker/docker/client.(*Client).Ping
    at github.com/docker/docker@v23.0.6+incompatible/client/ping.go:28
11  0x0000000100867e34 in github.com/docker/docker/client.(*Client).NegotiateAPIVersion
    at github.com/docker/docker@v23.0.6+incompatible/client/client.go:227
12  0x0000000100867c7c in github.com/docker/docker/client.(*Client).getAPIPath
    at github.com/docker/docker@v23.0.6+incompatible/client/client.go:194
13  0x000000010088060c in github.com/docker/docker/client.(*Client).sendRequest
    at github.com/docker/docker@v23.0.6+incompatible/client/request.go:116
14  0x00000001008879d8 in github.com/docker/docker/client.(*Client).get
    at github.com/docker/docker@v23.0.6+incompatible/client/request.go:36
15  0x00000001008879d8 in github.com/docker/docker/client.(*Client).ServerVersion
    at github.com/docker/docker@v23.0.6+incompatible/client/version.go:12
16  0x0000000100f34a90 in github.com/docker/buildx/util/dockerutil.(*ClientAPI).ServerVersion
    at <autogenerated>:1
17  0x0000000100f675b0 in github.com/docker/buildx/driver/docker.(*Driver).Info
    at github.com/docker/buildx@v0.11.0-rc1/driver/docker/driver.go:24
18  0x0000000100f29398 in github.com/docker/buildx/driver.(*cachedDriver).Info
    at <autogenerated>:1
19  0x0000000100f5fa54 in github.com/docker/buildx/builder.(*Node).loadData
    at github.com/docker/buildx@v0.11.0-rc1/builder/node.go:173
20  0x0000000100f5f840 in github.com/docker/buildx/builder.(*Builder).LoadNodes.func2.1
    at github.com/docker/buildx@v0.11.0-rc1/builder/node.go:118
21  0x0000000100c9626c in golang.org/x/sync/errgroup.(*Group).Go.func1
    at golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75
22  0x0000000100522134 in runtime.goexit
    at runtime/asm_arm64.s:1172
```

</details>

These two stack traces suggest to me that either `github.com/docker/docker/client` is not cleaning up its conns correctly or, more likely, that something in `github.com/docker/cli@v23.0.6+incompatible/cli/connhelper/commandconn` is not properly cleaning up the SSH process once the conn is closed.

There is an interesting commit from 6 months ago authored by @pdaig which may be what caused this issue to become apparent: https://github.com/docker/cli/commit/e547881e27f25789694bf0e3888eb4ab5b07b72a
I don't think this could _cause_ the bug, but if the cancellation of the context was eventually clearing up old SSH processes then it would have masked the issue of the processes not being closed when they are no longer needed.

There is another commit authored by @laurazard that has been added after the version of the package used in the compiled binary which is of interest:
https://github.com/docker/cli/commit/a5ebe2282aabaf983c116525af4a7c5eeedf2c6e
This commit makes significant changes to the way the SSH conn is handled. It is not clear to me if this has fixed the issue as I have not as yet worked out the exact cause of the SSH processes not being closed. The next steps in debugging the compiled binary involve tracking the lifetime of the conn object to identify if and when the Close() function is called, but this is more complicated and time consuming.

With that in mind, I am very much hoping that a docker maintainer who is more familiar with the code can use the information above to understand the cause of the problem more easily. If not I will continue my debugging journey as this issue is causing more and more issues for me and a fair few other people it seems.

**Comment by laurazard** [comment]
Thanks for the ping @niallnsec — I'be been trying to improve this code recently, and there's still a lot of refactoring/changes to do there. I'm currently out, but when I'm back next week I'll try to dig a bit more (with your provided information — thanks!) and track down the issue/see if it's still present.

**Comment by sanvean** [comment]
Hi @niallnsec @laurazard I think the broader question here is why is Docker Desktop auto-connecting to any of the SSH contexts a developer has configured locally in the first place. Not why it's failing to clean up after itself before then re-connecting again to the all contexts again every few minutes until it wipes out each server.

I'm not sure if I missed something in the docs but my intention when setting up my SSH contexts (and I'm sure it's the same for others in this thread) wasn't to give Docker Desktop permission to connect to my configured servers whenever it feels like it?

Why is Docker Desktop attempting to connect to any of the configured contexts without being instructed to do so?

**Comment by niallnsec** [comment]
Hi @sanvean There is a TODO in the code which appears to relate to this behaviour:
https://github.com/docker/buildx/blob/daba16f4be78f4bb6bb6ac73ac5c5615023a2bd7/builder/node.go#L42

I think that a discussion on docker loading info about all configured build contexts instead of lazy loading on demand is best suited to its own issue, since this appears to be a known limitation of the current code and is awaiting an improvement.

**Comment by laurazard** [comment]
> I think the broader question here is why is Docker Desktop auto-connecting to any of the SSH contexts a developer has configured locally in the first place. Not why it's failing to clean up after itself before then re-connecting again to the all contexts again every few minutes until it wipes out each server.

It might intersect with that question, but ultimately that's a separate issue and not the issue described in the OP, which does have to do with connections not closing properly – which we need to look into.

> I'm not sure if I missed something in the docs but my intention when setting up my SSH contexts (and I'm sure it's the same for others in this thread) wasn't to give Docker Desktop permission to connect to my configured servers whenever it feels like it?

> Why is Docker Desktop attempting to connect to any of the configured contexts without being instructed to do so?

There could be a lot of reasons for this – as @niallnsec mentioned, we do need to do improvements regarding how/when remote contexts are loaded – however, this requires discussion and, for people in this thread, can be being caused by factors outside of our control: since the CLI will attempt a connection anytime it's loaded, in order to negotiate API versions with the daemon and other logic, anything running that invokes the CLI (periodically – as mentioned in this thread – or not) can be causing these connections. That includes things like the VS Code Docker extension, or JetBrain's analogous Docker integration, which aren't managed by us.

**Comment by laurazard** [comment]
> Note nowhere does @lucawint describe manually running docker -c context etc. to open a SSH connection to a remote host.

That's what I've attempted to explain though – anything that invokes the CLI, when a remote context is configured, might result in an attempted connection since the CLI connects on startup in order to negotiate API versions, etc. A manual `docker -c [context] ...` isn't necessary for this to happen. It might be the case that something changed either on the client/server side re: connection keep-alives, etc., and that this is just surfacing a behaviour that already existed, or that the cause is something else.

Regardless, it is an issue and I've pinged people internally to take a look at it in the meantime, so thanks for bringing it up.

**Comment by sanvean** [comment]
Many thanks! @laurazard

**Comment by pdaig** [comment]
Hi all!

@niallnsec
Maybe I can help shed some light on why the change to `commandConn` was made.
You can read the full discussion in docker/cli#3900 and https://github.com/docker/compose/issues/9448#issuecomment-1264263721.
I'll try to summarize below:

<details>
<summary>Short summary of docker/compose#9448 (docker/cli#3900)</summary>

Since Go's http client pools connections, the same SSH connection might be reused for multiple http requests.
To my knowledge, we don't really have direct control over *when* a connection is closed by the http client. It's kept alive for a certain amount of time after the http request completes (and new connections are created on demand if the number of concurrent http requests exceeds the number of available, already established connections).

When `commandConn` is created, it receives its caller's context. The http request will execute and the context will eventually complete. The connection however, will remain in the pool for future reuse. If the SSH process takes the context of the caller, it'll be killed when the caller's context completes (successfully or not) and it'll fail when the pooled connection is eventually reused.

That's what was happening when running `docker compose pull` with more than 1 service.

>error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=docker&tag=latest": command [ssh -l user -- host docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=

This was fixed by "disconnecting" the process from the caller's context. As counter-intuitive as it may seems, after discussing this at length, I think it's the right solution since the lifetime of the process actually *outlives* that of the caller's context.

</details>

While investigating this issue, I also noticed that idle connections weren't cleanly closed before the main docker process exited. Since the spawned SSH subprocess were still cleaned up by the OS/runtime it wasn't causing any real problem. Still, it was worth fixing to properly clean up resources. So I opened a PR back in december, docker/cli#3899, but some tests were failing and I haven't got around to fixing it yet. At the time, it didn't seem that important since it didn't cause any problem, so there was no hurry to merge this change.

This might not be the cause at all but it seemed related enough that I thought I'd mention it. Again, I have no proof that it would fix the accumulation of SSH process since, last time I checked, all subprocesses were automatically cleaned up when the parent process exited anyway.

If some code were to create multiple `Client` object without properly closing them, I suppose it *could* theoretically cause an accumulation of SSH processes/connections but I haven't verified that and as far as I know this isn't the case for docker CLI (but I have no idea what Docker Desktop or other tools are doing).

Personally, I haven't noticed any problem with Docker Desktop under Windows/WSL (v4.20.1) and I have about 10 SSH context saved on my machine.

**Comment by bvv-jmedved** [comment]
I can confirm the same problem on Docker v4.20.1 on Windows 10 Pro/22H2 WSL. One remote context - yesterday 135 unclosed connections in about 6 hours.

**Comment by laurazard** [comment]
Update: I've confirmed this, and testing with the HEAD of http://github.com/docker/cli (w/ the changes from https://github.com/docker/cli/commit/a5ebe2282aabaf983c116525af4a7c5eeedf2c6e) the issue doesn't present anymore. We'll try to make a release soon and include this fix.

**Comment by niallnsec** [comment]
Thanks a million! Much appreciated :)

**Comment by laurazard** [comment]
We'll be doing a patch release of Docker Desktop soon which includes fixes for this issue. I'll keep this issue updated, thanks all ❤️

**Comment by lorenrh** [comment]
We have released Docker Desktop 4.21.1, containing a fix for this issue! Please see: https://docs.docker.com/desktop/release-notes/#4211

**Comment by frankfil** [comment]
I've just upgraded to 4.21.1 and am seeing slightly different version of this same issue.

In this case what I am seeing is that each time you switch to the remote context a new set of connections is made, but any old connections are not closed.

Steps to reproduce:

In one terminal run the following command to keep an eye on remote connections:

```
watch -n 10 ssh remote.docker.host 'ps -aef | grep docker'
```

In a second terminal switch the context to the remote host:

```
docker context use remote.docker.host
```

Observe a set of connections to the remote host get created.

Switch back to the local Docker context:

```
docker context use default
```

Observe that not only do the initial remote connections not get closed, but a few more are created!

Repeat the above steps, switching between the remote and local contexts. Each time you make a switch, regardless of whether you switch to or away from the remote context, a new set of connections is made to the remote host.

Looks like switching to the remote context creates slightly more connections that switching away. And sometimes one of the connections will be closed when switching away from the remote context.

But otherwise it's the same issue but instead of happening every ~15 minutes it just happens on each context switch.

**Comment by sacundim** [comment]
I just went to Docker Desktop 4.21.1 (114176) on MacOS 13.3.1 and I still see it create new connections and processes every 15 minutes without cleaning up the old. Expand below for `lsof` and `ps` output on the remote host.


<details>

```
[core@fcos-docker ~]$ ps -au core -o pid,user,%mem,start_time,args
    PID USER     %MEM START COMMAND
   1643 core      0.3 05:08 /usr/lib/systemd/systemd --user
   1645 core      0.5 05:08 (sd-pam)
   1658 core      0.1 05:08 sshd: core@pts/0
   1659 core      0.1 05:08 -bash
   2549 core      0.8 05:59 docker system dial-stdio
   2588 core      0.8 05:59 docker system dial-stdio
   2589 core      0.8 05:59 docker system dial-stdio
   2738 core      0.8 06:14 docker system dial-stdio
   2778 core      0.8 06:14 docker system dial-stdio
   2779 core      0.8 06:14 docker system dial-stdio
   2903 core      0.8 06:14 docker system dial-stdio
   2943 core      0.8 06:14 docker system dial-stdio
   2984 core      0.1 06:14 sshd: core@notty
   2985 core      0.8 06:14 docker system dial-stdio
   3115 core      0.8 06:29 docker system dial-stdio
   3176 core      0.1 06:29 sshd: core@notty
   3177 core      0.8 06:29 docker system dial-stdio
   3181 core      0.1 06:29 sshd: core@notty
   3189 core      0.8 06:29 docker system dial-stdio
   3348 core      0.1 06:44 sshd: core@notty
   3349 core      0.8 06:44 docker system dial-stdio
   3412 core      0.1 06:44 sshd: core@notty
   3413 core      0.1 06:44 sshd: core@notty
   3414 core      0.8 06:44 docker system dial-stdio
   3419 core      0.8 06:44 docker system dial-stdio
   3585 core      0.1 06:59 sshd: core@notty
   3586 core      0.8 06:59 docker system dial-stdio
   3647 core      0.1 06:59 sshd: core@notty
   3648 core      0.1 06:59 sshd: core@notty
   3649 core      0.8 06:59 docker system dial-stdio
   3653 core      0.8 06:59 docker system dial-stdio
   3701 core      0.1 06:59 sshd: core@notty
   3702 core      0.8 06:59 docker system dial-stdio
   3807 core      0.0 07:08 ps -au core -o pid,user,%mem,start_time,args


[core@fcos-docker ~]$ sudo lsof -i4 
COMMAND    PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
systemd-r  787 systemd-resolve   10u  IPv4  23900      0t0  UDP *:hostmon 
systemd-r  787 systemd-resolve   11u  IPv4  23901      0t0  TCP *:hostmon (LISTEN)
systemd-r  787 systemd-resolve   16u  IPv4  23907      0t0  UDP _localdnsstub:domain 
systemd-r  787 systemd-resolve   17u  IPv4  23908      0t0  TCP _localdnsstub:domain (LISTEN)
systemd-r  787 systemd-resolve   18u  IPv4  23909      0t0  UDP _localdnsproxy:domain 
systemd-r  787 systemd-resolve   19u  IPv4  23910      0t0  TCP _localdnsproxy:domain (LISTEN)
NetworkMa  796            root   25u  IPv4  26267      0t0  UDP fcos-docker:bootpc->_gateway:bootps 
chronyd    833          chrony    5u  IPv4  26112      0t0  UDP localhost:323 
sshd       865            root    3u  IPv4  26176      0t0  TCP *:ssh (LISTEN)
sshd      1635            root    4u  IPv4  27830      0t0  TCP fcos-docker:ssh->192.168.50.249:61870 (ESTABLISHED)
sshd      1658            core    4u  IPv4  27830      0t0  TCP fcos-docker:ssh->192.168.50.249:61870 (ESTABLISHED)
sshd      2970            root    4u  IPv4  35334      0t0  TCP fcos-docker:ssh->192.168.50.249:49702 (ESTABLISHED)
sshd      2984            core    4u  IPv4  35334      0t0  TCP fcos-docker:ssh->192.168.50.249:49702 (ESTABLISHED)
sshd      3162            root    4u  IPv4  36653      0t0  TCP fcos-docker:ssh->192.168.50.249:50321 (ESTABLISHED)
sshd      3163            root    4u  IPv4  36657      0t0  TCP fcos-docker:ssh->192.168.50.249:50320 (ESTABLISHED)
sshd      3176            core    4u  IPv4  36657      0t0  TCP fcos-docker:ssh->192.168.50.249:50320 (ESTABLISHED)
sshd      3181            core    4u  IPv4  36653      0t0  TCP fcos-docker:ssh->192.168.50.249:50321 (ESTABLISHED)
sshd      3341            root    4u  IPv4  39961      0t0  TCP fcos-docker:ssh->192.168.50.249:51393 (ESTABLISHED)
sshd      3348            core    4u  IPv4  39961      0t0  TCP fcos-docker:ssh->192.168.50.249:51393 (ESTABLISHED)
sshd      3397            root    4u  IPv4  37243      0t0  TCP fcos-docker:ssh->192.168.50.249:51402 (ESTABLISHED)
sshd      3398            root    4u  IPv4  37247      0t0  TCP fcos-docker:ssh->192.168.50.249:51401 (ESTABLISHED)
sshd      3412            core    4u  IPv4  37247      0t0  TCP fcos-docker:ssh->192.168.50.249:51401 (ESTABLISHED)
sshd      3413            core    4u  IPv4  37243      0t0  TCP fcos-docker:ssh->192.168.50.249:51402 (ESTABLISHED)
sshd      3578            root    4u  IPv4  37566      0t0  TCP fcos-docker:ssh->192.168.50.249:52168 (ESTABLISHED)
sshd      3585            core    4u  IPv4  37566      0t0  TCP fcos-docker:ssh->192.168.50.249:52168 (ESTABLISHED)
sshd      3633            root    4u  IPv4  37644      0t0  TCP fcos-docker:ssh->192.168.50.249:52176 (ESTABLISHED)
sshd      3634            root    4u  IPv4  37648      0t0  TCP fcos-docker:ssh->192.168.50.249:52177 (ESTABLISHED)
sshd      3647            core    4u  IPv4  37644      0t0  TCP fcos-docker:ssh->192.168.50.249:52176 (ESTABLISHED)
sshd      3648            core    4u  IPv4  37648      0t0  TCP fcos-docker:ssh->192.168.50.249:52177 (ESTABLISHED)
sshd      3694            root    4u  IPv4  40544      0t0  TCP fcos-docker:ssh->192.168.50.249:52180 (ESTABLISHED)
sshd      3701            core    4u  IPv4  40544      0t0  TCP fcos-docker:ssh->192.168.50.249:52180 (ESTABLISHED)
```

I also get these printed to my SSH session:

```
channel 21: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
channel 23: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
channel 23: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
channel 23: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
```

</details>

**Comment by lucawint** [comment]
Thank you for your work on this @laurazard and @lorenrh, unfortunately the issue is not resolved on my side either in Docker Desktop version 4.21.1 (114176) / Engine: 24.0.2.

I still see the exact same behavior, connections being opened every 15 minutes and memory usage increasing on the remote host. I see 16 connections are currently open on a remote host since adding the remote context about 1 hour ago.

**Comment by ryan-shaw** [comment]
4.21.1 is still exhibiting the same behaviour for me

**Comment by laurazard** [comment]
Ahhh, thank you both for the reports. It seems while rushing to get a fix out, I missed some things –

I assumed it was fixed since with the changes from https://github.com/docker/cli/commit/a5ebe2282aabaf983c116525af4a7c5eeedf2c6e since, on my end, I no longer see stuck `ssh -- <contest host> docker system dial-stdio` processes. However, I didn't notice that there were still `docker system dial-stdio` processes on the remote host.

I'll keep taking a look at this to try to get a fix out soon – thanks all for the input.

**Comment by quentinsf** [comment]
I have a server that started to die repeatedly, and eventually I began to suspect the number of `docker system dial-stdio` processes running on it, each of which had a large resident memory footprint.
On a thread elsewhere I noticed a suggestion that this might be due to the connection depending on an SSH key with a password, and the use of 1Password to supply that.  Perhaps the docker engine only understands ssh-agent?
I was using the macOS Keychain to provide mine -- I had `UseKeychain yes` in my ssh config -- and removing that _seems_ to have fixed the problem... it's early days yet, but it's looking hopeful.

As others have said, the real issue is that Docker _shouldn't_ be trying to make these connections in the first place, but until that's fixed, the short-term problem may be something to do with the SSH connection requiring, say, a touch-ID interaction or a 1Password dialog before it can proceed?

**Comment by AndyA** [comment]
I'm using ssh-agent - no UseKeychain yes - and I'm still seeing the problem.

**Comment by quentinsf** [comment]
Mmm, yes, I fear it was a temporary respite.  The server just died again.

**Comment by ilude** [comment]
Any word on this getting fixed? It a very serious resource leak at this point.

Here are some commands to help somewhat. but PLEASE REVIEW before running on your systems:

Windows Powershell - Kill all ssh.exe processes currently running
``` [powershell]
taskkill /F /IM ssh.exe /T
```

Linux - Kill all ssh connection that are running the docker system dial-stdio command 
```[bash]
ps -ef | grep -v $(who -u | awk '{print $6}') | grep 'docker system dial-stdio' | grep -v grep | awk '{print $3}' | xargs -r kill -9
```

**Comment by sacundim** [comment]
> Any word on this getting fixed? It a very serious resource leak at this point.

I'm seconding this. The bug here all but makes the SSH remote hosts feature unusable, IMHO

**Comment by ilude** [comment]
And just to be clear this is not a mac only issue I am running docker desktop on windows 10 currently

![image](https://github.com/docker/for-mac/assets/219478/2a483161-ff37-4583-aaeb-7030f487a940)


```
docker info
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 10
  Running: 4
  Paused: 0
  Stopped: 6
 Images: 293
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.28GiB
 Name: docker-desktop
 ID: 8c5bbce2-0004-4cc0-9b5b-dcec9604c934
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by HollisTech** [comment]
So this 'magnificent bug'! is generic and not restricted to docker for windows (https://github.com/docker/for-win/issues/13584). Yay! Now can we get it fixed? I'd like to use remote contexts, they were fairly useful.

**Comment by ramki88** [comment]
Is there any workaround for this, except for quitting docker desktop and use only the remote ones?

**Comment by bsousaa** [comment]
@ramki88 @HollisTech @ilude @sacundim can you confirm you are getting this issue with the latest Docker Desktop version?

**Comment by whobutsb** [comment]
I was pulling my hair out for a while with this bug.  It might be sacrilegious to suggest this recommendation in this project but I migrated to [OrbStack](https://orbstack.dev) for my projects and it solved the bug.  I might come back to Docker Desktop in the future, but I got to be honest i'm really liking the alternative.

**Comment by ilude** [comment]
> @ramki88 @HollisTech @ilude @sacundim can you confirm you are getting this issue with the latest Docker Desktop version?

Yes it is still happening with the latest version of docker desktop

![image](https://github.com/docker/for-mac/assets/219478/90c0df8d-3268-49f2-99c6-cdfd72e5f367)

**Comment by niallnsec** [comment]
@bsousaa I can confirm it is still happening on 4.22.0 (117440) on Mac as well.

I did some more debugging on the issue, I did begin to think the problem could be at least somewhat related to using SSH as a transport for http.Client. It seems that the way it is implemented is such that every connection the http.Client opens results in a new SSH process spawning. I am not convinced that is a generally viable architecture considering the way http.Client pools connections and runs keepalives. Looking at the code for http.Client, I was expecting the number of SSH processes to max out around 100 instances. For me, this has largely been true, but others here have mentioned reaching higher numbers. I have only seen much higher numbers in cases where I had restarted Docker Desktop several times without restarting my computer or killing the SSH processes.

Unfortunately I couldn't debug very far as a lot of the code in the paths that are spawning SSH processes are in private repositories instead of being part of the open source codebase.

**Comment by trajano** [comment]
Also happens on Windows

**Comment by niallnsec** [comment]
> BTW @ramki88 @niallnsec are you connecting to a Docker Server that's managed by AWS or something that's version 20.x? I am thinking if that may be the factor.

In my case I am connecting to another box on my local network, just checked it and it is running 24.0.4.

**Comment by HollisTech** [comment]
Docker Desktop 4.21.1 (114176) is currently the newest version available. <- windows docker for win. And yes it is busted. 

This is easy to test apparently on both mac and windows. Just create a remote ssh context and monitor the ssh process count.

**Comment by ramki88** [comment]
> Also happens on Windows with the current version
> 
> BTW @ramki88 @niallnsec are you connecting to a Docker Server that's managed by AWS or something that's version 20.x? I am thinking if that may be the factor.

@trajano, have two remote connections, one is in azure and the other is in GCP. Both of them are 24.0.5

**Comment by ramki88** [comment]
@laurazard, could you please advise if there are any workaround to stop DD from making so many SSH connections, 71 connections for 2 remote in that last 2 hours has been made.

**Comment by ryan-shaw** [comment]
> @laurazard, could you please advise if there are any workaround to stop DD from making so many SSH connections, 71 connections for 2 remote in that last 2 hours has been made.

The best I could find was to downgrade docker

**Comment by laurazard** [comment]
@ramki88 For now, downgrading DD is an option. Other than that, I've pinged people internally and looks like we've got a fix, so we'll try to get a proper fix into the next release. I'm sorry for how long this has taken to get fixed :|

**Comment by ramki88** [comment]
> @ramki88 For now, downgrading DD is an option. Other than that, I've pinged people internally and looks like we've got a fix, so we'll try to get a proper fix into the next release. I'm sorry for how long this has taken to get fixed :|

Thanks @laurazard and @ryan-shaw , for anyone with the question of a workaround below are two options known so far.
1. Downgrade DD to 4.18.0 [Mentioned by @ryan-shaw](https://github.com/docker/for-mac/issues/6834#issuecomment-1543577015)
2. Quit DD and use only the remote engines, which I am right now

**Comment by bsousaa** [comment]
We just released 4.23 - can you give it a try? https://docs.docker.com/desktop/release-notes/

**Comment by HollisTech** [comment]
So far it looks good. Zero zombie ssh processes on windows. I only set one ssh context. I'll add some more and see what happens.

**Comment by quentinsf** [comment]
Looking good here too - thanks!

**Comment by frankfil** [comment]
v4.23 looks much improved from my very limited testing (on macOS 13.5.2).

I have noticed that each time you switch to a remote context a new connection is made that stays open even if you switch the context away. So if you switch to a remote, switch back to local, then back to remote you end up with 2 connections.

But I've not let it sit for very long so the old connections might disconnect after a while.

Having said that, it's not creating a number of connections on startup. And it doesn't look like it's creating multiple new connections on context switch or every few minutes like older versions did.

**Comment by ramki88** [comment]
> We just released 4.23 - can you give it a try? https://docs.docker.com/desktop/release-notes/

Most awaited update of DD. Looks good so far with 4 remotes.
Thanks docker team!

**Comment by tjsr** [comment]
I've installed the version listed and will get around to testing the functionality later, however what I did notice is that I couldn't spot where this fix was actually mentioned in the release notes.  Is this under the heading of something that isn't quite so obvious?

**Comment by lucawint** [comment]
A few days have passed now with the remote context installed without any unnecessary SSH connections being opened.

I will close this issue now since no one has reported encountering the reported issue with the latest release.

Thanks again to everyone who worked on fixing this!

**Comment by Kishlol** [comment]
Reset all the settings of Mac

**Comment by Kishlol** [comment]
Configure the Wi-Fi network for Mac, according to my phone

**Comment by texpert** [comment]
Here it is occurring again on 4.37.1

macOS Sonoma 14.7.1
