### ISSUE TITLE
not booting

### ISSUE THREAD

**Issue by Sajjad-Taghinezhad** [docker/for-mac#6964]
### Description

After update to latest version, docker not booting up and stuck in booting state

### Reproduce

Update from setting page 

### Expected behavior

should booting up 

### docker version

```bash
all docker commands stuck and not working
```

### docker info

```bash
all docker commands stuck and not working
```

### Diagnostics ID

---

### Additional Info

I tried theses : 
- restart docker 
- purge data 
- reset to factory 
- reinstall 

But, it is stucked in booting

**Comment by Sajjad-Taghinezhad** [comment]
Now I tried older version and it's ok. 
version : [4.21.1](https://docs.docker.com/desktop/release-notes/#4211) this is ok

**Comment by milewski** [comment]
Me too, I have just reset my Mac back to factory settings, installed docker first thing.. and it won't boot

iMac Retina 5k
MacOs: 12.6.8

**Comment by milewski** [comment]
> Now I tried older version and it's ok. version : [4.21.1](https://docs.docker.com/desktop/release-notes/#4211) this is ok

https://docs.docker.com/desktop/release-notes/#4211 This version works

**Comment by GBirkel** [comment]
Same issue here.  Deleted all data and config, then waited a very long time, and the engine eventually came up.  No idea what the problem was.  No idea if it will happen again.

**Comment by Sajjad-Taghinezhad** [comment]
> Same issue here. Deleted all data and config, then waited a very long time, and the engine eventually came up. No idea what the problem was. No idea if it will happen again.

It will up after delete data and wait a long time, but not work for me 
commands like `docks ps` or `docker pull` not works

**Comment by lorenrh** [comment]
Hi all, 

we have just released a new version of docker desktop, would you mind checking that out and letting us know if that fixed the issue? See[ release notes.](https://docs.docker.com/desktop/release-notes/)

**Comment by milewski** [comment]
Hi @lorenrh, unfortunately, it still not working, I have upgraded to version [4.23.0](https://docs.docker.com/desktop/release-notes/#4230) and docker stays stuck at "starting the docker engine" for over an hour, I have tried rebooting the computer and "Reset to factory defaults", but it won't boot. Are there any logs we can provide to assist in solving this issue?

<img width="1382" alt="Screen Shot 2023-09-12 at 12 59 57 PM" src="https://github.com/docker/for-mac/assets/2874967/a930610d-e26d-4277-9498-f368f0c7a461">

<img width="872" alt="Screen Shot 2023-09-12 at 1 00 34 PM" src="https://github.com/docker/for-mac/assets/2874967/7be13941-8f36-4152-985c-e5694712776f">

**Comment by milewski** [comment]
And I forgot to mention that reverting back to [4.21.1](https://docs.docker.com/desktop/release-notes/#4211) docker starts in less than a minute

**Comment by milewski** [comment]
Hi @lorenrh this is the diagnostics ID that was generated: `FFEAF58C-4ACD-44D6-B8D2-84BF77A302EA/20230912100711 `
