### ISSUE TITLE
4.24.2 Extensions Socket Crash

### ISSUE THREAD

**Issue by archen** [docker/for-mac#7029]
### Description

after upgrading to `4.24.2` on macOS 13.6 (Apple Silicon) the docker engine crashed. attempts to restart docker for desktop and my machine both resulted in the same outcome: docker desktop hangs while trying to restart the docker engine.

In the troubleshooting pane, I noticed a repetitive error with extensions; so I disabled them in configuration... and that's when the crashing started

```
Error: connect ENOENT extension-manager.sock
```

I now see the above error right before the app crashes.

### Reproduce

try to open Docker Desktop

### Expected behavior

Docker and kubernetes engines are running and usable...

### docker version

```bash
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           default
```
```


### docker info

```bash
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     [redacted]/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     [redacted]/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     [redacted]/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     [redacted]/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     [redacted]/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     [redacted]/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     [redacted]/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     [redacted]/.docker/cli-plugins/docker-scout

Server:
```
```


### Diagnostics ID

na

### Additional Info

creating a diagnostics ID from the UI or from the cli is not possible.

**Comment by tigco** [comment]
Same here, but I cannot disable there extensions. When I try to disable them, I get error:
![image](https://github.com/docker/for-mac/assets/15081919/710273d6-d189-44f2-a3d6-b3e5260e2e17)


> ### Description
> after upgrading to `4.24.2` on macOS 13.6 (Apple Silicon) the docker engine crashed. attempts to restart docker for desktop and my machine both resulted in the same outcome: docker desktop hangs while trying to restart the docker engine.
> 
> In the troubleshooting pane, I noticed a repetitive error with extensions; so I disabled them in configuration... and that's when the crashing started
> 
> ```
> Error: connect ENOENT extension-manager.sock
> ```
> 
> I now see the above error right before the app crashes.
> 
> ### Reproduce
> try to open Docker Desktop
> 
> ### Expected behavior
> Docker and kubernetes engines are running and usable...
> 
> ### docker version
> ```shell
> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
> Client:
>  Cloud integration: v1.0.35+desktop.5
>  Version:           24.0.6
>  API version:       1.43
>  Go version:        go1.20.7
>  Git commit:        ed223bc
>  Built:             Mon Sep  4 12:28:49 2023
>  OS/Arch:           darwin/arm64
>  Context:           default
> ```
> 
>  ```
> 
> 
> ### docker info
> 
> ```bash
> Client:
>  Version:    24.0.6
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc.)
>     Version:  v0.11.2-desktop.5
>     Path:     [redacted]/.docker/cli-plugins/docker-buildx
>   compose: Docker Compose (Docker Inc.)
>     Version:  v2.22.0-desktop.2
>     Path:     [redacted]/.docker/cli-plugins/docker-compose
>   dev: Docker Dev Environments (Docker Inc.)
>     Version:  v0.1.0
>     Path:     [redacted]/.docker/cli-plugins/docker-dev
>   extension: Manages Docker extensions (Docker Inc.)
>     Version:  v0.2.20
>     Path:     [redacted]/.docker/cli-plugins/docker-extension
>   init: Creates Docker-related starter files for your project (Docker Inc.)
>     Version:  v0.1.0-beta.8
>     Path:     [redacted]/.docker/cli-plugins/docker-init
>   sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
>     Version:  0.6.0
>     Path:     [redacted]/.docker/cli-plugins/docker-sbom
>   scan: Docker Scan (Docker Inc.)
>     Version:  v0.26.0
>     Path:     [redacted]/.docker/cli-plugins/docker-scan
>   scout: Docker Scout (Docker Inc.)
>     Version:  v1.0.7
>     Path:     [redacted]/.docker/cli-plugins/docker-scout
> 
> Server:
> ```
> 
>  ```
> 
> 
> ### Diagnostics ID
> 
> na
> 
> ### Additional Info
> 
> creating a diagnostics ID from the UI or from the cli is not possible.
> ```

**Comment by stevau5** [comment]
Also dealing with this right now

**Comment by jordanful** [comment]
Same problem here.

**Comment by eduardobcolombo** [comment]
Same problem here

**Comment by davewhiteley** [comment]
I was experiencing the same issue, however it appears to have been resolved by upgrading to macOS 14 (Sonoma)

**Comment by tigco** [comment]
> I was experiencing the same issue, however it appears to have been resolved by upgrading to macOS 14 (Sonoma)

Can someone confirm that upgrading to MacOS 14 resolves the issue?

**Comment by jordanful** [comment]
I'm on Sonoma and still experiencing the issue. Completely blocked and can't use Docker at all.

**Comment by marcobalk-berlinger** [comment]
I had the same on Sonoma, until I upgraded to [4.25.0](https://docs.docker.com/desktop/release-notes/#4250)

**Comment by jordanful** [comment]
> I had the same on Sonoma, until I upgraded to [4.25.0](https://docs.docker.com/desktop/release-notes/#4250)

Confirmed that Sonoma + Docker for Mac upgrade fixed the issue for me.

**Comment by bsousaa** [comment]
Thank you for the confirmation. I'm closing the issue. Please update the thread if you keep facing it and I will re-open.

**Comment by lidijarad** [comment]
I had this same issue confirming that that Sonoma + Docker for Mac 4.25.0 also fixed the issue for me 🌈

**Comment by sskorol** [comment]
I use Monterey, and I see the same error after updating Docker to 4.25.0.
This sounds weird that I must upgrade the whole OS to make Docker work again. Backward compatibility?
Why do you even allow to install an update on an incompatible OS version then?
