### ISSUE TITLE
"Start Docker Desktop when you log in" does not work.

### ISSUE THREAD

**Issue by sppatel** [docker/for-mac#7052]
### Description

https://github.com/docker/for-mac/issues/6723 was supposed to resolve this issue but it still does not work.

### Reproduce

1.  Turn on the setting.
2. Reboot.
3. Docker is not started.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.25.0 (126437)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/sppatel/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/sppatel/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/sppatel/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/sppatel/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/sppatel/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/sppatel/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/sppatel/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/sppatel/.docker/cli-plugins/docker-scout

Server:
 Containers: 7
  Running: 4
  Paused: 0
  Stopped: 3
 Images: 23
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 15.61GiB
 Name: linuxkit-0a89a32585fd
 ID: 1c6d67e8-4c64-4b79-9c5c-a317ce9f2f73
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

D36594FB-653A-4AE9-989B-FAD676F6A37B/20231101145146

### Additional Info

OSX 13.6.1

**Comment by osorionicolas** [comment]
same here

**Comment by snowbrdngtrix** [comment]
Same situation. Had to downgrade back down to version 4.24.2 to resolve issue. 

I believe it to be the same scenario that was fixed in a prior release and was working up to version 4.24.2. Here is a snippet from the [4.17.0 release notes](https://docs.docker.com/desktop/release-notes/#4170)
Fixed a bug that caused the Start Docker Desktop when you log in setting not to work. Fixes [docker/for-mac#6723](https://github.com/docker/for-mac/issues/6723).

**Comment by rfay** [comment]
Yes, this feature no longer works after years of working.  Same on arm64 and amd64. 

I did a factory reset and then set it to auto start, same problem.

F779B64C-4F74-4FE9-851C-880E07D43B1D/20231111164414

**Comment by jirsbek** [comment]
Just updated to 4.25.1 and unfortunately this issue persists.

**Comment by mediaxtend** [comment]
Same problem here with 4.25.1 (128006).
I tried:

1. "Uninstall" from "Troubleshoot".
2. Trash "Docker Desktop" from Applications folder, then empty trash.
3. Remove configuration files:
```
rm -rf ~/Library/Application\ Support/Docker\ Desktop
rm -rf ~/Library/Containers/com.docker.docker
rm -rf ~/Library/Group\ Containers/group.com.docker
rm -rf ~/.docker
```
4. Wait that Docker items disappear from background task management (`sudo sfltool dumpbtm`).

And then restart the Mac, re-install application, check again "Start Docker Desktop when you log in", log-out (or restart)…still the same.

**Comment by rfay** [comment]
Still broken in 4.25.2

**Comment by bsousaa** [comment]
Thanks, we escalated internally and will be fixed in 4.26

**Comment by trensen** [comment]
I can confirm that updating to 4.26.0 fixes the issue for me
