### ISSUE TITLE
Docker v4.31.0 - Network Issues within/between Containers

### ISSUE THREAD

**Issue by jo-tools** [docker/for-mac#7332]
### Description

I'm running the following Docker Compose setup:  
https://github.com/jo-tools/docker/blob/main/local-cubesql-volumes/docker-compose.yml

This runs a Database Server (cubeSQL) and a web administration tool.
The setup is preconfigured, so that one can just click 'Connect' in the Web Admin to successfully connect:
- Hostname: `host.docker.internal`
- Port: `4430`

-----
No Issues with Docker v.4.30.0 and earlier

-----
However, with Docker v4.31.0 the connect can't be established any longer.  
Interestingly, changing the Host from `host.docker.internal` to the effective Host's IP (e.g. `192.168.1.x`) works to establish a connection.

So something has changed in v4.31.0 which causes issues with Network Connections within/between Containers.

### Reproduce

1. Use this `docker-compose.yml`:  
   https://github.com/jo-tools/docker/blob/main/local-cubesql-volumes/docker-compose.yml
2. `docker-compose up -d `
3. Open the Web Admin Tool in the Browser: `http://localhost:4431`
4. Push the Button `Connect`

### Expected behavior

Connection to the Database Server via `host.docker.internal` on Port `4430` can be established.

Actual Behavior:
- works with Docker v4.30.0
- connection errors with Docker v4.31.0 (via `host.docker.internal:4430`)
- connection errors with Docker v4.31.0 (via `cubesql:4430`), which should also work since that's the hostname of the Network that the two containers are both part of.
- works with Docker v4.31.0 only when connecting via Host's real/effective IP (e.g. `192.168.1.x`)

### docker version

```bash
Client:
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:26:02 2024
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.31.0 (153195)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:22 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    26.1.4
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1-desktop.1
    Path:     /Users/juerg/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1-desktop.1
    Path:     /Users/juerg/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     /Users/juerg/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/juerg/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.24
    Path:     /Users/juerg/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/juerg/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.2.0
    Path:     /Users/juerg/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/juerg/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.9.3
    Path:     /Users/juerg/.docker/cli-plugins/docker-scout

Server:
 Containers: 8
  Running: 2
  Paused: 0
  Stopped: 6
 Images: 8
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.31-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.755GiB
 Name: docker-desktop
 ID: dd331a20-17bd-4cf5-a2da-7ae5f90b26f6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/juerg/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

D8B99358-A952-49AC-A00D-0CC40DA51EB0/20240616195445

### Additional Info

- macOS Sonoma 14.5
- MacBook Pro 16-inch, 2019
- Processor: 2.6 GHz 6-Core Intel Core i7

**Comment by jo-tools** [comment]
This might be related to Issue https://github.com/docker/for-mac/issues/7324

**Comment by foriam** [comment]
We have a similar issue. `host.docker.internal` now resolves to an IPv6 address.
Confirm with, for example: `docker run --rm alpine:latest getent hosts host.docker.internal`

**Comment by jo-tools** [comment]
> We have a similar issue. `host.docker.internal` now resolves to an IPv6 address.

Interesting...

`ping` uses the IPv4 address, and it can't ping the IPv6 address:

> ping: connect: Network is unreachable

```
# getent hosts host.docker.internal
fdc4:f303:9324::254 host.docker.internal
```

```
# nslookup -query=AAAA host.docker.internal
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   host.docker.internal
Address: fdc4:f303:9324::254
```

```
# nslookup -query=A host.docker.internal
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   host.docker.internal
Address: 192.168.65.254
```

```
# ping -c 2 host.docker.internal
PING host.docker.internal (192.168.65.254) 56(84) bytes of data.
64 bytes from 192.168.65.254 (192.168.65.254): icmp_seq=1 ttl=63 time=0.285 ms
64 bytes from 192.168.65.254 (192.168.65.254): icmp_seq=2 ttl=63 time=0.702 ms

--- host.docker.internal ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 0.285/0.493/0.702/0.208 ms
```

```
# ping -c 2 192.168.65.254
PING 192.168.65.254 (192.168.65.254) 56(84) bytes of data.
64 bytes from 192.168.65.254: icmp_seq=1 ttl=63 time=0.304 ms
64 bytes from 192.168.65.254: icmp_seq=2 ttl=63 time=0.345 ms

--- 192.168.65.254 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1043ms
rtt min/avg/max/mdev = 0.304/0.324/0.345/0.020 ms
```

```
# ping -c 2 fdc4:f303:9324::254
ping: connect: Network is unreachable
```

```
# ping -c 2 ip6-localhost
PING ip6-localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.025 ms
64 bytes from localhost (::1): icmp_seq=2 ttl=64 time=0.041 ms

--- ip6-localhost ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1046ms
rtt min/avg/max/mdev = 0.025/0.033/0.041/0.008 ms
```

**Comment by jo-tools** [comment]
So it seems the issue is that with Docker v4.31.0 `host.docker.internal` resolves to an **IPv6 address**, which is in an **unreachable network**...

...so any service trying to _(preferrably)_ use the IPv6 address won't work any longer _(unless it uses the working IPv4 address as a fallback)_

**Comment by levischuckeats** [comment]
Thank you for documenting this issue. Several on my team have encountered it when upgrading.

**Comment by mliudev** [comment]
My team is also stuck on 4.30 because of it.

**Comment by jo-tools** [comment]
Note: The Docker Image used in the original post *(which lead to discover this isse)* has been updated with a fix for this issue.

If someone wants to reproduce using the originally posted steps, then the mentioned `docker-compose.yml` needs to be changed to use the previous/affected docker image:

> ### Reproduce
> 1. Use this `docker-compose.yml`:
>    https://github.com/jo-tools/docker/blob/main/local-cubesql-volumes/docker-compose.yml  
>    edit `docker-compose.yml` and change  
>    from: `image: jotools/cubesql-webadmin` *(the 'latest' is updated with a fix for this issue)*
>    to: `image: jotools/cubesql-webadmin:1.0.0` *(use the affected image which works with Docker < v3.31.0, but fails to connect with Docker v4.31.0)*
> 2. `docker-compose up -d `
> 3. Open the Web Admin Tool in the Browser: `http://localhost:4431`
> 4. Push the Button `Connect`

Anyway - I don't think it's necessary to use that docker compose setup to reproduce this issue.  
The other replies show in more detail what the underlying issue is.

**Comment by TamerShlash** [comment]
Similar issue here. An nginx container resolves `host.docker.internal` to an IPv6 address and then cannot reach it.

**Comment by basbiesheuvel** [comment]
@jo-tools what did you change in the cubesql-webadmin image to make it work on 4.31 ?

**Comment by jo-tools** [comment]
> @jo-tools what did you change in the cubesql-webadmin image to make it work on 4.31 ?

I've fixed the client connector.

If the hostname resolves to both IPv4 and IPv6 addresses, it'll try to connect to both and uses the first successful one (which in Docker v4.31 will be the IPv4 address, since the IPv6 address can't be reached).

The bug in the client connector had been that it aborted with every error before (e.g. because of the IPv6 address not reachable), and didn't try the other resolved address instead.
The good thing with this (now fixed/improved) client connector bug has been that this Docker issue has been discovered ;)

**Comment by tdalbo92** [comment]
I may have missed it, but is there a config or something to work around this?  We just hit it with our local Envoy containers refusing to connect to other services running in Compose.  Downgrade seems to be the only straightforward option, but if there's another way, that would be great.  

Making our app server and dependencies work with IPv6 would take a decent amount of work, given that work would all be individually container specific.

**Comment by tlbraams** [comment]
The release notes for 4.33.0 listed a bug fix for this issue, but I'm still seeing IPv6 addresses assigned to `host.docker.internal` with that version.

<details>
<summary>Version info</summary>

```
% docker version
Client:
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:54:12 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.33.0 (160616)
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:14 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

**Comment by diggabyte** [comment]
We're also still seeing this in 4.33

We've tried rolling back to earlier versions of docker desktop (<= 4.30) and continue to be unable to reach `host.docker.internal` from within a running container. This is a major disruptor to our teams development environments.

1. Does anyone have rollback instructions that actually work? 
2. Are there any other workarounds until a fix can be made?

Version Info:
```
Client:
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:54:12 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.33.0 (160616)
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:14 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```

**Comment by bpholt** [comment]
FYI, `gateway.docker.internal` seems to have the same problem.

**Comment by MisterSquishy** [comment]
Paraphrasing some stuff from a conversation with support:

These is a new setting planned in an upcoming release (called `IPv4 only`, under Settings > Resources > Network). I was able to test it on a dev build and it fixed this issue. They are hopeful it will be included in `4.34.0` but there's a possibility it slips to `4.35.0` 🤞

**Comment by tlbraams** [comment]
Looks like they weren't able to include it in 4.34.0.

**Comment by woodser** [comment]
I'm also having this issue. Would really appreciate a fix. Thanks.

**Comment by lbsonix** [comment]
I'm also having this issue - would be really great to have it fixed. Thank you

**Comment by maksym-kurdyukov-mark43** [comment]
+1. Would really appreciate for a fix. Thanks.

**Comment by tlbraams** [comment]
> Paraphrasing some stuff from a conversation with support:
> 
> These is a new setting planned in an upcoming release (called `IPv4 only`, under Settings > Resources > Network). I was able to test it on a dev build and it fixed this issue. They are hopeful it will be included in `4.34.0` but there's a possibility it slips to `4.35.0` 🤞

Not seeing this option after updating to 4.35, also didn't spot anything in the release notes

<details>
<summary>Version info</summary>

```
% docker version
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:38:18 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.35.0 (172550)
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:19 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

**Comment by barnash** [comment]
Please try to include this in the coming version, some of us are really counting on it for our day to day work, and are actually stuck in version 4.28.0

**Comment by tlbraams** [comment]
I did discover that the (new) [settings config](https://docs.docker.com/desktop/settings/) includes `IPv4Only` and `IPv6Only`, both set to false. If you change `IPv4Only` and do a full docker restart, it'll use IPv4 for host.docker.internal, so it appears the setting was release, just not the UI to enable/disable it. 😅

**Comment by barnash** [comment]
> I did discover that the (new) [settings config](https://docs.docker.com/desktop/settings/) includes `IPv4Only` and `IPv6Only`, both set to false. If you change `IPv4Only` to true and do a full docker restart, it'll use IPv4 for host.docker.internal, so it appears the setting was release, just not the UI to enable/disable it. 😅

@tlbraams Not sure what you mean, I didn't see anything in the settings config.
Are you saying that in the latest version we can change the configuration, just not through the UI?
I tried that and didn't succeed, if you have done it, can you please tell us how?

**Comment by acj** [comment]
What worked for me on macOS with 4.35.0:
1. Quit Docker Desktop
2. Edit `~/Library/Group Containers/group.com.docker/settings-store.json` (the path given in the doc that @tlbraams linked) and change `IPv4Only` to `true`. Make sure `IPv6Only` is `false`.
3. Start Docker Desktop

**Comment by tlbraams** [comment]
> > I did discover that the (new) [settings config](https://docs.docker.com/desktop/settings/) includes `IPv4Only` and `IPv6Only`, both set to false. If you change `IPv4Only` to true and do a full docker restart, it'll use IPv4 for host.docker.internal, so it appears the setting was release, just not the UI to enable/disable it. 😅
> 
> [@tlbraams](https://github.com/tlbraams) Not sure what you mean, I didn't see anything in the settings config. Are you saying that in the latest version we can change the configuration, just not through the UI? I tried that and didn't succeed, if you have done it, can you please tell us how?

Did you perhaps edit `settings.json`? as acj mentions, docker now uses the `settings-store.json` file. Those steps are indeed what I intended to indicate.

**Comment by oole** [comment]
The issue is still present in 4.35.1 (173168).

I had both the `settings.json` and the `settings-store.json` present, made sure that I have both set accordingly:

> "IPv4Only": true,
> "IPv6Only": false

That did the trick. Thank you @acj!

**Comment by marcbutler** [comment]
This issue is still present in 4.36.0 (175267).

I found I only modified the `settings-store.json`.

Thank you @acj!

**Comment by e-compton-bb** [comment]
This is still happening in v4.40.0... very confusing behaviour when devs upgrade to docker and host names become unreachable

**Comment by maksym-kurdyukov-mark43** [comment]
After latest updates IPv4 modifier stop working for `4.41.x` (Docker Desktop, MacOS 15.4.1, Intel).
To apply `IPv4Only` in `settings.json` and `settings-store.json` again I have to rollback to version `4.40.0`.

Thank you @acj!

**Comment by max-k7v** [comment]
After latest updates IPv4 modifier stop working for 4.41.x (Docker Desktop, MacOS 15.4.1, Intel).
To apply `IPv4Only` in `settings*.json` again I've rolled back to version 4.40.0.
Thank you @acj!

**Comment by matthewadams** [comment]
.

**Comment by NikitaKharkov** [comment]
Looks like 4.42 resolved this issue.
I found that our var resolved to ipv4 ip back. (I use IPv4Only solution in settings.json)

**Comment by matthewadams** [comment]
@NikitaKharkov I just tried 4.42 and it's still broken for me :/  I had to revert back to 4.39.

**Comment by danielloader** [comment]
Still broken on v4.44.0 for me. This is quite the feature at this point. Something as core as host.docker.internal shouldn't be broken out the box.

Better yet, my settings-store.json value no longer works. Wonderful. Looking forward to telling everyone to ignore the updates and then inevitably finding out no one did (nor should they).

```json
{
  "AutoStart": false,
  "Cpus": 8,
  "DisplayedOnboarding": true,
  "DockerAppLaunchPath": "/Applications/Docker.app",
  "EnableCLIHints": true,
  "EnableDockerAI": false,
  "EnableDockerMCPToolkit": false,
  "EnableInference": false,
  "HostNetworkingEnabled": true,
  "IPv4Only": true,
  "IPv6Only": false,
  "LicenseTermsVersion": 2,
  "MemoryMiB": 12288,
  "SettingsVersion": 43,
  "ShowInstallScreen": false,
  "UpdateInstallTime": 0,
  "UseBackgroundIndexing": false,
  "UseVirtualizationFramework": true
}
```

**Comment by acj** [comment]
@danielloader Maybe we can tease out the key settings. Comparing configs, the differences I see are `HostNetworkingEnabled` (false), `IPv4Only` (unspecified), `IPv6Only` (unspecified), and `UseVirtualizationFramework` (false, I'm using the VMM beta). Since v4.42.x my pod/container networking has been stable across dozens to hundreds of cycles per day. I'm on 4.43.2 currently but will upgrade to 4.44.0 and try it out.

**Comment by danielloader** [comment]
The issue wasn't an issue when I forced the application in the container to use IPv4 only dns lookups via docker compose settings.

So that's a workaround of sorts...

**Comment by jontro** [comment]
@danielloader How do you specify those settings?

**Comment by danielloader** [comment]
Well for me, since the container was envoy proxy envoy has configuration options for the upstream proxy dns lookups to be v4 only. Obviously this isn't a general purpose solution and relies on your application being able to disable ipv6 lookups. Ideally I'd just like for host.docker.internal to resolve correctly.

**Comment by matthewadams** [comment]
Appears to still be borkded on 4.48.0 & 4.49.0

**Comment by tlbraams** [comment]
I'm currently running 4.48.0 without issue. IIRC, I was also able to use 4.47.0 and 4.46.0, not sure when I managed to get everything working.

At some point I discovered a new setting in Docker>Settings>Resources>Network called "Default networking mode"
It took a bit of fiddling to get it working, not sure of the exact steps. 
I've removed the "IPv4Only" and"IPv6Only" settings from the `settings-store.json` and I have the default networking mode set to IPv4 only, and the Inhibit DNS resolution for IPv4/IPv6 set to filter IPv6 records.

<img width="755" height="266" alt="Image" src="https://github.com/user-attachments/assets/38bf592c-d6dc-428d-bb98-149a69841c48" />

```
~ % docker run alpine:latest getent hosts host.docker.internal
192.168.65.254    host.docker.internal  host.docker.internal
```

**Comment by matthewadams** [comment]
@tlbraams You're a life saver 🛟!  That worked.

**Comment by KoljaFrahm** [comment]
This still seems to be the case with 4.63, you have to select "Filter IPv6 (AAAA records), otherwise it doesn't work
